### ISSUE TITLE
Warn on Uncaught Exceptions

### ISSUE THREAD

**Issue by vip-ehowlett** [fsharp/fslang-suggestions#1097]
I propose we add a warning to uncaught exceptions. Similar to non-exhaustive pattern matching, I think it'd be very useful to make non-exhaustive error handling throw a warning. I know there are couple existing issue for making exceptions easier to deal with, but, I think this is a little different in scope. 

When inter-operating with C#, or consuming F# but especially C#, it can be near impossible to make sure you've caught every exception down the call stack without having to manually look at all the different functions which is very tedious and time consuming... perfect job for a computer! It would be extremely nice if the compiler could tell us if there's some exception that could be thrown and has no handle for in the call stack. 

This might not even be possible to do with interop code. It might require C# to adopt the java-style throws clause, but I don't know so that's why I'm asking on here. 

The existing way of approaching this problem in F# is ...
None?

## Pros and Cons 

The advantages of making this adjustment to F# are ...
- More sound code
- Better tooling 
- Better interop experience 

The disadvantages of making this adjustment to F# are ...
Hard to think of one. Annoying if you don't want to handle all the warnings?

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XXL Not sure on this, I'm assuming it's going to take a decent amount of work because it's based on context. No experience with compilers. 

Related suggestions: (put links to related suggestions here)
I believe https://github.com/fsharp/fslang-suggestions/issues/1094 is somewhat related.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
You're gonna catch ArgumentExceptions and ArgumentNullExceptions and NullReferenceExceptions? ¯\_(ツ)_/¯

**Comment by cartermp** [comment]
> Hard to think of one. Annoying if you don't want to handle all the warnings?

Oh there is a huge one:  many people _absolutely hate_ checked exceptions.

This was a conscious decision with .NET/C# in the early days, to prefer unchecked exceptions with detailed diagnostic info so that if an app fails, it fails fast and is quick to fix because you know what went wrong.

Another disadvantage is that a similar issue can happen as with Java: people will just write a bunch of "catch 'em all!" handlers that don't actually do anything meaningful and are clearly just trying to satisfy the compiler. In these situations, people will sometimes also not catch the specific exceptions and then lose information in the process. Unlike with union types, there isn't a strongly-typed, domain-based way to validate you're handling all your cases with this kind of mechanism.

**Comment by BentTranberg** [comment]
Can't this be accomplished with a tool instead of modifying the language in some way?

**Comment by piaste** [comment]
> You're gonna catch ArgumentExceptions and ArgumentNullExceptions and NullReferenceExceptions? ¯\_(ツ)_/¯

It's worse than that, at least those are spelled out in the source code and can be theoretically detected with consistence. Assuming this warning were high-level and opt-in, I might imagine a project-level property to define a list of exceptions to be ignored.

`OutOfMemoryException`, `StackOverflowException`, `TypeLoadException`... you'd need a special blessed category for 'exceptions that are raised by the runtime and have nothing to do with the code itself because they can appear literally anywhere' so you can ignore them.

And if you're coding on .NET Framework <= 4.8, you also have stuff like `ThreadAbortException`, which does not appear in the code path where it is raised, but may be indirectly raised via the `Thread` object 'containing' the running code.

```
    // Should the compiler warn on Uncaught Exception? If so, on which line? 
    let f1 = fun () -> Thread.Sleep(1000)
    let f2 = fun () -> Thread.Sleep(2000)

    let x = Thread(ThreadStart(if Random.Next(2) = 0 then f1 else f2))

    let exec1 = x.Start()

    let exec2 = x.Start(); x.Abort()
```

**Comment by BentTranberg** [comment]
> ... you'd need a special blessed category for 'exceptions that are raised by the runtime and have nothing to do with the code itself because they can appear literally anywhere' so you can ignore them

I believe that's exactly what they do in Java. My encounter with Java was very brief, and a really long time ago, so I'm not sure.

Farther up,
> ... as with Java: people will just write a bunch of "catch 'em all!" handlers ...
Tell me about it ... but it happens in .NET already. Whenever I take over some crappy old code, removing a gazillion empty catch-em-all is usually one major item on the clean-up list. Typically present in every ¤!#&?@ method.
But I'm not so sure whether decent programmers would turn to this voodoo medicine to make the compiler happy. And F# programmers are pretty decent folks.

**Comment by vip-ehowlett** [comment]
I think that since exceptions are a language-level construct, the checks for them should also be a language-level construct. 

I imagine something similar to what @piaste said, it's probably best to distinguish between recoverable exceptions (more along the line of bad input) as opposed to runtime-thrown exceptions and warn on the recoverable ones. It would also be something that's opt-in. I'm also not suggesting to not let it compile, just add some type of feature either at or before compilation to warn you whether there's a possibility of an exception not being caught.  

It might also be good to warn when a catch expression catches multiple errors implicitly.
