### ISSUE TITLE
Optional else for early return

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#1112]
# Optional else for early return

I propose we extend the behavior we have with unit to other types when we use if

Today we can omit the `else` keyword when our functions return unit
```fsharp
let doSomething foo = 
    if foo > 10
    then printfn "Is greater than 10"
    
    printfn $"{foo}"
```
But, we don't have the same behavior when using other types, we can't omit the else on this snippet:
```fsharp
let doSomething foo = 
    if foo > 10
    then 10
    else foo / 2
```
I propose to have similar behavior, when the function returns a value in the scope the `else` became optional, so this could be valid:

```fsharp
let doSomething foo = 
    if foo > 10 then 10
    foo / 2
```

## Pros and Cons 

The advantages of making this adjustment to F#:
- The expected behavior would be the same for unit and other types.
- Can turn some code simpler to read/write
It- Easier for beginners

The disadvantages of making this adjustment to F#:
- I don't know if it could be a breaking change

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by cartermp** [comment]
In general I wouldn't want this. It's a very small syntactical optimization but it comes at the cost of a lack of uniformity in the non-unit-returning shape of an `if` expression.

**Comment by jl0pd** [comment]
I think this proposal comes from need to reduce nesting, but current compiler handles it just fine:
```fsharp
let flat foo =
    if foo > 10
    then 10 // early return
    else
    if foo > 5
    then 5 // early return
    else
    0

let nested foo =
    if foo > 10 then
        10
    else
        if foo > 5 then
            5
        else
            0
```

Both `flat` and `nested` do same thing, but first have less indentations.

**Comment by auduchinok** [comment]
We tend to use this style in some places where many early returns are required:

```fsharp
let nested foo =
    if foo > 10 then
        10 else

    if foo > 5 then
        5 else

    0
```

It's compatible with F# syntax and doesn't add too many indents.

**Comment by the-not-mad-psychologist** [comment]
To me, this proposal suggests the imperative "return early" pattern. If others so interpret it, it might confuse them since F# does not employ multiple `return` clauses.

The `unit` `else`-less `if`-statement returns a default `unit` value implicitly. Thus, using a different a different type, it would be expected also to return a default value of that type. This is probably a bad idea since different situations require different defaults. (We could, of course, explicitly and situationally define a default value, but then we've just reinvented `else`.)

Alternatively, the non-`unit` `else`-less `if`-statement could return `unit` in the default case, to be replaced by the later given value--but this would just be multiple `return` expressions using a different syntax. (Also, the expression would not return the same type in all cases.)

Technically, besides returning from both branches (implicit default values) and returning from the `then` branch and ignoring the result of the `else` clause (multiple `return`s), there are also the options of ignoring the `then` branch and returning from the `else` branch (guard statements) and ignoring the results of both branches (no-op, or `unit` `if`-`else`), but I don't see how they would relate to the current question.

**Comment by isaacabraham** [comment]
> In general I wouldn't want this. It's a very small syntactical optimization but it comes at the cost of a lack of uniformity in the non-unit-returning shape of an if expression.

Basically this x100. The simplicity from the current model is worth its weight in gold - I really wouldn't like to make things more complicated with this.

**Comment by DavidRaab** [comment]
Is there a point to not use `elif`?

```fsharp
let nested foo =
    if foo > 10 then
        10
    elif foo > 5 then
        5
    else
        // the main code goes here
        0
```

or

```fsharp
let nested foo =
    if   foo > 10 then 10
    elif foo > 5  then 5
    else
        // the main code goes here
        0
```

**Comment by DavidRaab** [comment]
I don't like it because:

It is not easier for beginners. Not even for beginners coming from other languages that don't understand F#. Sure you can write this in other languages. But in other languages `if` is a statement not an expression. And real beginners learning programming are completely unaffacted. Even worse. In general its harder to understand **special rules** you introduce into languages.

Even i cannot fully describe it in words when the compiler/language should use `foo / 2` in your example.

```fsharp
let doSomething foo = 
    if foo > 10 then 10
    foo / 2
```

Consider that `if` generates a value, but is not bind to a variable. What you have here is more like:

```fsharp
let doSomething foo = 
    let a = if foo > 10 then 10 else ???
    let b = foo / 2
    ???
```

My question:

1. Which value does `a` have in the else case?
2. To get your result you somehow must choose `b` if `a` has no value.

You by the way could achieve this with:

```
let doSomething foo =
    let a = if foo > 10 then Some 10 else None
    let b = foo / 2

    defaultArg a b
```

But this is not something I wish the language somehow does under the hood. In that case I think explicit is better than implicit.

**Comment by dsyme** [comment]
Closing this out given the various reactions above
