### ISSUE TITLE
Allow Discriminated Union types to take incremental construction parameters

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#115]
Allow this:
```fsharp
type Physical(data: ModuleData) =
    | OneToOne of Line : ModuleList
    | OneOnOne of Line1 : ModuleList * Line2 : ModuleList
    | OneByOne of Line1 : ModuleList * Line2 : ModuleList
    | Vertical of Line1 : ModuleList * Line2 : ModuleList * Line3 : ModuleList * Line4 : ModuleList

    // Expose the Data field as a property:
    member _.Data = data

// Arguments provided as prefix, e.g.
PhysicalData.OneToOne(data, line)

```

Details would include 

* what about matching?
* Can `let` be used
* If so can the `let` distinguish on case?

-------------

Original: 

**Submitted by Андрей Чебукин on 6/3/2016 12:00:00 AM**  
**27 votes on UserVoice prior to migration**  

If an each case constructor of Discriminated Union has a parameter with the same name and the same type than allow to implement a property on Discriminated Union base type to access to this parameter value.
Now I have to write a match on every case

``` fsharp
type Physical =
| OneToOne of Data : ModuleData * Line : ModuleList
| OneOnOne of Data : ModuleData * Line1 : ModuleList * Line2 : ModuleList
| OneByOne of Data : ModuleData * Line1 : ModuleList * Line2 : ModuleList
| Vertical of Data : ModuleData * Line1 : ModuleList * Line2 : ModuleList
* Line3 : ModuleList * Line4 : ModuleList
member this.Data : ModuleData = match this with
| OneToOne(data, _) -> data
| OneOnOne(data, _, _) -> data
| OneByOne(data, _, _) -> data
| Vertical(data, _, _, _, _) -> data
```

Implement this same parameter as a field on base class and allow me to write

```
member this.Data : ModuleData = base.Data
```

Or automatic property implementation would also be a perfect option

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/14595360)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-14595360-provide-property-on-base-discriminated-union-type.md#comments)

**Comment by Tarmil** [comment]
I'd like to bump this proposal because I think it would be useful, and add a few comments:

* This would incidentally add automatic getters for all the (named) fields of single-case unions, which is convenient:

    ```fsharp
    type UserId = UserId of Id: string

    let show (u: UserId) = printfn "%i" u.Id
    ```

* This would combine nicely with #688, as the generated property would be a an efficient field access, no need for matching in its implementation.

* There is kind of prior art on this in Scala, where unions are defined as base and derived types, and the base type can define fields that must exist in all cases:

    ```scala
    sealed trait Physical { def data : ModuleData }
    case class OneToOne (data : ModuleData, line : ModuleList) extends Physical
    case class OneOnOne (data : ModuleData, line1 : ModuleList, line2 : ModuleList) extends Physical
    case class OneByOne (data : ModuleData, line1 : ModuleList, line2 : ModuleList) extends Physical
    case class Vertical (data : ModuleData, line1 : ModuleList, line2 : ModuleList, line3 : ModuleList, line4 : ModuleList) extends Physical
    ```

**Comment by Tarmil** [comment]
Here's an interesting question: if a union is defined with `private` cases, should this property still be generated? I think there are arguments both for yes and no. Argument for no: if the cases are private, so should be their arguments' names. Argument for yes: this property is more an abstraction over the cases than a leak of their implementation.

I think a compromise would be to generate it as a private property. This way it's private by default but can still be made public easily if you want to:

```fsharp
type Entry =
    private
    | IntEntry of key: string * value: int
    | StringEntry of key: string * value: string

    // automatically generated:
    // private member key: string = ...

    // if I want it public I can do this:
    member this.Key = this.key
```

**Comment by yatli** [comment]
how about:

```F#
type Physical(Data: ModuleData) =
| OneToOne of Line : ModuleList
| OneOnOne of Line1 : ModuleList * Line2 : ModuleList
| OneByOne of Line1 : ModuleList * Line2 : ModuleList
| Vertical of Line1 : ModuleList * Line2 : ModuleList * Line3 : ModuleList * Line4 : ModuleList
```

**Comment by Tarmil** [comment]
@yatli I'm a bit ambivalent about this. On one hand, I like having this as an explicit feature rather than implicit. Plus it sidesteps the private issue completely, which is nice. But on the other hand, this is yet another syntax for declaring a type, and we have a lot of those already.

Either way I'm not a big fan of the constructor syntax for this either. Maybe this instead:

```fsharp
type Physical of Data: ModuleData =
| OneToOne of Line : ModuleList
| OneOnOne of Line1 : ModuleList * Line2 : ModuleList
| OneByOne of Line1 : ModuleList * Line2 : ModuleList
| Vertical of Line1 : ModuleList * Line2 : ModuleList * Line3 : ModuleList * Line4 : ModuleList
```

**Comment by smoothdeveloper** [comment]
@Tarmil I like the idea of optionally exposing properties for private cases, although I'm wondering about the casing, assuming the field is named with a initial capital, what would happen to your sample?

The potential member hiding and unclear OO semantics is bothering me a bit.

I like the suggestion because I end up writing such properties/match, but maybe it should be enabled only via an attribute? 

Maybe it is a shorthand syntax that we want to extract a field rather than generating properties.

I'd also like to have option to generate... optional fields, it would return none if the field is not defined (or if it is an option type already).



pros of using attribute:
* would enable to generate warnings (for example when there are mismatched types for a given field name
* does not generate IL bloat, keep API surface low by default

**Comment by Tarmil** [comment]
Yes, using an attribute is a possibility. Although if we want to specify which field(s) must be exposed, we would have to pass their name as strings to the attribute, which feels odd to me.

Another possibility would be a dedicated syntax for it, maybe a body-less `member` for example:

```fsharp
type Physical =
    | OneToOne of Data : ModuleData * Line : ModuleList
    | OneOnOne of Data : ModuleData * Line1 : ModuleList * Line2 : ModuleList
    | OneByOne of Data : ModuleData * Line1 : ModuleList * Line2 : ModuleList
    | Vertical of Data : ModuleData * Line1 : ModuleList * Line2 : ModuleList * Line3 : ModuleList * Line4 : ModuleList

    // Expose the Data field as a property:
    member Data

    // Optionally with a type annotation:
    member Data : ModuleData

    // This may also allow optional access as you suggested,
    // with a required type annotation:
    member Line1 : ModuleList option
```

**Comment by Swoorup** [comment]
What would happen, if the case was a record type?

**Comment by dsyme** [comment]
Just to note if anything we'd probably do this:
```fsharp
type Physical(data: ModuleData) =
    | OneToOne of Line : ModuleList
    | OneOnOne of Line1 : ModuleList * Line2 : ModuleList
    | OneByOne of Line1 : ModuleList * Line2 : ModuleList
    | Vertical of Line1 : ModuleList * Line2 : ModuleList * Line3 : ModuleList * Line4 : ModuleList

    // Expose the Data field as a property:
    member _.Data = data
```

**Comment by kerams** [comment]
What would case construction look like?

```fsharp
OneOnOne (data, moduleList1, moduList2)
OneOnOne (data, (moduleList1, moduList2))
OneOnOne data (moduleList1, moduList2) // can you partially apply here?

let physicalCtor = Physical data
physicalCtor.OneOnOne (moduleList1, moduleList2)
```

I'd honestly just prefer to define a wrapping record to hold ModuleData and the union...

**Comment by dsyme** [comment]
Closing this as my variation https://github.com/fsharp/fslang-suggestions/issues/115#issuecomment-1295030289 isn't really that great, and there aren't good answers to the questions @kerams asks
