### ISSUE TITLE
Syntax: named parameters and arguments borrow from record

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#1185]
I propose we add a new feature: A syntax named parameters that is borrow from record type def:

```F#

let distance { x:float; y:float } = 
    (x**2.0+y**2.0)**0.5
```
named arguments are same as record type literal:

```F#
let result =
    distance { x=2.0; y=3.0; }
```

Because named parameters don't explicitly define his record type, This arguments of `distance` is not any record you can reference. it's impossible for you to input any record type instance directly. even though their fields are same.

```F#
type Point = { x:float; y:float }

let p = { x=2.0; y=3.0; }

distance p // error

distance { p with y= 2.0} // error

distance { x=p.x; y=p.y } // ok!
```

The existing way of approaching this problem in F# is 

anon record:

```F#

let distance (p:{|x:float;y:float|} =
    let x = p.x
    let y = p.y
    (x**2.0+y**2.0)**0.5

let result =
    distance {| x=2.0; y=3.0; |}

let p =  {| x=2.0; y=3.0; |}
let d = distance p
```
or typed record:

```F#
type distanceParameters = { x: float; y: float }
let distance ({x = x; y = y }:distanceParameters) = 
    (x**2.0+y**2.0)**0.5
let result =
    distance ({ x=2.0; y=3.0; }:distanceParameters)
```

## Pros and Cons 

The advantages of making this adjustment to F# are 

  - integerated type def with funition def is more readable than Separated the record type definition and function definition.
  - The input data requires more refine information and does not conflict with the record type of same fields.
  - Record type will can be decoupled with their custom member methods. for example `Point` can use `distance` without defining `member p.distance()`. 

The disadvantages of making this adjustment to F# are ...

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by abelbraaksma** [comment]
What your suggesting is already possible and are called record patterns. If I take your example and change it slightly to make it legal, you get this:

```
module X =
    type Foo = { x: float; y: float }
    let distance {x = x; y = y } = (x**2.0+y**2.0)**0.5
    let result =
        distance { x=2.0; y=3.0; }
```

If I’m misunderstanding, then please clarify.

**Comment by xp44mm** [comment]
@abelbraaksma Thanks for the code.

The current code has a flaw that when two record type members are the same, you have to specify the type.

```F#
type Point = {x:int;y:int}
type Foo = { x: float; y: float }
let distance ({x = x; y = y }:Foo) = (x**2.0+y**2.0)**0.5
let result =
    distance ({ x=2.0; y=3.0; }:Foo)
```

**Comment by abelbraaksma** [comment]
Thanks for explaining. Since you're repurposing existing syntax, at least as far as I can tell, this would break existing code. I think with "fake" you mean: erasable. You're correct that when you have types with the same fieldnames, you will run into the problem that you need to help the compiler. But "fake" records is not going to remove that situation.

Unless, perhaps you mean that what you mean with a "fake" record is a construct that means "any record that fits this same signature". In that case, this also already exists, but unfortunately only for anonymous records: when they are equal, they will be compiled to the same type. But, you cannot write a lh-side let-binding pattern with anonymous records.

Personally, I don't really see the merit of this proposal if it only ever helps cases where types have the same fields, which probably happens very rarely. I.e., it is way more common to use a type alias in those cases:

```
type Point = { x: float; y: float }
type Vector = Point
```

**Comment by xp44mm** [comment]
The named parameter table just looks like a record, it is not a record. Just as the C parameter table is not a tuple. both named and indexed parameter table is used is their members, and they themselves will never be used.

**Comment by abelbraaksma** [comment]
> This arguments of distance is not any record you can reference. it's impossible for you to input any record type instance directly. even though their fields are same.

I appreciate you updating the original text. But I still struggle to see what we’re gaining here. Apart from the syntax you propose (which we cannot use, because it’s already legal syntax with a meaning), you create a function that you want to take all the properties of a record, but you’re forbidding that the caller can call it with a record. 

This sounds like a lot of burden on the call-site. It’s like saying: this function takes a class, but you cannot call it with that class, you *must* specify all properties of the class explicitly as an object expression.

It removes the possibility of writing readable code, where you can first assign and construct a record to a variable, and then pass that variable to the function. In fact, if I’m reading your proposal correctly, you seem to want to forbid functions with this syntax being called with any variable, or result of a calculation.

Such construct would make it impossible to use such function (if we can even call it that) to be used with classic, and extremely common `|>` and `>>` operators. They could not be “composed”, which also means they could not be used themselves as higher order functions. You could not use them in, say, `List.map`, or anything else higher order (which is just about everything in F#).

I admit I didn’t understand this when I first reviewed your proposal, and maybe I’m still misunderstanding it, because it is so radically different from anything in FP. So forgive me for asking again, but how can this improve existing code? How does it help the programmer if they’re forced to write out the fields of the ‘fake’ record? Essentially you seem to say: here’s a new type of function that you cannot use as a function….

**Comment by xp44mm** [comment]
you define a tuple parameters function:
```F#
let dist (x,y) = x + y
let x = dist(2,3)
```
can you call `(2,3)` in `dist(2,3)`? and can you call `(x,y)` in `dist(x,y)`? 

Name parameters base on the same principle.

```F#
let dist {x;y} = x + y
let x = dist {x=2;y=3}
```
You can no longer use `{x;y} ` in `dist {x;y} ` and `{x=2;y=3} ` in `dist {x=2;y=3} `.

You can think of the following code as the syntax sugar of the above code. What benefits records are to tuples, and what benefits a named parametersis to index parameters.

**Comment by abelbraaksma** [comment]
> can you call (2,3) in dist(2,3)? and can you call (x,y) in dist(x,y)?

My point in my previous comment was about you saying in the original proposal that several syntaxes would be prohibited, i.e., using a variable:

> `distance p // error`
> `distance { p with y= 2.0} // error`
> `distance { x=p.x; y=p.y } // ok!`

But tuples don't have that. You can assign them to variables whichever way you want:

```
// on the definition:
let dist a = fst a - snd a   // this makes 'a' a tuple
let x = dist(2, 3)

// this answers your question on "can you call the tuple": yes you can, x is the tuple
let dist ((a, b) as x) = printfn "%A" x; a - b

// on the calling site:
let x = (2, 3) |> dist
let foo = (2, 3)
let x = dist foo
let f = dist >> string
```

All of these very common programming techniques (i.e.: use of variables as arguments, piping, composition), seem to be forbidden by your proposal.

> You can think of the second code as the syntax sugar of the first code. What benefits records are to tuples, and what benefits a named parametersis to index parameters.

I don't understand this at all. Index parameters? 

Anyway, you can get _very close_ to your syntax. It will forbid the use of the direct record, so you will need to specify the individual arguments. But, it is still a function (unlike what I understand from your proposal), so you are also allowed to use _without_ named parameters:

```
type MyClass =
    static member dist(a, b) = a - b

// open the class so they look like functions with named parameters
open type MyClass
type Point = {x: float; y: float}

// usages:
let x = dist (a = 2.0, b = 3.0) 
let p = {x = 12; y = 13 }
let y = dist (a = p.x, b = p.y) 

let alsoAllowed1 = let x = (2.0, 3.0) in dist x
let alsoAllowed2 = (2.0, 3.0) |> dist
```

Now I can't think of a coding pattern where this is useful, but that doesn't mean it isn't. I have no problem with syntax sugar, but your proposal _uses existing syntax to mean something else_, and disallows highly orthogonal constructs (like passing a parameter as a variable to a function), which, imho, very far from anything related to F#'s functional concepts.

**Comment by xp44mm** [comment]
The code `dist ((a, b) as x)` is actually a Curried function with a tuple type `a:'a*'a` parameter. It corresponds to `distance (p:{|x:float;y:float|}`. 

Index parameters is to pass arguments by position without regard to parameter name. for example `Regex("\d",opt)` by position.
```F#
    static member dist(a, b) = a - b
```
`dist(a,b)` is indexed parameters.

```F#
let x = dist (a = 2.0, b = 3.0) 
```
with
```F#
let x = dist {a = 2.0; b = 3.0;} 
```
The former arguments must be in order. The latter parameters may be sorted out of order.
Commas are strict, while semicolons are optional.

**Comment by abelbraaksma** [comment]
> The code dist ((a, b) as x) is actually a Curried function with a tuple type a:'a*'a parameter.

No, not at all. It's a _pattern_ where you assign the result of the captured pattern to a variable `x` and the result of parts of the pattern to `a` and `b`. 

Instead, a curried function is a function where you drop a function parameter. In the code above `x |> dist`, the ident `dist` is presented without the parameter, this is currying. Also, if you have `let f x y = x + y`, then `f 12` is a curried version of `f` with `12` captured in the closure of the curried version.

>  It corresponds to distance `(p:{|x:float;y:float|}.`

No, it does not. Here you have a parameter `p` that has a type-specification of an anonymous record type `{|x:float;y:float|}`. That is not the same as a pattern that's captured in a parameter. A record-example of a pattern with a record would be `let f ({x = a} as r) = r.y * a`. In this example, `a` captures the `x`-field of the `Point` record, while `r` captures the whole record through the `as`-assignment syntax.

> Index parameters is to pass arguments by position without regard to parameter name.

I see now what you mean by "index parameter". The terms in F# are tupled parameters (as with the BCL classes) and curried arguments (for any function). Tupled parameters are usually erased and cannot be curried. F# _does_ have a notion of ["indexed properties"](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/indexed-properties), same like in C#, and what's called _indexed lookup expression_, i.e. in `x[24]`.

Another term that you see sometimes is _positional arguments_ for what you call _indexed parameters_.

> for example Regex("\d",opt) pass his arguments by position. the def is indexed parameters.

No, the "def" is:

* It's an implicit lookup expression (probably, but not necessarily leading to a constructor call)
* The `(...)` here is called a "high precedence application"
* The part inside the parentheses is an `expr`, and can be _any_ expression, but in this case is what's called a _tuple expression_.

You can read about those definitions here: https://fsharp.org/specs/language-spec/4.1/FSharpSpec-4.1-latest.pdf.

You are correct in saying that the _position_ must be correct, as a _tuple_ is a [_grouping of unnamed values_](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/tuples).

> `dist(a,b)` is indexed parameters.

No, see above. More precisely, it matches this production, in which you can see that it is an _argument pattern_:

![image](https://user-images.githubusercontent.com/16015770/189552167-cf9fbc51-600c-4539-a838-d444e3b17bec.png)

> The former arguments must be in order. The latter parameters may be sorted out of order.

No, they don't have to be. The same code in inverted order works just fine:

```
let x = dist (b = 3.0, a = 2.0) 
```

> Commas are strict, while semicolons are optional.

Not quite, and: it depends. Only sometimes are semicolons optional. If I type `let z = let y = 12 in printfn "%A" y; y` it is not optional, removing it would invalidate the code. Same is true for `[a;b;c;d]` unless you put them each on a newline. Commas are sometimes strict (as in: ordered): for unnamed parameters, or when defining a tuple or generic type definition. In most cases, you cannot remove the commas.

> When the argument is a lambda expression, the former argument needs to be enclosed in parentheses.

There are no lambda expressions in this discussion so far, so I'm not sure what this refers to. If you have `f a b` as calling the function `f`, if you make `b` a lambda, you can write _that_ expression in parentheses, but you don't have to: `f a (fun _ -> x)` or `f a <| fun _ -> x` are both fine. But the _former_ argument does not have to be in parentheses, as you can see, `b` is not in parentheses.


---------------

But, while it is interesting to go into a discussion on what certain constructs mean or how they are called, I can highly recommend trying these things out for yourself. You will notice that the examples that I showed you solve your use-case.

If you are not convinced, go over the PDF for F# 4.1 and check the syntax and parsing grammar. You will find that there's nothing in there that allows anything remotely to your proposal (i.e., _disallowing_ using variables in a function call). You would then also see that an _argument pattern_ is a very powerful mechanism and that you shouldn't remove that power for one edge case.

Your original suggestion was about named parameters in a function definition where these use the syntax of a record. Since that's not possible _at all_ (syntax already used for something else, but I keep repeating myself, check the PDF if you don't believe it), the next best thing is to use named parameters, which simply already exist. Please try it out.

The only difference between your and my syntax is `{` vs `(`.

**Comment by cartermp** [comment]
I think given that you can do these:

```fsharp
let distance (p:{|x:float;y:float|} = ...

let distance (x:float) (y:float) = ...

// or even this, provided type inference infers them to be floats
let distance x y = ...
```

I don't think we're going to introduce a sort of "inline record" that lets you define parameters as a group outside of anonymous records.

**Comment by smoothdeveloper** [comment]
There is something interesting to consider, if this could be used for optional parameters and resilience to parameters being shuffled.

It could make call sites to such function, that would add optional parameters or shuffle them, source code compatible.

That being said, with `open type` and defining static methods, covers a large area of those concerns IMO.
