### ISSUE TITLE
(Optional?) warning on recursive members and add `member rec ... and ...` / `type rec ... and ...`

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1221]
I propose we add new warnings to these code
```fs
type A() =
    let a = 1
    let rec b() = b() // "rec" required
    let rec c() = d() // "rec" and "and" required
    and d() = c()
    static let a = 1
    static let rec sb() = sb() // "rec" required
    static let rec sc() = sd() // "rec" and "and" required
    and sd() = sc()
    member t.A = a
    member t.B = t.B // warn here (self reference)
    member t.C = t.D // warn here (declaration later than usage)
    member t.D = t.C
    static member SB = A.SB // warn here (self reference)
    static member SC = A.SD // warn here (declaration later than usage)
    static member SD = A.SC
```
and introduce this new syntax
```fs
type A() =
    let a = 1
    let rec b() = b() // "rec" required
    let rec c() = d() // "rec" and "and" required
    and d() = c()
    static let a = 1
    static let rec sb() = sb() // "rec" required
    static let rec sc() = sd() // "rec" and "and" required
    and sd() = sc()
    member t.A = a
    member rec t.B = t.B // warning eliminated!
    member rec t.C = t.D // warning eliminated!
    and t.D = t.C
    static member rec SB = A.SB // warning eliminated!
    static member rec SC = A.SD // warning eliminated!
    and SD = A.SC
```
and
```fs
type rec A() = // "rec" here to eliminate warnings
    let a = 1
    let rec b() = b() // "rec" required
    let rec c() = d() // "rec" and "and" required
    and d() = c()
    static let a = 1
    static let rec sb() = sb() // "rec" required
    static let rec sc() = sd() // "rec" and "and" required
    and sd() = sc()
    member t.A = a
    member t.B = t.B // no warning
    member t.C = t.D // no warning
    member t.D = t.C
    static member SB = A.SB // no warning
    static member SC = A.SD // no warning
    static member SD = A.SC
// "and" for mutually recursive types
```
`module rec` and `namespace rec` will automatically suppress member recursion warnings.

The existing way of approaching this problem in F# is to have no way of consistently enforcing linear declarations on members, aside from types, modules, and let declarations.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Consistency
2. Clarity
3. Code style enforcement improved

The disadvantages of making this adjustment to F# are the inconsistency of warning versus error, and the cost of deprecation of old styles in existing code, tutorials, etc.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S to M

Related suggestions:
- https://github.com/fsharp/fslang-suggestions/issues/811 which proposes `let public`. This makes larger inconsistency between field and property declarations.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design (new warnings are breaking for people with all warnings enabled but having warnings as errors turned on)
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by BentTranberg** [comment]
So if I understand correctly - let `rec` and `and` work the same way in the member section of a type as it does in the pre-member section in a class - or in a module. The default would be that a member can't see another member declared after it, if I understand correctly.

I very much love how F# imposes a particular ordering of functions, but the member section of a type should be regarded, source-wise also, primarily as a list of declarations. To impose an order in these declarations that depend on implementation details that can change at any time, and really doesn't have anything to do with the interface part, seems to me not to be helpful at all. I can't see the advantages that are listed. In fact I believe it will be counterproductive, and complicate things for no good reason. It would hamper CI because trivial implementation changes might easily cause major changes in the source of the public interface of the type. I also suspect that although this could be an opt-in feature, it is such a significant divergence from the non-opt-in version that we could think of it as an alternative F#. Not sure we want that mix.

In the member section of a type we frequently want to control the member order based on some criteria. It could be the same order as an interface, or alphabetical if there are many members, or grouped by overrides, or functionality, or... there are probably plenty of other good examples. We can't always do that with functions in a module, but we can in member sections. Also, the fact that members can all see each other is actually very often a very useful feature when writing the implementation, and even more so in classes than in other types because of the more mutable nature of classes, and what follows from that when you code - or at least when I code. I have the best of both worlds.

I think the gains that there might be in this suggestion, can usually better be accomplished with existing means or other means, such as using the pre-member section of a class or other places to separate the implementation details better from the interface, or by using a lint-like tool for finding code issues one might be interested in.

**Comment by BentTranberg** [comment]
I am far from an F# or functional expert, so consider that post as the allegorical 2 cents worth.

**Comment by dsyme** [comment]
I get the intent and the argument from consistency. However this has already been decided, partly by the languages F# inherits from.

Why did we/they choose the defaults? Because

1. types and objects are more likely to be recursive in design and implementation
2. top level let (and thus modules) are used for scripting and are thus generally non recursive 
3. Expression level are used for function bodies and are generally  non recursive

**Comment by Happypig375** [comment]
@dsyme Since classes can be thought of as modules with shared parameters of their functions, some uses of modules can be converted to classes as simplification. However, this comes with the side effect of changing the allowance of recursiveness, which becomes non-enforced. How can this dichotomy be solved?

**Comment by dsyme** [comment]
> How can this dichotomy be solved?

The only solution offered solution is to use an interior linear sequence of `let` in the class, and then "publish" these separately 

Classes/members also set other important defaults differently, especially `member x.P = expr` being re-evaluated on every invocation of the property.  So they do drop you into a different mode of programming where the rules are different.

**Comment by charlesroddie** [comment]
I was in favour of removing `_.` in member declarations since it incentivizes using `member X` (which is non-recursive) over `member t.X` (which allows recursive access to properties of `t`).

This suggestion but has the problem that in `class A with member t.X`, `t` is of type `A`, and something of type `A` must have the properties of type `A`.

I had a `let public` suggestion which I believe would have a similar effect without the above problem, although I may have scuppered it by mixing up fields and properties in the suggestion.

Will add links when at desktop.
