### ISSUE TITLE
Automatically propagate type parameter constraints

### ISSUE THREAD

**Issue by tymokvo** [fsharp/fslang-suggestions#1241]
I propose we...propagate type constraints on generics up through a type hierarchy.

Originally asked on [slack](https://fsharp.slack.com/archives/C1R50TKEU/p1674831399741279).

### Example

This block:

```fsharp
type Constrained<'a when 'a :> System.IComparable> = { value: 'a }

type ConstrainedHaver<'a> =
    {
        constrained: Constrained<'a>
    }
```
will cause the compiler error FS0001:
```
A type parameter is missing a constraint 'when 'a :> System.IComparable'
```

In order for this to compile, one must manually propagate the constraints to the type that is further up the hierarchy than the type which declares the constraints:

```fsharp
type Constrained<'a when 'a :> System.IComparable> = { value: 'a }

type ConstrainedHaver<'a when 'a :> System.IComparable> =
    {
        constrained: Constrained<'a>
    }
```
In this instance, this is not so bad. But, when making compound types that rely on many interfaces, this is laborious and repetitive. 

Much of dotnet relies on interfaces and, as a library author, it is typically prudent to create interfaces so that library consumers are able to implement them for their concrete types rather than rely on concrete type from a library that may not fit their program design.

## Pros and Cons 

The advantages of making this adjustment to F# are that it would reduce the amount of authored code that is required to create hierarchies of generic types with constraints.

The disadvantages of making this adjustment to F# are that it increases the complexity of the compiler to implement a feature that can be handled by a code author copying and pasting. There may also be issues for SRTP of which I'm not aware.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 
**M** 
(I am probably not the best person to estimate this, so assume this has a variance of 2 sizes)

Related suggestions: (not aware of any)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Tarmil** [comment]
This is an interesting idea, it would definitely save some redundant typing.

I would be a bit wary of implicitly adding constraints to a definition without realizing it, though. And I like the fact that when you see `<'a>` on a definition, you know that there are no constraints. Maybe we can strike a balance by making it explicit that there are constraints being propagated, while still saving the effort of specifying them, with some kind of constraint wildcard:

```fsharp
type ConstrainedHaver<'a when _> =
    {
        constrained: Constrained<'a>
    }
```

**Comment by Lanayx** [comment]
What a coincidence, just today I've come to the same conclusion when trying to implement dependency injection using generics. With the automatic constraint propagation it becomes usable for production solutions. Consider this code

```fsharp
type IDb<'T> =
    static abstract member GetUserName : unit -> string
    static abstract member GetUserNames : unit -> string[]

type ILogger<'T> =
    static abstract member Log : string -> unit

type RealEnv =
    interface ILogger<RealEnv> with
      static member Log text = printf "%s" text
    interface IDb<RealEnv> with
      static member GetUserName() = "DbUser"
      static member GetUserNames() = [|"DbUser"|]
  
type TestEnv =
    interface ILogger<TestEnv> with
      static member Log _ = ()
    interface IDb<TestEnv> with
      static member GetUserName() = "TestUser"
      static member GetUserNames() = [|"TestUser"|]  

//--------------  


module BL =
  let getUserNameInner<'T when IDb<'T> and ILogger<'T>>() =
      let userName = 'T.GetUserName()
      let result = "Mr. " + userName
      'T.Log result
      result
      
  // Here I face the constraint missing error    
  let getUserName<'T>() =
       getUserNameInner<'T>() 
      
  let getUserNames<'T when IDb<'T>>() =
      'T.GetUserNames()


let realProgram url =
  match url with
  | "getUserName" -> BL.getUserName<RealEnv>() |> box
  | "getUserNames" -> BL.getUserNames<RealEnv>() |> box


realProgram "getUserName"
```

There is also inconsistency with generics for function parameters - constraint propagation works properly there, so inability of constraint passing on type level feels like a bug for me.

**Comment by Lanayx** [comment]
> This is an interesting idea, it would definitely save some redundant typing.
> 
> I would be a bit wary of implicitly adding constraints to a definition without realizing it, though. And I like the fact that when you see `<'a>` on a definition, you know that there are no constraints. Maybe we can strike a balance by making it explicit that there are constraints being propagated, while still saving the effort of specifying them, with some kind of constraint wildcard:
> 
> ```fsharp
> type ConstrainedHaver<'a when _> =
>     {
>         constrained: Constrained<'a>
>     }
> ```

@Tarmil I think your approach only covers only one case - when you don't want to specify ALL constraints, while I'd rather see automatic constraint merge just like this works for parameters:
```fsharp
type ISmth1 =
    abstract Smth1: unit -> unit
type ISmth2 =
    abstract Smth2: unit -> unit

let myFunc1 (e: #ISmth1) =
      e.Smth1()
// here e infers both constraints
let myFunc2 (e: #ISmth2) =
     myFunc1(e)
     e.Smth2()
// here e infers both constraints
let myFunc3 (e: 'T) =
     myFunc1(e)
     myFunc2(e) 
```

**Comment by Tarmil** [comment]
Right, some constraints need to be explicit for the body to be compilable. I think we can still make my solution work:

```fsharp
let myFunc5<'T when 'T :> ISmth2 and _> (e: 'T) =
     myFunc4<'T>()
     e.Smth2()
```

**Comment by Lanayx** [comment]
Ok, thank you for the explanation, it makes sense! However, as everyday user of constraints auto-merge on parameter level - I find it very convenient to be able to skip additional "when _" and "and _" statements, without any downsides (since code editor does a good job of showing them in a hint).

**Comment by tymokvo** [comment]
> I would be a bit wary of implicitly adding constraints to a definition without realizing it, though.

@Tarmil I'm not sure I understand how the case of "not realizing" the constraints would arise. Could you expand on this?

What @Lanayx is describing makes intuitive sense to me:

> while I'd rather see automatic constraint merge just like this works for parameters:

When the compiler, as it currently works, propagates type constraints on value parameters, I think I typically _do_ want to be informed that the type has been restricted by the usage of the parameter. If another, unconstrained, degree of freedom is needed, one can add a parameter that is used differently.

For example, it seems surprising that type parameters do not work in the same way as value parameters:

Entering this to FSI, the parameter type constraints are propagating up from usage:
```fsharp
let f a b = a = b
val f: a: 'a -> b: 'a -> bool when 'a: equality
```
(The type of `a` and `b` have been constrained to `requires equality` by usage)

But, for the example in the original issue, FS00001 results, even though the compiler clearly understands _what_ the constraints are since they are present in the error message.

What about differentiating between true type variables like `'a` and cases where you expect constraints to propagate up from usage? A bit how anonymous type variables are permitted in functions, e.g.:

```fsharp

// Fully unconstrained
type Identifiable<'a> = {id: System.Guid; value: 'a}

// Simple constraint
type Constrained<'a when 'a :> System.IComparable> = { value: 'a }

// Using anonymous type parameters to propagate the sets of constraints
// Including the empty set of constraints on `__`
type ConstrainedHaver<_, __> =
    {
        constrained: Constrained<_>
        identified: Identified<__>
    }
```

**Comment by konst-sh** [comment]
Supporting this a lot, constraint inference would be very natural and expected behavior. I guess compiler already makes this check, since we having error of missing constraint instead of constraint application. And anyway would be helpful to know the source of constraint if it is inferred in some point if its possible.

**Comment by charlesroddie** [comment]
I don't like this at all. `type T<'a> =` is the current way to express that I want to define a `T` taking any generic argument `'a`. If this suggestion is implemented I won't be able to express that. If it turns out that the definition cannot be satisfied for some `'a` and that constraints are needed, I want to get an error or at least a warning at that point and certainly not have a hidden constraint added automatically.

**Comment by Lanayx** [comment]
@charlesroddie Who do you want "to express" it to? I see two options: first - when you use it in a regular code in work project and you express it to colleagues, second - whey you expose it as a library to other people.
In first case (which is far more common) I don't really care about "expression", I care about getting thing done in the easiest way, here auto-propagation serves really well, since it's less code to write and support. If code has more constraints than I expected I don't care, whatever it takes to make the product work. If something breaks - I'll see it at compile time and fix it.
In second case - (when you publish nuget package) you indeed can take care and verify that all your generics don't have constraints to make sure your library is backward compatible and won't break user code in update by suddenly adding constraint to generics. But I think that this is not too big deal for several reasons: user doesn't check your sources anyway only the outcome, user will see the error in compile time, user can revert library update and report an issue. As a library author you could break your api at any time, so user should be prepared for it anyway.

**Comment by konst-sh** [comment]
@charlesroddie I guess the "expression" of inferred constraints can be safely relayed to code editor side - the special appearance of type parameter, the hint with inferred constraints, the tooltip to auto-generate and explicitly embed the constraints code.
In the end type inference is one of the things why we like F#, not annotating every parameter with type constraints is common practice and this will be a step towards its unification and simplification.

**Comment by jpeg729** [comment]
Would an analyser that proposes a code fix be a decent compromise?

**Comment by cartermp** [comment]
@jpeg729 probably not; we'd first need a way for the compiler to emit an INFO diagnostic that a code fixer could listen on. That precedent (for the purposes of code refactorings) doesn't really exist today.

**Comment by tymokvo** [comment]
@charlesroddie I'm not sure I understand this:

> `type T<'a> =` is the current way to express that I want to define a `T` taking any generic argument `'a`. If this suggestion is implemented I won't be able to express that.

Could you give an example of what you mean?

From my understanding, this:

```fsharp
type T<'a> = { value: 'a }
```

would not be impacted by this proposal.

And this:

```fsharp
type C<'a when 'a :> System.IComparable> = { value: 'a }

type T<'a> =
    {
        value: C<'a>
    }
```

is already not possible to compile, due to the error mentioned in the original proposal. Additionally, there _is_ an error emitted by FSAC because of this.

**Comment by charlesroddie** [comment]
@Lanayx I mean by express that I write something with a meaning and that someone reading it can understand the meaning. The problem with your argument is that it assumes that no one ever reads code.

@konst-sh yes sometimes people read code within IDEs and that does help a lot, but it doesn't help when reviewing code in current source control systems, and we don't yet have IDE support for viewing type signatures without hovering to my knowledge, so it doesn't help skim through code. A certain style of F# specifies signatures fully via fsi files, a certain style of F# doesn't specify signatures at all, and a certain style of F# specifies signatures fully in code files and only relies on rightwards/downwards inference. I strongly support the last style over the second (you can read code from top to bottom, it focuses on types first and implementation second, it saves human readers the effort of inference, it detects type errors much more efficiently). At the very least, this style should be allowed!

@tymokvo The problem is that by the latter code the writer might have intended it to work for all `'a`, and will realise that a mistake has been made when the code fails to compile, while if this suggestion is made the code will compile and not be what was intended.

That said, @Tarmil 's proposed syntax wouldn't conflict with existing syntax and so wouldn't create these problems.

**Comment by Lanayx** [comment]
@charlesroddie What I was trying to say is that to read and understand you don't have to have all types information right in front of you. Automatic types resolution is the cornerstone fsharp feature, you can always use csharp and write down all the types that you need. Consider the code
```fsharp
let deserialize<'T> str = JsonSerializer.Deserialize<'T> str
```
I'm pretty you can clearly read and understand this code, but actually 'T might need to have parameterless constructor. This extra knowledge has opposite effect - it distracts you from your function business logic.
That's is the point - you don't have to face all the possible constraints that underlying function has if they are not directly used by your function, it's' the visual garbage for reading.

**Comment by konst-sh** [comment]
@charlesroddie the style with optional hand-written type constraints should stay for sure, its discussible should the compiler be allowed to append user specified type constraints with inferred ones or to treat the set of constraints as sealed. In the last case you are insured that you keeping top to to bottom control over type inference when needed. Its just for the matter of parity between this two layers.

**Comment by dsyme** [comment]
I understand the request, but there are just too many technical problems involved in allowing inference of constraints within type definitions.   There is just case after case where you need to know the constraints "before" the use of the construct, and it becomes totally intractable to infer them from the use sites.

I won't write out the cases, but trust me, it's technically out of reach.

**Comment by tymokvo** [comment]
That is unfortunate, but thank you for the response. I get that there are technical limitations that I'm not aware of. Would it be possible for one of the F# maintainers to explain the cases in a blog post or in office hours?

I find it confusing that the compiler is able to emit the message about what constraints are missing on type parameters at the time the enclosing type is authored and before it has any use sites, but that it's intractable to apply those to the new type parameters.

**Comment by gusty** [comment]
> I find it confusing that the compiler is able to emit the message about what constraints are missing on type parameters at the time the enclosing type is authored and before it has any use sites, but that it's intractable to apply those to the new type parameters.

Moreover, for operators this feature requested just works !

So I would also be interested in knowing what changes from the moment an operator become a named function.

**Comment by IS4Code** [comment]
I would also like to see this implemented. Maybe an attribute, in the form `[<InferredConstraints>]'T`? It doesn't have to work in every case, but maybe there are situations where it could be viable? For example if there is no interdependence of members using the constraints, or only for some constraints that are painful to repeat (explicit member constraints for example).

@vzarytovskii @dsyme Would a weaker version of this proposal work, or perhaps one that comes with some "precautions" to make it more viable (such as with the attribute or other decorational syntax). In a lot of times, the compiler indeed very helpfully points out exactly the constraint that is necessary, so why couldn't it (in the explicitly marked case) just abandon the compilation of the type and start anew with the constraint in mind?

I should also point out that there are two existing cases where this already happens without issues:
* Functions/methods with implicit generic parameters. All constraints are inferred perfectly, so it makes sense to me to be able to just state explicitly what the type parameters are, in what order, and leave the rest for the compiler since it otherwise does a great job figuring it out. I don't think giving *more* information to the compiler should make it *less* capable.
* Object expressions. There, the compiler is already building a type that receives the constraints automatically:
  ```fs
  let f x = {
    new obj() with
      member this.ToString() =
        if x = null then "null" else x.ToString()
  }
  ```
  You can observe the compiled code that the `not struct` constraint is inferred for both the type and the method. To me, this feels almost within reach, "just" make the generated type public and all would be great.

Are there any issues with extending such mechanisms to make this possible?

**Comment by T-Gro** [comment]
It might be difficult to create a specific counterexample, but correctness while maintaining a single-pass typechecking is a concern.

As values and members are being typechecked, existing type constraints of the parent type are already taken into account.
If a member triggers addition of new constraints, would it have to re-typecheck all of the proceeding ones again? (making it quadratic).

We do not support expressing `allows ref struct` in F# code now, but if we did - auto-inferring it as part of an member could make previous members invalid ; as an example.


I am happy to chat/brainstorm if anyone has an idea how to safely introduce this to constraint solving - maybe I am overseeing something here.

**Comment by IS4Code** [comment]
@T-Gro I don't think `allows ref struct` should be inferred at all, or at least not through this mechanism. Since it is an "anti-constraint", you are right that automatically adding it to the list to constraints might make previous code invalid, which is not something one wish to do. I think it could still be solved, but that is a discussion that (I think) can be made separately.

Without taking `allows ref struct` into account, I am not sure if this is actually an issue or not. Consider what already happens during typechecking for functions or members:
* Constraints are supposed to give the implementer more power (being able to do more with the type parameters) at the expense of the consumer (is restricted in terms of what he can pass as type argument).
* Thus, if a type parameter `T` is encountered in a context that constrains it (from another type/function/member or an operation, such as `= null`), such an operation should *always* succeed on its own, because it just means the type parameter must request *more* capabilities to be used in that context, hence new constraints are added that provide the necessary functionality.
* However, the constraints might end up non-satisfiable (such as containing both `struct` and `not struct`). This is not an error per se, it just means there are no types that could satisfy them, but even though you could technically view it as "a later operation making an earlier one invalid", it is the exact same thing as "a prior operation making the following one invalid", since the constraints are what ensures the consistency.
* This means that we must find an operation that is not exactly governed by constraints (although is affected by them) that can actually fail if you get *more* power than you have initially. Overload resolution immediately comes to my mind, but I could not come up with an example where this would actually *introduce* ambiguity:
  <details>
  <summary><i>My attempt</i></summary>

  ```fs
  type I1 = interface end
  type I2 = interface end
  
  type C =
    static member inline M(x : I1) = false
    static member inline M(x : I2) = true
  
  let f(x) = {
    new obj() with
      member this.Equals(other) = 
        let _ = x :> I1
        C.M(x) // already an error, regardless of the following member
        
      //member this.ToString() =
      //  let b = x :> I2
      //  C.M(b).ToString()
  }
  ```

  </details>

Do you think there could be other situations where constraints are not enough to ensure consistency and prevent single-pass typechecking? Due to object expressions being a thing, I am still not convinced that, if there is a potential issue there, it could not be observed already for object expressions.

-----

There is also a similar strategy for `allows ref struct`, all you need is to turn it into a real constraint:
1. Initially, start with `allows ref struct` already "enabled" ‒ just with the constraint list empty.
2. When you encounter an operation that contradicts `allows ref struct`, add a new virtual constraint, say, `*requires_heap`.
3. When you finish typechecking, just emit `allows ref struct` if and only if `*requires_heap` is *not* present.

This still leaves enough room for two options how to actually express `allows ref struct` in code:
* If the user requested "`allows ref struct`" (I would actually prefer to use `[<IsByRefLike>]` for that, not a constraint) but `*requires_heap` is inferred, you can fail typechecking immediately.
* If the user did not request "`allows ref struct`" explicitly (nor implicitly), you can choose which default behaviour you'd like when `*requires_heap` is *not* inferred ‒ it would make sense to add it silently, because most code is already compatible with it, and would benefit from getting it automatically.
