### ISSUE TITLE
Replace 'function' keyword

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fslang-suggestions#1246]
*I propose we ...*

do allow `decision` to be a replacement for `function`

_The existing way of approaching this problem in F# is ..._

There is not really a true solution to this now, as it requires understanding of the implementation to understand its semantic meaning.

Currently, the `function` keyword is used to describe pattern matching, without explicitly stating an argument. 

The issue with that is: `function` within itself is less of a totally accurate, descriptive word.

It requires some understanding of the implementation, just in order to understand the reason of its name.

It describes what happens under the hood, and not even that accurately, as opposed to `match .. with`, that communicates its intention, clearly and recognizible. 👍🏻  

I suggest this proposal in order to increase readability particularly for people, who are new to the language.

```fs
match expression with
| pattern1 -> result1
| pattern2 -> result2

decision (function)
| pattern1 -> result1
| pattern2 -> result2
```

## Pros and Cons 

The advantages of making this adjustment to F# are ...

This makes the language more coherent, transparent and predictable. Its also more communicative, and declares its intent clearly. 

The disadvantages of making this adjustment to F# are ...

It allows to do a thing, in a way that is already possible. 

So duplication of behavior, inconsistent experience between different codebases, and potential confusion while learning. 

(And also easier learning, since its communicating the intented behavior upfront.)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [ x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [ x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ x] This is not a breaking change to the F# language design
* [ x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by ShalokShalom** [comment]
In order to increase the benefits and decrease the disadvantages, could I see that we warn about the usage of `function' in future releases, and declare it outdated.

**Comment by RonaldTinashe** [comment]
> In order to increase the benefits and decrease the disadvantages, could I see that we warn about the usage of `function' in future releases, and declare it outdated.

I think existing working code should not suddenly emit warnings because of cosmetic changes in a future release.

**Comment by ShalokShalom** [comment]
After some communication with the community, do I come to the conclusion, that my former proposal, to use `match` instead of `function` may cause unwanted consequences. 

I did change it to `match with` therefor.

There are further concerns, that `match with` communicates that it's closer to `match .. with` than it really is. 

I personally think, that the difference between the two in type signature consequences are unavoidable, and that they can be though and seen quite naturally. 

In case that the team decides that this proposal is still too misleading, I do suggest `choice` as it still represents the semantic meaning. 

Other possible candidates can be suggested, obviously.

**Comment by BentTranberg** [comment]
This proposal is not about adding anything to the language, or solving a problem. It just adds work with no gain. I don't believe that this is significant with regards to clarity, teaching, onboarding, etc.

The `function` keyword is doing its job well enough, and has done so for a long time in ML languages, so why go to the trouble of introducing an alternate here? Or even change it? Because trouble it will cause for somebody, and for no good reason IMO. I have trouble seeing which will be worse going forward - adding an alternate, or changing it.

I also think the proposed alternatives are bad. `match with` are two keywords, which is messy when one will do. It can also be troublesome if an expression is forgotten in a match-with, and it's still legal code. If somebody is thinking `matchwith` then - well, that too could be a miswritten match-with. The function and the match-with are two different things, and I for one like that they are not using the same keyword(s).

`choice` and `fmatch` - the first I think will cause great confusion because of its use as `option` in other functional languages, if I'm not mistaken. The second makes me wonder whether it's a formatted match - anyway not a good keyword.

**Comment by 7sharp9** [comment]
Depreciate with warning would be nice.
