### ISSUE TITLE
Literal sprintf

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#129]
**Submitted by Dzmitry Lahoda on 8/8/2016 12:00:00 AM**  
**16 votes on UserVoice prior to migration**  

Allow:
```
[<Literal>]
let a = sprintf "%s" "string"
```

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/15591624)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-15591624-literal-sprintf.md#comments)

**Comment by dsyme** [comment]
There are many possible extensions to literals. These can actually be implemented by making a type provider that provides literal values based on arguments.  Since there is a way to do this already, I'm closing this, though I appreciate that the Literal mechanism could be combined with more compie-time meta-programming to be much more powerful
