### ISSUE TITLE
Allow static optimization conditionals

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#138]
**Submitted by lee on 9/28/2016 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

If we write the code as below, we will get a compile error: Static optimization conditionals are only for use within the F# library
```fsharp
let inline toBytes (x : ^a) : byte[] =
    (^a : (static member ToBytes : ^a -> byte[])(x))
    when ^a : byte = [|retype x : byte|]
    when ^a : string = System.Text.Encoding.UTF8.GetBytes(retype x : string)
```

But allow "static optimization conditionals" is very useful, which allow us avoid to use those tricks like "Simple typeclass implementation". http://www.fssnip.net/9B

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/16402732)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-16402732-allow-static-optimization-conditionals.md#comments)

**Comment by dsyme** [comment]
As per the archived comments on the original submission, there are good reasons not to allow this outside the F# core library - it is a rope for people to hang themselves on.  

Per policy, I'll close this since we don't revisit design decisions taken in previous iterations of F# unless there has been a significant change of circumstance
