### ISSUE TITLE
Allow type definitions at expression scope

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#150]
**Submitted by Gustavo Guerra on 3/21/2014 12:00:00 AM**  
**36 votes on UserVoice prior to migration**  

The suggestion is to allow "type X = ..." in an expression, e.g.

``` fsharp
let f () =
  type X = A | B
  let x = (A,A)
  let y = (B,B)
  if (x=y) then true else false
```

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5663202)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5663202-allow-to-define-types-at-expression-scopes.md#comments)

**Comment by charlesroddie** [comment]
This is a generalization of https://github.com/fsharp/fslang-suggestions/issues/277 .

**Comment by Happypig375** [comment]
@dsyme Now that #277 has been approved in principle, any chance that this can be approved as well?

**Comment by charlesroddie** [comment]
Presumably the scoping here would be purely about reducing accessibility, and that these types would be "static" and not have access to variables in the scope. E.g. this would not be allowed:
```fsharp
let y(x:int) =
    type T() =
        member _.X = x // Error: x is not defined
     T().X
```

This issue is then one of several that are about allowing static things to be defined in smaller scopes:

- [Allow static local functions (closed)](https://github.com/fsharp/fslang-suggestions/issues/765)
- [Attributes for local `let`s](https://github.com/fsharp/fslang-suggestions/issues/848)

In all these suggestions, things defined in expression scope could be treated as if defined as private things at a higher level in the same file (the nearest module or namespace).

I assume it would be OK to keep the type name the same, and give an error there is a name conflict.

```fsharp
module M

// If at least 2 of the three A definitions are present, there is a `duplicate definition of type A`

type A() = class end
let x =
    type A() = class end
    ()
let y =
    type A() = class end
    ()

```

Alternatively the name could be automatically appended to to give uniqueness.

**Comment by yatli** [comment]
> Alternatively the name could be automatically appended to to give uniqueness.

This will be problematic because once the outer type is shadowed, you cannot access it anymore because expression is not module/namespace

**Comment by oleksandr-bilyk** [comment]
Having nested types inside of F# OOP types would be useful to have as well. It will allow to minimize use of Anonimous Record
types and tuples as result of private functions.
Example
type External() =
     type IntegmediateResult= { A: int; B: int }
     let someInternalFunction(): IntegmediateResult = failwith "TODO"
     member _.Foo() =
           let i = someInternalFunction();
           i.A + i.B
I think that IntegmediateResult should be compiled as C# [nested type](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/nested-types).

**Comment by jl0pd** [comment]
@oleksandr-bilyk this example looks like a worse alternative to tuples with named fields https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples#tuple-field-names. Also I don't see what's wrong with anonymous records for such case, even allocations doesn't matter because records can be structs

**Comment by oleksandr-bilyk** [comment]
@jl0pd will reply to your comments
> @oleksandr-bilyk this example looks like a worse alternative to tuples with named fields https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples#tuple-field-names. Also I don't see what's wrong with anonymous records for such case, even allocations doesn't matter because records can be structs

1. I provided oversimplified sample. In my real code record type was more complicated. 
2. I also think that F# should support Tuple Field Names but in my case I needed complex internal structure and wanted record type.
3. Complex Anonimous record types when they passed through few private members are not readable well. If forces us to declare type outside of OOP type.
4. Ther are nested types in C#. According to .NET Framework Guidelines they may be result of public functions. I wish it be supported by F# as well.

**Comment by dsyme** [comment]
I'm closing this as declined.  It just raises a lot of issues about closure capture and representations if the types are allowed to include members.  

If only `static type` are allowed then I don't particularly think code becomes much cleaner.

**Comment by Happypig375** [comment]
@dsyme What about not allowing members at all? Only algebraic types. They would clarify flow control a lot.
