### ISSUE TITLE
Support syntactic macros

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#210]
**Submitted by Bryan Edds on 3/24/2014 12:00:00 AM**  
**453 votes on UserVoice prior to migration**  

At least give it a try in a private branch, and upon success, enable them publicly with a compiler switch initially.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5674940)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5674940-implement-syntactic-macros.md#comments)

**Comment by gsomix** [comment]
Bringing typed, modular macros to OCaml

https://oliviernicole.github.io/about_macros.html

**Comment by radekm** [comment]
I don't like the idea of having both type providers and macros in F# since they have a pretty big overlap - especially when https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1023-type-providers-generate-types-from-types.md is implemented.

And currently I prefer type providers over macros since they seem friendlier to IDEs.

**Comment by TIHan** [comment]
Macros add a great amount of complexity to the language. More focus should be on type provider functionality. Let's work with what we've got.

The argument for macros would be better if we had some listings of substantial use cases. Even in the original user voice, there is nothing in there that tells me macros is a must have.

**Comment by vasily-kirichenko** [comment]
Real word usage of that new OCaml macro system https://github.com/OlivierNicole/macros-examples/tree/master/staged-streams

**Comment by radekm** [comment]
@vasily-kirichenko In OCaml there already exist two ways to do that without modular macros:

* PPX (if you need types then you can use https://bitbucket.org/camlspotter/typpx),
* compiler plugin.

It would be easier to support compiler plugins (ie. a function which transforms typed AST to another typed AST) in F# compiler than implementing macros in F# language.

**Comment by radekm** [comment]
@vasily-kirichenko Wouldn't be user provided optimizations (optimization plugins) sufficient for implementing strymonas?

**Comment by Rickasaurus** [comment]
I like the idea of compiler plugins. It may be difficult to make it easy to plug into both the actual compiler and the intellisense compiler at the same time though.

**Comment by sighoya** [comment]
+1 for it

**Comment by pr-yemibedu** [comment]
Hello,
 The reason I want syntactic macros is for new syntax over that F# AST. 
 - One use case is to allow indexer syntax extension to be improved without waiting years or [faulting an underlying BCL implementation](https://stackoverflow.com/questions/39352811/system-string-extension-member-in-f-for-chars).
 - Another would be to allow Reflected Definitions to expose more underlying information so you can write a simple "**nameOf**" function with quotations.
- Also a computation expression might now be able to be nested. I am thinking test frameworks with heterogeneous builders that are recursive.

 We can have a simple abstraction point with *[Nim templates](https://nim-lang.org/docs/tut2.html#templates)* that can handle very flat and non-recursive scenarios? It is more powerful than "*computation expressions*", "*operators*", "*inline*" and "*quotations*" because its purpose is to combine them under a unified context of manipulation.

I mean to be able to create as needed and *then* to allow to the language authors a chance to bring in with the *best* implementation of your ideas seems reasonable too. There is a lot of overhead for showing proof for some small language features that could be alleviated this way. Maybe templates should be suggested separate of macros? Thank you. Good day.

**Comment by 7sharp9** [comment]
See myriad for a way of doing this at pre-compile:  7sharp9/myriad

**Comment by 7sharp9** [comment]
https://github.com/7sharp9/myriad
and the white paper: https://7sharp9.github.io/2019/04/24/2019-04-24-applied-metaprogramming-with-myriad/

**Comment by CameronAavik** [comment]
Here is some further reading on macros and their uses and implementation in Dotty:
- https://dotty.epfl.ch/docs/reference/metaprogramming/macros.html
- https://dotty.epfl.ch/docs/reference/metaprogramming/macros-spec.html

I see mentions here about how "compiler plugins" might be a better alternative, but I'm not really sure how that could support something like strymonas which was linked earlier.

I have an implementation of strymonas working using quotations [here](https://github.com/CameronAavik/StreamFusion). To summarise, it can convert the following code:

```fsharp
[|0; 1; 2; 3; 4|]
|> Stream.ofArray
|> Stream.map (fun a -> <@ %a * %a @>)
|> Stream.filter (fun x -> <@ %x > 2 @>)
|> Stream.fold (fun x y -> <@ %x + %y @>) 0
```

into the following efficient, iterative code:

```fsharp
let total = ref 0
let arr = [|0; 1; 2; 3; 4|]
for i in 0..(Array.length arr - 1) do
    let x = arr.[i]
    let y = x * x
    if y > 2 then
        total := !total + y
!total
```

While this is nice it has three main problems:
1. The performance limitations of `Expr` evaluators and compilers
2. It does this transformation at runtime and needs the user to cache the resulting expression to save having to pre-compile.
3. Quotations have limitations that make implementing and using this library difficult (https://github.com/fsharp/fslang-suggestions/issues/584)

My understanding is that a macros approach would mean we can generate the above code at compile time instead. How would a compiler plugin or type providers theoretically be able to support a use case like above?

**Comment by 7sharp9** [comment]
You might want to check out the Myriad and Falanx libs to see what alternative are also doing.  Falans somewhat abuses quotation to convert them back to syntax via fantomas but quotations are lossy.   Myriad on the other hand uses the AST.  Both of these are in my applied F# challenge paper from last year if you are interested.

**Comment by vasily-kirichenko** [comment]
> You might want to check out the Myriad and Falanx libs to see what alternative are also doing. Falans somewhat abuses quotation to convert them back to syntax via fantomas but quotations are lossy. Myriad on the other hand uses the AST. Both of these are in my applied F# challenge paper from last year if you are interested.

We used Falanx for some time to generate code out of proto files, but the compilation time was _large_, so we dismissed it in favor of the standard C# package. Why I'm writing this? Because any macro-like feature (Falanx, TPs) makes (already very slow) F# compiler unacceptably slow. So, I don't think F# needs any metaprogramming features.

**Comment by 7sharp9** [comment]
Myriad and Falanx both worked at compile time via msbuild being called during the recompilation step.  The slow area in this is firstly calling msbuild, that will always introduce a little latency, then secondly parsing quotations and transforming the AST a tiny bit more, but the most intensive part is fantomas which is really slow.  @vasily-kirichenko Is correct though these phases which use the compiler can be very slow.  

Im not sure if the bug where TP's are called multiple times still exists that used to slow down tooling a lot as there was no way to easily abort a request to re-parse the code.

**Comment by pr-yemibedu** [comment]
Hello,
 I think F# is being held in a glass jar. Looking very beautiful, but not available for its full potential. Its neighboring languages (modern and / or functional) tend to look towards embracing these two meta capabilities. Scala 3 (through Dotty) has this as an integral part of the language knowing it could have been left out giving the clean slate it is working from.

 What is it that **Scala**, **Clojure**, **Nim**, **Rust**, and **Crystal** understand about this benefit that is frowned upon by our communty? What is it that we feel makes it so important to not allow **F#** to be better hands down over **C#**?

 This is supposed to be a first class language of a billion dollar company. They invest so much in so many things at so many levels. Why not give this a chance (even with a proper fork (F$, F!, F%, F& or whatever symbol) and try something like clean template meta programming features to help us create some really beautiful things that others can get their hands on with waiting for a **RFP** to be cleared.

 I definitely think that it is doable without a compiler plugin (**Reflected Definition** was one key part). I also think it is not an all or nothing (Better functional **"self"** support, more robust compound operator support, improved inline function embedding locations). They are not little things (need to think of the whole language when adding any single feature). I just see them as beneficial and forward progressing for a language that deserves to let its wings spread and soar high above the alternatives.

Even languages like **Dafny** can bring insight and maybe their could be a Microsoft Global Compiler team that can cross help everyone with low hanging fruit to get the really innovative and game changing features available for users. Appreciate anyone who took the time to read this opinion. Thank you. Good day.

**Comment by 7sharp9** [comment]
Its important to note that Quotations don't support the full F# language and suggestions to add to them have been turned down:

https://github.com/fsharp/fslang-suggestions/issues/682
https://github.com/fsharp/fslang-suggestions/issues/681
https://github.com/fsharp/fslang-suggestions/issues/680

Also that syntactic macros themselves have been tagged as probably not too: https://github.com/fsharp/fslang-suggestions/issues/210

I think we are unlikely to ever see two full blown quotation based macros.  The design of quotations themselves loose information in the translation into the AST form which was what some of the above issues attempted to counter, so I don't see a way forward with quotations as they stand, short of a full redesign to make them first class.

**Comment by abelbraaksma** [comment]
> What is it that we feel makes it so important to not allow F# to be better hands down over C#?

It is already hands down better in almost every aspect. I code in both, but miss F# each time I choose in C#. A complex feature like this, that'll primarily be used by very advanced programmers is not going to convince people that think differently than me in the C# vs F# discussion. 

> Why not give this a chance (even with a proper fork (F$, F!, F%, F& or whatever symbol) 

@pr-yemibedu The beauty of open source is that anybody can. And perhaps if someone can prove this is possible, feasible and usable with such a fork, there's a good chance that it may be merged back into F#. The question is, who's going to do this work? Seems to me that it might take a single person about a year to get a reasonable implementation finished. 

I've read through the original thread, but they're was nothing concrete. No clear examples of scenerios how they're done now, and how they could be done more easily after. I'm talking actual syntax, how it could work, if at all, not the description of abstract use cases.

A good way to drive any proposal is to get consensus on syntax, use cases, compiler options, maybe even an RFC. Anyone who'd then like to pick it up will have a good chance of his PR being accepted.

**Comment by 7sharp9** [comment]
I don’t see the point of an RFC as Don has already indicated it won’t be accepted.

**Comment by TIHan** [comment]
A bit off topic, but,

@vasily-kirichenko 
> but the compilation time was large, so we dismissed it in favor of the standard C# package

We actively working on performance everyday with F#, so any examples that showcase perf issues help us a ton in improving perf overall.

**Comment by abelbraaksma** [comment]
> I don’t see the point of an RFC as Don has already indicated it won’t be accepted.

You're probably right. But it was marked 'probably not', which is not the same as declined. We could ask @dsyme why it as declined and whether that was on the grounds of protecting the language, or because there simply isn't time for a relatively risky new feature that we aren't even sure is possible yet. In the latter case, we could pick it up as community and try to concretize the proposal, and/or create a simple PoC,which could help understand the risk & time vs benefits.

**Comment by 7sharp9** [comment]
Personally I think that side projects like Myriad, Falanx and others in this category fit this explorations and could easily start to be applied to the compiler for deeper integration.  I wrote about Myriad extensively for the Applied F# challenge for this reason.

**Comment by stevenarnold** [comment]
> A complex feature like this, that'll primarily be used by very advanced programmers is not going to convince people that think differently than me in the C# vs F# discussion.

Advanced programmers might be the ones who create macros, but I bet every programmer will use them all the time. It's certainly this way in most languages that support macros. They get used a lot. There's got to be a reason for that. For me, the reason is that macros provide tremendous expressive power.

**Comment by dsyme** [comment]
I'm going through old major issues with the "either close it or mark it as approved" approach. 

I'm closing this as it's never really been envisaged that this is going to be part of the F# design.  There are use-cases for sure but the complexity introduced is huge.
