### ISSUE TITLE
Allow Unicode symbols to be used as operators

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#224]
**Submitted by Jerold Haas on 3/27/2014 12:00:00 AM**  
**76 votes on UserVoice prior to migration**  

Suggestion moved from https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2314078-allow-unicode-symbols-to-be-used-as-operators
It would be great to define mathematical operators (e.g. ∀, ∑, ∩) in F#, and be able to use other Unicode symbols (such as arrows) in operators as well. So instead of saying

```
let inline (!++) xs = xs |> Seq.sum
```

you could say

```
let inline (~∑) xs = xs |> Seq.sum
```

Writing `∑myList` is much, much easier on the eyes and brain than trying to figure out what `!++myList` does.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5688398)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5688398-allow-unicode-symbols-to-be-used-as-operators.md#comments)

**Comment by dsyme** [comment]
As discussed in the comments in the original submission, this is a minefield....  Deciding the precedence for such operators is really hard.  It would also create swathes of unreadable F# code.

I'll close this since we've previously decided not to do this in F# 2.0, and there has not yet been a major change of circumstance to warrant altering this which addresses the concerns.

**Comment by charlesroddie** [comment]
> @dsyme As discussed in the comments in the original submission, this is a minefield.... Deciding the precedence for such operators is really hard. It would also create swathes of unreadable F# code.

This is also not an accurate summary of the comments in the linked submissions. Precedence rules didn't come up except in support of unicode operators.

Precedence rules would be the same as for current operators. The only thing needed to implement this feature is to add a finite list of new operator symbols, with some alphabetic representations, extending the current list:

![image](https://user-images.githubusercontent.com/19760720/57581241-8f5dd900-74ac-11e9-8d8a-c20898205bcc.png)

**Comment by charlesroddie** [comment]
The post against operators, which @dsyme agreed with, gave reasons:

> @jack-pappas My chief concern is that you'd be forcing consumers of your code to use these symbols as well.

Debatable, and a conservative note could be given in the F# style guide that it may not be advisable to expose these in non-specialist libraries for external use.

> @jack-pappas A number of mainstream development tools (including parts of VS) weren't designed with Unicode symbols in mind, and won't work properly when code or compiled assemblies use them in type/field/method names.

This comment is from 2014. I haven't encountered any problems in VS2017/9. The following code works according to spec, for example:
```fsharp
type ỤṅỉḉØᵭᴱ(ĉ:char) =
    member t.ĉĉ = string ĉ + string ĉ
let Ж = ỤṅỉḉØᵭᴱ('♫').ĉĉ
```

**Comment by cartermp** [comment]
It might be worth noting that unicode _values_ are a little strange for debugging and FSI:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/6309070/57584499-008f9300-7491-11e9-8ddf-b881791bc832.png">
<img width="198" alt="image" src="https://user-images.githubusercontent.com/6309070/57584503-17ce8080-7491-11e9-8611-635bbe97a669.png">

But otherwise they aren't really problematic. They color, show in tooltips, can be debugged, etc. in VS.

**Comment by voronoipotato** [comment]
@baronfel technically since single argument operators work kinda like functions, you can already do this. 

just tested in FSI 
```fsharp
> let ``Σ`` = Seq.sum
- ``Σ`` [2;3;4;5;6];;
val Σ : (seq<int> -> int)
val it : int = 20
```

Don I recommend you look away for this bit.

If you want to use it like an operator this works presently.

```fsharp
let ``🍔`` a b = a * b
3 |>``🍔``<| 4
//or ....

type System.Int32 with
  member x.``🙅`` n = x * n

3 .``🙅`` 5
```

**Comment by voronoipotato** [comment]
@dsyme I know we closed this because operator precedence, but what if instead we treated it like APL where unicode operators go left to right unless parentheses say otherwise? I think it's a potentially huge value add for math and science programmers (matlab and datascience crew), which we could court with our fancy math operators. In windows the `super+;` keyboard makes them easy to type. I think it makes sense given that the notation would actually be significantly less foreign to those familiar with the operators, and those who are unfamiliar would be lost anyway because math has a learning curve.
