### ISSUE TITLE
Allow implementation of abstract slots with generic return type instantiated at type 'unit'

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#25]
**Submitted by Eric Stokes on 1/8/2016 12:00:00 AM**  
**7 votes on UserVoice prior to migration**  

The behavior described [here](http://stackoverflow.com/questions/26296401/why-is-unit-treated-differently-by-the-f-type-system-when-used-as-a-generic-i) is quite surprising to someone coming from other typed FP languages. The fact that a generic type parameter can't be unit makes the whole generics abstraction feel a bit leaky and hacky, which isn't great publicity, as F# actually has a lot of great ideas.

In practice this comes up when implementing type indexed values of various sorts, as an interface is an ideal and natural way to do that, and of course one often wants to have a sometype<unit> value. The compiler error is rather surprising as well, as it implies the object expression doesn't implement the interface, which of course isn't the case.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/11356293)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-11356293-allow-implementation-of-abstract-slots-with-gener.md#comments)

**Comment by dsyme** [comment]
(adding old approval comment) 

Approving this in principle, it would be great to fix this behavior. We will open an [RFC](https://github.com/fsharp/FSharpLangDesign/tree/master/RFCs) on this in due course, though this is not yet high priority.

There are reasons for the existing behaviour due to unit v. void, as explained in the various stackoverflow topics on this question, but it should be possible to workaround those.

Don Syme, F# Language Evolution

**Comment by dsyme** [comment]
When implementing such a method
```
        override __.Eval (args) = expr
```
we would presumably need to emit two methods:
```
        override void Eval (args) = this.Eval(args); [ret]
        member FSharpUnit Eval (args) = expr
```
Tailcalls would be lost, because of the need to discard the "FSharpUnit" value

**Comment by dsyme** [comment]
Closing this as we won't be addressing this specific technical limitation, it is not a significant problem in practice.
