### ISSUE TITLE
Wildcard self identifiers

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#333]
**Submitted by Daniel Robinson on 9/29/2014 12:00:00 AM**  
**9 votes on UserVoice prior to migration**  

Two underscores are frequently used in member definitions to denote an ignored "self" identifier. This seems like a hack given that the language already provides a wildcard pattern that represents an unused value.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6499392)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6499392-wildcard-self-identifiers.md#comments)

**Comment by dsyme** [comment]
I’m marking this as approved in principle for F# 4.×. you are invited to submit a quality and tested implementation would be needed, to be submitted to http://github.com/Microsoft/visualfsharp.
See http://fsharp.github.io/2014/06/18/fsharp-contributions.html for details about contributing to the F# language and core library 

FWIW I’ve actually taken a look at this once or twice and it was surprisingly invasive to implement. But by all means give it a go and ask if you need help.

Don Syme BDFL F# Language/Core Library Evolution

**Comment by Regent** [comment]
@dsyme does this require an RFC?
Any pointers to where is it the best to start?

**Comment by dsyme** [comment]
@Regent In theory an RFC is required but it can be ultra short unless you discover corner-cases in the implementation

For implementation - starting with this:
```
type C() = 
   member _.P = 1
```
and compiling using ``fsc.exe a.fs`` we get a syntax error.  Syntactically ``_.P`` is a pattern.  Looking through the parsing rules in ``pars.fsy`` for ``memberCore`` I eventually get down to ``atomicPatternLongIdent`` as the thing being parsed

So, the first thing to start is to add ``_`` to the parser in the appropriate place for long identifiers in patterns, e.g.

```
atomicPatternLongIdent:
  | UNDERSCORE DOT pathOp  { let (LongIdentWithDots(lid,dotms)) = $3 in (None,LongIdentWithDots(ident("_",rhs parseState 1)::lid, rhs parseState 2::dotms)) }
```
or something like that. The  only problem is that this use of ``UNDERSCORE`` might cause conflicts with this:
```
atomicPattern:
   ...
  | UNDERSCORE 
```

If so that might need to be investigated.

**Comment by gusty** [comment]
I tried adding the rule @dsyme suggested at the top level position of `atomicPatternLongIdent` and it seems to be working fine. See https://github.com/dotnet/fsharp/pull/6829

CC @cartermp

**Comment by pblasucci** [comment]
@gusty This is syntax I’ve wanted since 2007 🤪

**Comment by gusty** [comment]
Yes, me too, long time.

It's all green already, either it was easier than what we thought, or failing test is missing.

**Comment by cartermp** [comment]
Closing as this is in for F# 4.7
