### ISSUE TITLE
Add support for separated type annotations

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#341]
**Submitted by amazingant on 10/8/2014 12:00:00 AM**  
**58 votes on UserVoice prior to migration**  

Although it's typically preferred to let the compiler handle types, it is often necessary to provide type annotation. Sometimes this is to help the compiler understand the types a function can take, often it is done to help other developers understand your code, and in my personal use, I frequently add type annotations to ensure the compiler will catch typos I make which change a function's return type.

Although not as verbose as other .NET languages, the F# type annotations do add verbosity to a function definition, look cluttered compared to Haskell's syntax (personal opinion), and do not match the type format provided by the compiler or interactive environment.

I propose adding syntax to allow defining a function's type with a syntax closer to Haskell's. Since the `::` operator is already in use, my proposal is to create a new operator such as `=>` for these purposes; a new keyword could suffice as well, or simply new use of the val keyword currently used in signature files.
My initial suggestion is as follows:

``` fsharp
let f => int -> int -> int
let f x y = x * y
```

While the inclusion of variable names would reduce the terseness of the syntax and would provide little benefit to readability or comprehension, such a change would provide consistency with the format output by fsi.exe and seen in Visual Studio with IntelliSense. An more complex type signature with such a format:

```
let f => a:(int -> string -> int) -> x:string list -> y:int -> int list
let f a x y = List.map (a y) x
```

In these examples, neither of the code snippets would typically need type annotations, and the annotations here are much larger than the implementation itself. However, the former syntax (my preference) would greatly reduce the length of function declarations in more complex functions. The latter option, while I would prefer it over the current syntax, would introduce an additional location where variable names would have to be changed during refactoring.

It is my opinion that were such a syntax to be provided, use of both the new and current syntaxes together should provide a compiler warning to the effect of "Multiple type annotations provided for function {0}. Consider removing extra type annotations to simplify refactoring of your code."

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6538074)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6538074-add-support-for-haskell-style-type-annotations.md#comments)

**Comment by yawaramin** [comment]
IMO we can achieve an equivalent level of de-cluttering, and keep the 'spirit' of ML, by making the type inference engine use types from signature files as input the same way it does annotations in the implementation files. If I'm not mistaken, OCaml does this as well, right? Since we can ascribe a more restricted type to a value in the interface file than in the implementation.

**Comment by michelrandahl** [comment]
After looking into Idris I've also become a proponent explicit types, and I've been adding explicit types to all my F# code _(and most of my Python code as well)_ ever since.
I feel explicit types add a lot of documentation value to the code. Its like adding comments to your code, -except these 'comments' are much better because they are type checked :).

**Comment by yawaramin** [comment]
@michelrandahl hi, I feel signature files (or interface files) are a good place to put all the explicit type annotations, because they already exist and are used, and wouldn't require any surface changes to the language. The only problem with them is as I mentioned above.

About the automatic annotation adornments, check out Visual Studio Code or Atom with the Ionide plugin. It does that. The feature is called CodeLens. Actually I found it rather annoying, so I turned it off. I can get type info any time by hovering over or clicking in any symbol.

**Comment by michelrandahl** [comment]
@yawaramin I guess it all comes down to personal preference, where my preference is that of the style used in Idris/Haskell eg. type signatures together with the code. If it was ever implemented in F# I would prefer it to be optional of course. 
Anyhow, I think you might be right that it would be a too radical change/addition to the language.

Thank you so much for pointing out that the adornments already exists with Ionide, I've been missing that feature so bad. It's looks exactly how I wanted. 
Now I just hope someone will implement it for emacs as well, or I'll just have to finally get around learning how to make emacs plugins ^^.

**Comment by cloudRoutine** [comment]
```fsharp
let f : int -> int -> int =
    fun x y -> x * y
```
Is currently valid syntax and gets you most of the way there and iirc the IL generated after compilation is exactly the same as `let f x y = x * y`

**Comment by toburger** [comment]
@cloudRoutine quite neat!

This method could be handy to write some script/prototype/exploratory code, but the downsides are that it is not very common to write functions this way and it would be advisable to adapt the function declaration if it is used in a production application.
I would love to have **optional** type annotations like used in Idris/Haskell.

**Comment by yawaramin** [comment]
@toburger top-level type annotations are mandatory in Idris.

**Comment by kspeakman** [comment]
I've used both ways now in Elm (annotations above) and F# (annotations inline). At first, I loved Elm annotations and wished F# had them. But as time went on the Elm annotations became a bit of a chore. Even if you could define them as:

```elm
myFunc : a -> MyRecordType -> b
// or even
myFunc : _ -> MyRecordType -> _
```

It's a chore to declare every parameter's type when you only really need it for MyRecordType.

Now, F#'s inline annotations are certainly not perfect. In particular, having to wrap  characters around a parameter with "( ... : MyRecordType )" is also a chore, and the parameter looks "ugly". But I prefer being able to annotate only the parameters that require it instead of having to declare (at least some placeholder) types for every parameter. I usually wait until the compiler complains before adding an annotation. Otherwise, I let the code be as generic as possible.

**Comment by toburger** [comment]
I think there are three purposes for type annotations:

* **Making the compiler happy:** inline extensions are the way to go. Oftentimes you only have to annotate a single argument so a separate type annotation is too verbose with all the wildcard types.
* **Writing (all) types for documentation purpose:** separate type annotations are way more readable. For large scale projects a separate signature file can be handy (and writing the doc comments together with the type definitions). One limitations exists though: signature files are a good mechanism to describe the public API, I don't think it is a good fit for private functions, they are oftentimes the moving parts of the application and maintaining two files is overhead.
* **Writing types before writing code:** in functional programming oftentimes you know the function signature before you know how to implement the function. Separate type annotations are way more elegant to work with.

**Comment by voronoipotato** [comment]
Function signatures as they are feel borderline vestigial. What's the work it would take to add this so that the signature actually counts as annotation, and I can do this inline? Having it as an entire separate file is a whole lot of work replicating my entire program structure, and I can't use it in FSI. I'm somewhat new to compiler discussion and frankly F#, https://fsharpforfunandprofit.com/posts/function-signatures/ brought me here. If it something that a small group of users are passionate about maybe we could be guided into doing the work, and improve the number of project contributors. 

```
val foo int -> int
let foo x = x
```

**Comment by erbaman** [comment]
What bothers me the most is the fact the style isn't consistent.
Let's say I choose to let the compiler handle types but then sometimes I might have to help it out which makes me end up with code like this:

    let f x = ...
    let g x (y:MyType) = ... 

Or maybe I feel like annotating the types:

    let f : 'a List -> 'a option = function
      | []      -> None
      | x :: _ -> Some x

    let g (x:int) (y:int) : int = x + y`


In order to make the code look consistent I pretty much have to resort to writing the function g above like this:

    let g : int -> int -> int =
      fun x y -> x + y

I personally find `f: int -> int -> int` more readable than g (x:int) (y:int) : int. Not only that but the former is also the way types are annotated in intellisense, fsi, signature files and so on.

@baronfel 
`I propose adding syntax to allow defining a function's type with a syntax closer to Haskell's. Since the :: operator is already in use, my proposal is to create a new operator such as => for these purposes; a new keyword could suffice as well, or simply new use of the val keyword currently used in signature files.`

I'm not sure about using the `=>` operator as it could potentially be used in the future for (much needed) improvement to type constraint syntax? ;)

**Comment by voronoipotato** [comment]
I don't think using lambdas is a solution. Perhaps something like this would be nice. This would allow you to pass your function into a neatly named slot. Right now of course this gives an error.
```F#
type CoolFunction = int -> int -> int
let (kickflip:CoolFunction) x y = x * y
```
and this currently works
```F#
type CoolFunction = int -> int -> int
let (kickflip: CoolFunction) = fun x y -> x * y
```

Using a type for this is nice because it gives you a practical name for the signature beyond what it consumes and beyond the specific implementation details aka the function name. In this sense the type represents a kind of "functional interface" which can be consumed by other functions.

**Comment by 7sharp9** [comment]
Anyone have a feel for whether on not this would ever be approved?
/cc @dsyme / @cartermp

**Comment by cartermp** [comment]
I'm really undecided on this one. After programming a lot of haskell recently, I get the appeal. But something about it just doesn't feel right for an ML.

**Comment by kspeakman** [comment]
VS2019 comes with (experimental) CodeLens feature, which will display an annotation above (or beside) the function. With this, most of the reason I liked type signatures from Elm are satisfied: I get to see the separate type signature. But now I get that without having to type it out manually, nor having to keep it updated.

It wouldn't hurt my feelings if this feature were implemented, but our team would almost never use it. We really like the almost-dynamic feel of not having to specify types most of the time. Plus (from Elm experience) maintaining a separate type signature eventually feels like a chore -- you have to update 2 lines if you add/remove (or something change) a parameter. We probably wouldn't do type signatures in Elm anymore, except the compiler issues a warning if you don't. I'd much rather see effort toward type signatures first go into getting CodeLens out of experimental status. Then see what's what after that.

**Comment by 7sharp9** [comment]
I wish F# emitted a warning for a top level function without an annotation.

**Comment by kspeakman** [comment]
> I wish F# emitted a warning for a top level function without an annotation.

If you really wish it, make an issue suggesting the feature (maybe in the compiler repo?). It could be behind a compiler flag, for example. That would make it controllable from build scripts or IDE configurations.

**Comment by toburger** [comment]
> 
> 
> I'm really undecided on this one. After programming a lot of haskell recently, I get the appeal. But something about it just doesn't feel right for an ML.

Can you explain what about separated type annotations doesn't feel right for an ML?

**Comment by adam-becker** [comment]
I like the concept of signature files for enforcing types on top-level functions in a library, but their use is a bit clunky and requires doubling up the number of files in a project. Also, being able to do these inline would provide a convenient way around the old "value restriction" issue.

> I'm really undecided on this one. After programming a lot of haskell recently, I get the appeal. But something about it just doesn't feel right for an ML.

To be clear, the feature requested in this issue is nothing new for F#. The ability to add separated function signatures already exists with signature files. The desire to be able to write the signature closer to the function is more desirable than having a separate file for a few reasons.

Having a separate file to manage on top of the implementation feels very C/C++ header-y, and just creates additional burden. It would be great If we were able to define signatures as we do now in a signature file, but inline with the source:

```f#
 // no non-intuitive value restriction error
val someValue : int32
let someValue = someGenericFunction ()

// the names of type parameters should come from the annotation as well; no more 'a0, 'a1, etc
val bind : Option<'a> -> ('a -> Option<'b>) -> Option<'b>
let bind option binder = ...
```

A few common complaints I've heard when showing people F#, and trying to spread it's use is that
* The type annotations for functions look clunky.
* The type inference system allows different signatures to be inferred for a public function, breaking the API.
* Signature files feel burdensome, especially in light of F# requiring users to manage the order of files in the `*.fsproj` file.
* Signature files move the signature further away from the functions, making them harder to review or see.

Having inline (but separate) type annotations would address all of these concerns. I would add to this that the compiler should allow generating a warning for public functions without an associated signature as well.

To address arguments against this feature in the vein of "x tool provides a tooltip showing a signature"; this does no good when reading the code in an editor that doesn't provide such a feature.

**Comment by smoothdeveloper** [comment]
@voronoipotato the issue with the examples providen in your post is the loss of parameter names (and their documentation?)

I actually like the approach of unifying the signature file syntax that @adam-becker proposes, although I don't find the current type annotation syntax to be clunky, it is the same as in most languages, baring C/C++/java and C# among the popular ones; the syntax is in fact more consistent than C type languages having their casting syntax and type comes before symbol name dichotomy.

**Comment by adam-becker** [comment]
@smoothdeveloper I personally dislike having to wrap parameters in `()` and put a colon after the name just to introduce a type annotation. In this way, they are heavier than most languages.

But the only reason I have to do that is because the alternative (making a new file and having the annotation far away) is lacking.

I think if this were to be adopted, there should be a rule to enforce that a type annotation is always directly above the thing being annotated.

```fsharp
// this should not be allowed because it defeats the purpose of merging the *.fsi file
val add : int32 -> int32 -> int32
let multiply a b = a * b
let add a b = a + b
```

**Comment by abelbraaksma** [comment]
> there should be a rule to enforce that a type annotation is always directly above the thing being annotated.

Though a strong argument for this feature is the opposite: there are plenty scenarios where you know the type of a function, but want to defer the implementation. The current way to solve that is with interfaces, but they cannot be applied to functions in modules and require type instantiations. 

An alternative could be (thinking out of the box) to allow interface-style declarations for modules and/or static classes. Some languages, like Java since v8, support this, and iirc, it was part of Eiffel too. Though static interfaces are a notion in OO, the concept could easily be adopted to the functional paradigm.

A module that inherits a static interface (or say, a function group definition), must implement the functions, just as if it's a normal interface, but without the class instantiation. 

And just like normal interfaces, you can consume methods from the static interface as parameters or define variables of such deferred functions, but to call them, they must be given a concrete implementation.

This would by no means be a small language change, with undoubtedly a lot of questions to be answered, but it gives a lot of freedom on top of what's suggested in the original lang suggestion here.

**Comment by adam-becker** [comment]
@abelbraaksma There's already a way to keep signatures and implementations separate, `.fsi` files! :smile: 

Joking aside, having chosen F# for its functional aspects mostly puts me off of the idea of solving problems in the language by introducing OO concepts, like interfaces and inheritance. But if you really believe in this idea, it's distinct enough to be its own suggestion and you should definitely open an issue to argue in favor of it.

Back to the proposal at hand, I don't believe it's a very big lift, as all of the pieces needed to implement already exist. The pieces just need to be brought together and it may take some work, but I would love to have this as an option for defining type signatures.

**Comment by 7sharp9** [comment]
Oh no, please surgically extract `.fsi` files.  Its like going back to header files.  Moving comments and signature to a sig files is just awful.

**Comment by 7sharp9** [comment]
I don't think this suggestion adds anything to F#, I do like the idea of making there compiler output a warning if you don't have a full type signature on a top level public type though.

**Comment by abelbraaksma** [comment]
> There's already a way to keep signatures and implementations separate, .fsi files! smile

@adam-becker, that's it what I meant. FSI doesn't allow writing the signatures before usage, let alone before definition.

Another way to look at this is (in compile order):

* define full signature
* use it as if it exists
* define implementation

**Comment by 2jacobtan** [comment]
![image](https://user-images.githubusercontent.com/12626411/82752981-a429b800-9df4-11ea-9331-5399b205a82f.png)

Linter is mad at me :(

**Comment by abelbraaksma** [comment]
@2jacobtan, I fail to see the relevance to this thread? Maybe you intended to post it in the FSharpLint github repro instead? (btw, Lint is correct with its suggestion, you can replace the whole function with just `( * )`).

**Comment by 2jacobtan** [comment]
> @2jacobtan, I fail to see the relevance to this thread? Maybe you intended to post it in the FSharpLint github repro instead? (btw, Lint is correct with its suggestion, you can replace the whole lambda with just `( * )`).

Apologies for the irrelevance.

But thank you for the tip!! I finally understand the lint message.

**Comment by abelbraaksma** [comment]
@adam-becker, this thread is about a language suggestion about type annotations to be separate from the definition. The linter message was about lambda elimination. I'm trying to connect the dots, but fail to see it. If others do see the connection, then by all means, please disregard my message ;).

**Comment by konst-sh** [comment]
To me the idea looks like it might worth it, if it will stay optional. Moreover it seem that the separate string for signature declaration might not even be needed, if it be possible to declare function type right after its name like that:
`let functionName: 'T1->'T2->...->'Tn
      arg1 arg2 ... argn =
     .......
`
This approach to function type annotation seem to be even backward compatible.

**Comment by MarkNicholls** [comment]
Having originally learnt my fp in Haskell, this is the single most important thing I miss! Not typeclasses of higher kinded types or all the fancy bells and whistles of Haskell.
For me they are invaluable mechanism for me to write down (like a logician) what I intend to implement/prove, before writing the code.
Code lens is after the fact.
(I think Wadler suggests writing signatures before implementations - though i may have got that wrong, and its pretty standard practice in logic (curry/howard bla bla bla)).

I DO sometimes revert to the lambda style
```
let f : int -> int =
   fun x -> x  
```
but view this as a poor substitute

**Comment by ShalokShalom** [comment]
Considering the conciseness of fsharp at basically all other places, and **particularly** the verbosity of higher level functions and their type signatures, I consider it suitable to the rest of the languages design, to provide Haskell like type annotations.

**Comment by dsyme** [comment]
As part of going over long-opened issues, I'm closing this out - we won't add separated type annotations to F# in the forms discussed above. As mentioned above, one of the main reasons is the gradual appearance of CodeLens tooling which allows for the full inferred signature of functions to be easily inspected in IDE tooling.  This reduces the need to make this explicit in the code.

I get that this is still something many people long for but I don't think in balance it's the right direction to add this into the language in any of the suggested forms above.

**Comment by ShalokShalom** [comment]
I can't edit the inferred type, and I understand that the fsharp way of 'inference first' is valuable and worth to be defended. 

Still, I think **IF** we are providing type annotations, the Haskell way is more aligned with the aspirations of FSharp: 

Readability, Conciseness and Types first. 

I am still fine with closing this and forgetting about it, since I dont think FSharp makes it that needed to annotate types in the fist place.

**Comment by ShalokShalom** [comment]
I can't edit the inferred type, and I understand that the fsharp way of 'inference first' is valuable and worth to be defended. 

Still, I think **IF** we are providing type annotations, the Haskell way is more aligned with the aspirations of FSharp: 

Readability, Conciseness and Types first. 

I am still fine with closing this and forgetting about it, since I dont think FSharp makes it that needed to annotate types in the fist place.

**Comment by 7sharp9** [comment]
@ShalokShalom I think all public API facing types should be annotated, otherwise you have no strict interface into your public API.

**Comment by ShalokShalom** [comment]
Yeah, I just dont know if it's worth integrating it just for that. 

Maybe it's more sensible, to improve signature files for that ;)

**Comment by voronoipotato** [comment]
🤔.. hmm  (they should really add a thinking response to github). @MarkNicholls  You can still generate a fsi towards this end but I get your point about being able to do it granularly.

**Comment by ShalokShalom** [comment]
> 

I guess you could still use signature files. 

They ensure type safety as well, and dont clutter the main source code at all.

**Comment by MarkNicholls** [comment]
> ....As mentioned above, one of the main reasons is the gradual appearance of CodeLens tooling which allows for the full inferred signature of functions to be easily inspected in IDE tooling. This reduces the need to make this explicit in the code.
> 

codelens is removed from VS 2022 (I dont use vs code) #14256

I am falling back on function value signatures and explicit interfaces (ew, I'm turning into a scala programmer!).

Seems odd that functions are 2nd class citizens in this regard.
