### ISSUE TITLE
Allow opening of static classes (matching the C# design)

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#383]
**Submitted by Isaac Abraham on 1/13/2015 12:00:00 AM**  
**31 votes on UserVoice prior to migration**  

You currently can't "open" a static class e.g. System.Console - only modules or namespaces. We should be able to also open static classes as well.
## Response

*\* by fslang-admin on 2/4/2016 12:00:00 AM **

Thanks for the suggestion. Approved in principle. We will open an RFC for this in due course https://github.com/fsharp/FSharpLangDesign/tree/master/RFCs

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6958404)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6958404-allow-opening-of-static-classes-matching-the-c.md#comments)

**Comment by Richiban** [comment]
Is it intended that this apply only to `static` classes? (I can't remember how static classes are represented in IL, is it just both `sealed` and `abstract`?).

For the record, C# allows one to 'open' any type that simply has at least one static member.

> The using static directive applies to any type that has static members, even if it also has instance members.
> https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-static

**Comment by duncanmak** [comment]
I'm interested in working on this.

Should F# match the C# behavior, or should it just allow opening static classes? 

I think personally, I prefer only allowing static classes.

**Comment by jwosty** [comment]
(@duncanmak)
> I think personally, I prefer only allowing static classes.

I would expect this as well.

**Comment by dsyme** [comment]
> Should F# match the C# behavior, or should it just allow opening static classes?

I think F# would support the same behaviour as C# if we implement this feature.

**Comment by dsyme** [comment]
See https://github.com/Microsoft/visualfsharp/pull/6309

**Comment by 7sharp9** [comment]
@dsyme Is this going to fundamentally change the way F# is written?

I mean now we have the question of whether to use a module or a static class, static classes have the benefit of named params and optional parameters, the only thing limiting a static class is the fact they cannot be nested but modules can.

**Comment by alfonsogarciacaro** [comment]
Will this be compatible with `AutoOpen` attribute? This will be necessary if you want to use this feature to replace an `AutoOpen` module with a static class in order to use optional arguments or ParamArray.

**Comment by dsyme** [comment]
> Will this be compatible with AutoOpen attribute? 

Yes

> @dsyme Is this going to fundamentally change the way F# is written? I mean now we have the question of whether to use a module or a static class, static classes have the benefit of named params and optional parameters....

The impact of this on F# methodology is definitely worth discussing.  

* The intent is that it only impacts F# methodology for "DSLs", loosely speaking.  However there is a chance people will turn to classes for the extra notation conveniences you mention, where previously they would have used a module-that-you-open.

* That said, defining a static-class-that-you-open is not a particularly simple of natural way of writing an API.  For example, `FSharpChecker` in FCS does use static methods, but is not a static class (it contains instance members).

* Other APIs rarely feature modules-that-you-open.  Internally in an implementation they are used (e.g. there are lots of them in the F# compiler), but those can't be converted to static classes because of the lack of nested types.

* It is likely we will still support named and optional arguments on module-defined `let` functions at some point, which would reduce the temptation to use static classes.

All in all I think that

(a) I do think some people will be tempted to try to move their modules-that-you-open to static-classes-that-you-open 
(b) they will soon realize that the lack of nested types makes this uncompelling 

So I think the overall disturbance in the force will be limited

**Comment by dsyme** [comment]
RFC here: https://github.com/Microsoft/visualfsharp/pull/6309

**Comment by vasily-kirichenko** [comment]
> It is likely we will still support named and optional arguments on module-defined let functions at some point, which would reduce the temptation to use static classes.

Tupled module and local functions should support named and optional arguments for sure. I find myself defining classes just to get these features.

**Comment by 7sharp9** [comment]
Over the last year or two I have started using static members a lot more to use the optional parameter syntax rather than currying some parameter.

**Comment by cartermp** [comment]
Closing is this is now in for F# 4.7

**Comment by cartermp** [comment]
This is actually completed for F# 5, with a different design, called `open type`. But it accomplishes the same thing.
