### ISSUE TITLE
Allow finer-grained control of "open", like Haskell's "import hiding"

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#492]
# Allow finer-grained control of "open", like Haskell's "import hiding" [9987774]

**Submitted by Robin Munn on 9/30/2015 12:00:00 AM**  
**21 votes on UserVoice prior to migration**  

Currently, F#'s `open` keyword imports everything from the opened namespace, which can result in unexpected shadowing. For example, if I do:

```fsharp
open Foo
// fn1 and fn2 are defined in Foo
let bar (x:Foo.DataType) : DataType = x |> fn1 |> fn2
```

If a later version of Foo defines a `bar` function that does something completely different, I might later write code that tries to call `Foo.bar` as `bar`, forgetting that I had created my own `bar` function. Worse, if `Foo.bar` is defined with the type `Foo.DataType -> Foo.DataType`, then the compiler won't even be able to save me from my mistake!

What I'd like to be able to do is specify exactly which names I'm importing from any given module. Something like one of the following syntax examples:

```fsharp
open Foo using only (fn1, fn2)
open Foo importing (fn1, fn2)
open Foo with only (fn1, fn2)
open Foo with (fn1, fn2)
```

Or, alternately, to import everything except for a few names:

```fsharp
open Foo hiding (bar)
let bar = ... // Be explicit about not shadowing
```

The syntax examples I've listed above are only a few possible ideas that I came up with in five minutes; other possible keywords might be better.

This is related to, but not the same as, the following two suggestions:
* #383 (`open` static classes)
* #310 (aliases for namespaces)
* #227 (`open` in local declarations)

The Python community has had a long-standing recommendation NOT to use `from Foo import *` (the Python equivalent of `open Foo`, which imports all its names into the current namespace), due to precisely the kinds of namespace pollution issues that `open Foo` can cause. The strong recommendation in Python is to be explicit about what names you're bringing into your local namespace: `from Foo import (fn1, fn2)` and I'd like to see F# allow that very good practice as well.

## Response

*\* by fslang-admin on 2/4/2016 12:00:00 AM **

Thank you for making this suggestion. I’ve marked it as declined per my comment below.
However I sympathise with the suggestion and would like to hear more if you find specific situations where not having this feature has caused bugs,
Don Syme,
F# Language and Core Library Evolution

**[Original UserVoice Submission](../blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-9987774-allow-finer-grained-control-of-open-%2C-like-haske.md)**
[Archived Uservoice Comments](../blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-9987774-allow-finer-grained-control-of-open-%2C-like-haske.md#comments)

[Edited for updated issue links and syntax highlighting by @baronfel on 2020-01-05]

**Comment by Krzysztof-Cieslak** [comment]
Hey, 

I'd like to revisit this suggestion. In recent years this feature has been added to several languages, the ones worth mentioning here are:
* JS (ES6/2015) and TS - `import { myLogger, Alligator } from 'app.js';` 
* Elm - `import Html exposing (Html, div, h1, p)`. 

In case of Elm (just like in Python what was mentioned in original suggestion) importing everything (`import Html.Attributes exposing (..)`) is treated as anitpattern (unless there are good reasons to import everything - example I've used `Html.Attributes` is actually one of modules where it make sense to import everything).

In case of JS there is even no syntax for importing everything - all you can do is creating qualifier (`import * as App from 'app.js'`)

As mentioned above `open MyModule (func1, func2)` could nicely solve pollution of current entity space visible in file and give developers a way to solve the problem with accidental shadowing. It would also forced people to think bit more about design of their code, coupling etc, which in general fits into F# theme of language pushing users into good design.

---

Additionally I'd want to extend the proposal to include `open qualified MyModule (func1, func2)` from Haskell

My main example right now (and reason why I've tweeted about this feature) would be opening modules containing components in Elmish applications. Such modules have always similar structure - type defining Messages, type defining Model, init function, update function and view function. However those modules very often contains some helper types and functions. So, when using such component what I'd like to do is something like `open qualified MyComponent (Msg, Model, init, view, update)` which would give me access to `MyComponent.Model` or `MyComponent.update` but not to `MyComponent.myRandomHelper`

I guess obvious question is "Why not make only those 5 entities public and everything else private?" And my answer would be - "I still want to unit test those smaller helper functions, so they need to be public"

**Comment by baronfel** [comment]
I'd second @Krzysztof-Cieslak's perspective on this. I see the feature as less of a declaration of the external contract of a module, and more as documentation of the _consumed_ contract of the so-annotated module.  These declarations can be used to audit/enforce cycles, provide a place for comments/documentation as to why certain modules are included, and only incidentally serve any tooling purpose.

**Comment by cartermp** [comment]
Tagging @dsyme explicitly as per twitter conversation

**Comment by dsyme** [comment]
I'll reopen the issue for people to noodle on a design

**Comment by rmunn** [comment]
Nearly five years after the original request, I've discovered a use case where this might be important. https://stackoverflow.com/a/41094189/ has all the details, but here's a short example. What's the difference between these two snippets?

```fsharp
let someFunc (lst : List<int>) = lst.[10000]
```

```fsharp
open System.Collections.Generic
let someFunc (lst : List<int>) = lst.[10000]
```

Answer: the first one defines a `someFunc` that takes an F# list, which has O(N) indexing, so looking up the 10,001st item requires running through the previous 10,000 items to find it. But once you open System.Collections.Generic, then suddenly the name `List<int>` becomes a System.Collections.Generic.List a.k.a. a ResizeArray, so `someFunc` runs in constant time.

Now, this is a somewhat contrived example because any calls to someFunc in the code would probably be passing it an F# list, and would then fail with a type error once the `open System.Collections.Generic` line was added. But in theory, this is an example of code that *changes behavior* when you open a namespace (which you may have done because you wanted to get at the IDictionary interface elsewhere in the code). And I can easily imagine someone being surprised and upset at their code refusing to compile because of type errors in `someFunc`, and not knowing that they should have written `someFunc` as taking a `list<iint>` instead of a `List<int>` in order to be safe against opening System.Collections.Generic.

**Comment by abelbraaksma** [comment]
> and not knowing that they should have written someFunc as taking a list<int> instead of a List<int> 

Or more idiomatic, `int list`.

I've seen this situation a lot on old code bases, and similar things can happen with `Map`. Also, if you need both generic BCL list and F# list, you'll need to either fully specify, or use a type alias.

It can also happen if you, say, reorder the open statements alphabetically. What was shadowed in one way, now gets shadowed the other way, leading to compile errors.

**Comment by samueleaton** [comment]
Hey 👋  As a new learner of F# who doesn't use an IDE or Language Server (LSP), I find it difficult to understand code without explicit imports or aliases. I assume most F# devs need to rely on an IDE to make sense where types can from.

I resonate with the JavaScript example above `import { myLogger, Alligator } from 'app.js';` since _it treats the file like a static function with explicit inputs_.

Exploding an import via an `open X` doesn't seem very "functional" to me (lots of side effects). 

Example, I would love to be able to do `open Microsoft.AspNetCore.Hosting as AspHost` which just aliases `AspHost` to the fully qualified `Microsoft.AspNetCore.Hosting`.

**Comment by Tarmil** [comment]
> Example, I would love to be able to do `open Microsoft.AspNetCore.Hosting as AspHost` which just aliases `AspHost` to the fully qualified `Microsoft.AspNetCore.Hosting`.

You can actually do this with modules using `module Foo = Something.Very.Long`, but not with namespaces such as `Microsoft.AspNetCore.Hosting`.

**Comment by cartermp** [comment]
I would say that from a syntax perspective, `open MyModule (func1, func2)` seems the best to me because it doesn't require an additional keyword and doesn't require re-using an existing one that has a different meaning elsewhere.

Any symbol representing an entity (function, module, type, subnamespace) would then be available without further qualification, but no other entity would be available.

Straightforward F# example with modules:

```fsharp
module M =
	type Boof() = class end
    let f x = x
    module N =
        let f x = x

open M (Boof, N)

f 12 // Error
M.f 12 // ok
N.f 12 // ok
Boof() // ok
```

Straightforward example from a `System.*` namespace:

```fsharp
open System (Console)

String.IsNullOrWhiteSpace(null) // error
Console.WriteLine("hello") // ok

```

There are some additional considerations that come to my mind:

1. Do types need to be fully qualified in the list?

```fsharp
open System.Collections.Generic (System.Collections.Generic.List)
```

If not, what are the entities in the `()` scoped to, the `open` declaration they are a part of? Probably yes, but it would need answering.

2. What is the syntax for generic types? Is there any?

```fsharp
open System.Collections.Generic (System.Collections.Generic.List)
```

vs.

```fsharp
open System.Collections.Generic (System.Collections.Generic.List<_>)
```

or

```fsharp
open System.Collections.Generic (System.Collections.Generic.List<'T>)
```

What would `'T` be in this case?

3. Should you be able to restrict by generic instantiation?

```fsharp
open System.Collections.Generic (List<int>)

// Access to List<int> and only List<int>
let x = List<int>() // ok
let x = List<string>() // error
let x = List<_>() // ?? - warning saying it will always be int?
```

Today we allow opening a type at a particular generic instantiation, so why not have that option here? Speaking of opening types...

4. Can you restrict what is exposed in an `open type` declaration?

```fsharp
open type System.Math (PI)

// Only 'PI' is available now
```

This seems straightforward until you consider DUs:

```fsharp
module M =
    type BST<'T> = Empty | Node of 'T * BST<'T> *  BST<'T>

open type M.BST (Empty)

// Only access to 'Empty', which is kind of stupid
```

**Comment by Tarmil** [comment]
> 1. Do types need to be fully qualified in the list?
> 
> ```fsharp
> open System.Collections.Generic (System.Collections.Generic.List)
> ```

I would expect the identifiers in parentheses to be automatically scoped to the namespace/module being opened.

> 2. What is the syntax for generic types? Is there any?

I think `List<_>` would be the best, maybe with `List<'T>` being accepted too. `List` would be ambiguous since two types with the same name and different arity can exist in the same namespace.

> 3. Should you be able to restrict by generic instantiation?

That feels like a step too far to me.

> 4. Can you restrict what is exposed in an `open type` declaration?

Yeah I think `open type` should behave like `open` in every way that makes sense, and this is one.

> Only access to 'Empty', which is kind of stupid

I suppose it is, but it's the kind of "obviously nonsense" stuff that I can't really imagine would trip up anyone. So I see no reason to forbid it.

**Comment by MecuSorin** [comment]
Interesting proposition.

Facing a similar issue in my project, where I have multiple state machines that are updated by convention by a function "update", and have Model and Msg (and others, in a similar fashion to the Elmish modeling). I adopted the convention to use the RequireQualifiedAccessAttribute for all modules to have a clear/safe scope. This suggestion will not solve my issue, but will sweeten the pill by using the aliases

I suggest this syntax:
```open MyModule <enumeration>``` meaning that the items from MyModule can be used with ```MyModule.func1```
```open MyModule <enumeration> MyModule_Alias``` meaning that the items "imported" can be used with ```MyModule_Alias.func1```
Or ```open MyModule_Alias: MyModule <enumeration>``` meaning that the items "imported" can be used with ```MyModule_Alias.func1```

About enumeration: we should chose something familiar. Many choices here:
 - Either borrow the js syntax ```{ func1, func2 }```  - In my opinion this is the best
 - Use F# list syntax ```[ func1; func2 ]```
 - Use F# tuple syntax ```( func1, func2 )```

About the import everything but hide something, I suggest an unary operator ```-``` in a syntax similar to
```open MyModule -{ func1 }``` meaning import everything but func1 from MyModule

About the qualification of items in the ```<enumeration>```, I would not support redundant info meaning that
```open System { System.Console }``` should throw an error "Do you mean Console declared in the System". The correct way to import System.Console to be ```open System { Console }```

**Comment by rmunn** [comment]
I like the suggestion of aliases, but I don't like the syntax `open MyModule <enumeration> MyModule_Alias`. I would want the keyword `as` in there to mark an alias: `open MyModule as MyModule_Alias` and/or `open MyModule <enumeration> as MyModule_Alias`.

As for the syntax, the `{ ... }` syntax is used in Javascript because it's reminiscent of deferencing a few keys out of an object. (As in `let { foo } = params` where params is an object like `{ foo: "bar", x: 5 }`). And in fact, that's kind of what's going on behind the scenes in Javascript. In F#, the pattern-matching syntax for records provides a somewhat-natural syntax for pulling names out of a module or namespace. So if we take this pattern-matching example from the F# reference documentation:

```fs
let IsMatchByName record1 (name: string) =
    match record1 with
    | { MyRecord.Name = nameFound; MyRecord.ID = _; } when nameFound = name -> true
    | _ -> false
```

and apply a similar syntax to the `open` keyword, we could end up with `open Namespace with { SomeName; SomeOtherName = MyAlias } as NamespaceAlias`. The `with` then signals pattern matching, and the inside of the `{ }` is more or less standard pattern-matching syntax, with one extension: if you want to open a name and *not* alias it, then you don't need the `=` part of the pattern-matching syntax.

As for the `-`, I see how that could work, but it's very short and, IMHO, too easy to miss. I would prefer to use `not` here: even though `not` is not a keyword, it's used in the phrase `not struct` in parameter constraints, and we could also use it here:

```fs
// Instead of -{ Name }, I would prefer:
open Namespace with not { Name }
// But I think this is better:
open Namespace not with { Name }
```

This syntax avoids introducing new keywords, whereas everything else I've come up with (`open Namespace without Name`, or `exlcuding` or `except` or several other ideas) would introduce a new keyword. So `not with` would probably be best.

## Summary

Having thought about it some more, I now propose the following syntax:

```fs
// Import everything (current syntax)
open Namespace
// Import only two names
open Namespace with { Name; AnotherName }
// Import everything *except* two names
open Namespace not with { Name; AnotherName }
// Namespace or module alias
open Namespace as NSAlias
// Import one name without renaming, import another name as an alias
open Namespace with { Name; AnotherName = LocalAlias }
// Alias namespace and one imported name at the same time
open Namespace with { Name; AnotherName = LocalAlias } as NSAlias
```

**Comment by Happypig375** [comment]
@rmunn With #762 we will have the `without` keyword. Use it instead.

**Comment by vzarytovskii** [comment]
> @rmunn With #762 we will have the `without` keyword. Use it instead.

'with-' was approved as keyword.

**Comment by Happypig375** [comment]
Oh: https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1072-without-anonymous-records.md

**Comment by rmunn** [comment]
@vzarytovskii - Ugh, `with-` is ugly. That's about the worst choice possible. I understand not wanting to introduce new keywords, as I was bending over backwards not to do so myself, but yikes. Well, if `with-` is settled on, then it's what should be used here too, but yikes. (Wait, I said "yikes" already. Well, that just goes to show how ugly I think that choice is.)

**Comment by Krzysztof-Cieslak** [comment]
My controversial opinion here is that there shouldn't be `without` case for this feature.

**Comment by Tarmil** [comment]
@Krzysztof-Cieslak Why not? In Haskell it's common to use `hiding` to avoid ambiguities when two imported modules contain functions with the same name. In F# we rely on the order of `open`s, which I've always found pretty fragile.

**Comment by MecuSorin** [comment]
Please don't put "with", cannot be cleaner than:

```
open [MyModule_Alias:] MyModule [-]<enumeration>
```
Legend: ```[]``` means optional feature

Where ```:``` already is introduced in the language as ```having the type``` | ```bonded to``` | ```containing the thing```
The ```-``` not being visible enough is not … , just for curiosity: There is someone here that is missing other ```-``` in the code because are too short? In real usage will be easy to understand what is available and what is not when reviewing or writing the code in some file.

@Krzysztof-Cieslak Can you give a glimpse on "Why" you have that opinion for excluding specific types from import?
I have my own concerns about the complexity of implementation regarding the ```AutoOpen```, type extensions (with the needed opens, for the tooling to proper work) and ```RequireQualifiedAccess```

I'm secretly hoping that this feature will help me alias a type inside embedded modules with RequireQualifiedAccess attribute decorations by using something like:
```
open M12: ThisIsRequireQualifiedAccessModule1.ThisIsRequireQualifiedAccessModule2

M12.comeToPapa ":)"
```

**Comment by dsyme** [comment]
Closing this out in favour of #309, we can discuss there
