### ISSUE TITLE
Making Votes Count

### ISSUE THREAD

**Issue by sirinath** [fsharp/fslang-suggestions#497]
# Making Votes Count

I propose implement the higher voted features also with special attention to [100+ votes](https://github.com/fsharp/fslang-suggestions/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20-label%3Avotes%3A0-10%20-label%3Avotes%3A11-50%20-label%3Avotes%3A51-100). If voting has little bearing then there is no point of even collecting suggestions as suggested by many [low voted features are approved](https://github.com/fsharp/fslang-suggestions/issues?q=is%3Aissue+label%3Avotes%3A0-10+is%3Aopen) but [highly voted features are not](https://github.com/fsharp/fslang-suggestions/issues?utf8=%E2%9C%93&q=is%3Aissue%20-label%3Avotes%3A0-10). Most of the approved in principle suggestions have the lowers votes from the community than many [of the closed suggestions](https://github.com/fsharp/fslang-suggestions/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20-label%3Avotes%3A0-10). Even if a closed feature attracts votes then it should be reconsidered for implementation and should be open, either is the same form or an improved or alternative form. 

Also when considering features instead of the impact of one feature what should be considered is the transitive impact. E.g. if a language feature many be used to improve a library targeting the 99% of users of which only 1% of the contributor may master and use then it should be considered as impacting 99% than 0.01%. In Java case good example is Usafe. Very few use it but the libraries build are used widely hence transitively widely used. So any advance feature only a few power users may use is still justified and libraries build by them will be used by many. Some of the closed features and highly voted but not yet accepted suggestion may fall into this category hence need to be reconsidered.

Ultimately what is needed is to make the votes count in improving the language.

## Pros and Cons 

The advantages of making this adjustment to F# are that features the user community cares about get incorporated into the language.

The disadvantages of making this adjustment to F# are the features may not be the easiest to implement.

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by cloudRoutine** [comment]
What do you mean by "resources"? Where are they supposed to be added? Who do you expect to add them?

>  If voting has little bearing then there is no point of even collecting suggestions.

The fact that we're on github instead of Uservoice shows that sometimes voting does have an impact 😉

**Comment by sirinath** [comment]
>  little bearing

does not mean **no bearing**. But there is an undue bias, as I feel, from who the suggestion is coming from an perhaps maybe how easy it is than the votes.

**Comment by dsyme** [comment]
@sirinath The decisions about moving things to "approved in principle" (and thus RFC stage) are up to me. The votes are just used as an indicator. A huge range of factors go into the decision to "approve in principle", including

* estimated utility 
* estimated cost of implementing
* completeness of proposed design (is this an "idea" or a concrete suggestion)
* availability of alterenatives
* education/learning
* does this give multiple ways to achieve the same thing
* votes
* design coherence
* "less is more" design considerations
* likelihood of breaking change
* strategic importance
* usefulness (or otherwise) for interop with .NET and other languages
* risk of churn w.r.t. bugs
* cost of churn w.r.t. education materials (new editions of books etc.)
* is someone stepping up to the plate to write an RFC, implement the change and own it long term?

Also we have a large queue of relatively small-cost "approved in principle" items, and large (and occasionally growing) number of bugs/issues in http://github.com/Microsoft/visualfsharp.  In my eyes getting through these is also a priority.

Probably the best thing you can do to get a feature promoted is to draft an RFC on it, even if it has not yet been marked "approved".  A prototype implementation to high quality, with testing, would also help convince.

**Comment by dsyme** [comment]
I'm closing this. Votes do "count", in the context of the above decision making framework.

**Comment by cloudRoutine** [comment]
@dsyme it might be useful to add that list or something similar to it to the readme so everyone has an understanding of how the process works.

**Comment by dsyme** [comment]
@cloudRoutine Will do, good idea, thanks
