### ISSUE TITLE
Internal serialization of Async<_> should be fixed.

### ISSUE THREAD

**Issue by Thorium** [fsharp/fslang-suggestions#499]
# Internal serialization of Async<_> should be fixed.

I propose we modify the way `Async<_>` is serialized. Easiest would be just serialize to `Task<_>`.

The existing way of approaching this problem in F# is that if you serialize `Async<>` item, e.g. save it to memory `IDictionary<,_>` it won't warn you but it will fail at runtime producing unexpected result. However current .NET "standard way" of Task<_> (the corresponding C# implementation) works.

## Pros and Cons 

The advantages of making this adjustment to F# are e.g. that concurrent memoization would work as expected.

The disadvantages of making this adjustment to F# are unknown.

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): L?

Related suggestions: https://github.com/fsharp/fslang-suggestions/issues/494

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to the F# language design: It modifies runtime behaviour.
* [x] I would be willing to help test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
@Thorium I looked at your snippet and TBH I don't really know what you mean by "serialize".  It seems you are putting tasks in a dictionary.  If you want to put asyncs in a dictionary for the purposes of memoization, then you would need to start them first - that's just how F# asyncs work (you must start them). Using Async.StartAsTask to start them is fine - there are other choices such as AsyncResultCell https://github.com/SuaveIO/suave/blob/master/src/Suave/Utils/AsyncResultCell.fs

SO it looks to me that this is either a question about how asyncs work, or expected behaviour.

**Comment by dsyme** [comment]
Closing as this isn't yet a well-formed suggestion
