### ISSUE TITLE
Shorthand notations for the if expressions 

### ISSUE THREAD

**Issue by financial-engineer** [fsharp/fslang-suggestions#519]
# Shorthand notations for the if expressions 

I suggest adding shorthand notations for the if expressions in order to make code more succinct and elegant. 
The ordinary syntax for the if expressions is good in instances in which the then, elif, else branches contains large code blocks, while shorthand notations would be especially useful for the if expressions containing one or two lines of code within the then, elif, else branches.
The below-mentioned shorthand notations are not designed to repeal and replace the ordinary if ... then ... elif ... else ... syntax; they only allow language users to have alternatives for expressing their ideas in code. 

## 1. Shorthand notation from Cryptol
When chaining if...then...else expressions together, a language user can use the | symbol instead of the else if, elif keywords; they are equivalent.
```
// SHA-1 hash function implementation snippet
if 0 <= t  && t <= 19 then (x &&& y) ^^^ (~~~x &&& z)
|  20 <= t && t <= 39 then x ^^^ y ^^^ z
|  40 <= t && t <= 59 then (x &&& y) ^^^ (x &&& z) ^^^ (y &&& z)
|  60 <= t && t <= 79 then x ^^^ y ^^^ z
else raise (InvalidOperationException("t is out of range")
```
This implementation unambiguously captures both the English description and the  
[mathematical specification](http://www.cryptol.net/images/SHA1.png).

## 2. Additional shorthand notation (combining the suggested if syntax and the existing match syntax)
A language user can use the | symbol instead of the else if, elif keywords (like in Cryptol), the -> symbols instead of the then keyword, the | _ -> instead of the else keyword (like in the F# match expressions).
```
if 0 <= t  && t <= 19 -> (x &&& y) ^^^ (~~~x &&& z)
|  20 <= t && t <= 39 -> x ^^^ y ^^^ z
|  40 <= t && t <= 59 -> (x &&& y) ^^^ (x &&& z) ^^^ (y &&& z)
|  60 <= t && t <= 79 -> x ^^^ y ^^^ z
| _ -> raise (InvalidOperationException("t is out of range")
```
As to the | symbol within the first branch of the if expression, I believe it's a good idea if the first | symbol is non-mandatory (just like the first | symbol in match expressions), so language users would be allowed to write:

## 3. Shorthand notation (partially motivated by the Haskell syntax and vasily-kirichenko's comment)
The | symbol in the first branch of the if expression is non-mandatory (like in the first branch of the F# match expression). So, language users can write:
```
// like in Haskell, with the | symbol in the first branch of the if expression
if | 0 <= t  && t <= 19 -> ...
   | 20 <= t && t <= 39 -> ...
   | 40 <= t && t <= 59 -> ...
   | 60 <= t && t <= 79 -> ...
   | _ -> ...
```  
or
```
if 0 <= t  && t <= 19 -> ...
|  20 <= t && t <= 39 -> ...
|  40 <= t && t <= 59 -> ...
|  60 <= t && t <= 79 -> ...
| _ -> ...
```

## Existing way of approaching this problem
The existing way of approaching this problem in F# is to use the if ... then ... elif ... else ... syntax.

## Pros and Cons 

The advantages of making this adjustment to F# are 
-  more succinct and elegant if expressions, especially in instances in which they contain one or two lines of code within the then, elif, else branches.

The disadvantages of making this adjustment to F# are 
- language users have to learn new shorthand notations for the if expressions
- (added by Don Syme) there are even more ways of doing the same thing
- (added by Don Syme) no widely used language supports this version of conditional syntax

## Extra information

A shorthand notation for the if expressions exists in Cryptol, a programming language for cryptography used by NSA and some U.S. aerospace and defense contractors.

Estimated cost (XS, S, M, L, XL, XXL): M?

Related suggestions: no

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped").

Please tick all that apply:
* [x] This is not a breaking change to the F# language design. It does not affect existing codebases.
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

## P.S. 
I am strongly in favor of introducing a shorthand notation from Cryptol to F#, but if you allow to add it along with the additional shorthand notations (sections 2 and 3), it will be great.

**Comment by matthid** [comment]
Why don't you use match for these kind of use cases?

**Comment by financial-engineer** [comment]
> Why don't you use match for these kind of use cases?

because you have to start almost each branch of the match with the words no one wants or needs ("_ when ...") while you can get down to business right away in the new syntax:
```
// Existing syntax
match t with
| _ when  0 <= t && t <= 19 -> ...
| _ when 20 <= t && t <= 39 -> ...
| _ when 40 <= t && t <= 59 -> ...
| _ when 60 <= t && t <= 79 -> ...
| _ ->
``` 
instead of
```
// New syntax 
if  0 <= t && t <= 19 -> ...
|  20 <= t && t <= 39 -> ...
|  40 <= t && t <= 59 -> ...
|  60 <= t && t <= 79 -> ...
| _ ->
``` 
or
```
// New syntax from Cryptol
if  0 <= t && t <= 19 then ...
|  20 <= t && t <= 39 then ...
|  40 <= t && t <= 59 then ...
|  60 <= t && t <= 79 then ...
else ...
```
I think new short-hand notations in the language never bothers anyone; they only allow anyone to have alternatives for expressing her/his ideas in code.

**Comment by dsyme** [comment]
> I think new short-hand notations in the language never bothers anyone; 

Well, they increase the cost to learn the language, And if people in your team don't know the syntax then team cooperation becomes harder.

**Comment by financial-engineer** [comment]
@dsyme 
I agree with you. I mentioned it in the disadvantages section, but I think this disadvantage is tiny, in my view. The new syntax is intuitively clear and resemble the match syntax already known to language users, so team members would have a relatively short learning curve. Please do not reject this suggestion, I think it can benefit the F# language in terms of code succinctness and elegance.

**Comment by vasily-kirichenko** [comment]
Haskell has `MultiWayIf` extension:
```haskell
if | guard1 -> expr1
   | ...
   | guardN -> exprN
   | otherwise -> ...
```
I like it more than the proposed syntax. It looks like the following pattern match, but noise free:
```fsharp
function
| _ when guard1 -> expr1
| ...
| _ when guardN -> exprN
| _  -> ...
```

**Comment by financial-engineer** [comment]
@vasily-kirichenko 
but Haskell syntax contains a new keyword (`otherwise`), while I suggest using no new keywords, but the idiomatic to F# syntax (`| _ ->`) instead. I think the idiomatic to F# syntax in new suggestions is better and intuitively clear for existing language users.

As to `function | _ when ... syntax`, in my opinion, it has a drawback I mentioned earlier:
> you have to start almost each branch with **the words no one wants or needs ("_ when ...")**, while you can get down to business right away in the new syntax

I think the DRY (Don't Repeat Yourself in code) principle is a good principle of coding.

As to the `|` symbol within the first branch of the if expression, I believe it's a good idea if the first `|` symbol is non-mandatory (just like the first `|` symbol in match expressions), so language users would be allowed to write:
```
if | guard1 -> expr1
   | ...
   | guardN -> exprN
   ...
```
or 
```
if guard1 -> expr1
| ...
| guardN -> exprN
...
```
if they are willing to write so.

**Comment by matthid** [comment]
Active Patterns can help here as well (Between(min, max))...

**Comment by financial-engineer** [comment]
@matthid 
Of course, active patterns can help if a problem requires it, if your code has to solve a recurrent, complex problem. But you don't need a musket to shoot a butterfly. I suggest to use the new shorthand notations for the if expressions to tackle a relatively easy, one-time-only problem, when the existing syntax for the if and match expressions looks a bit verbose and heavyweight, only to make code more clear and lightweight.

**Comment by Rickasaurus** [comment]
I don't think this could work with Active Patterns as it's just the when clauses? To me this seems like a pretty rigid construct and doesn't add very much.

**Comment by smoothdeveloper** [comment]
@financial-engineer 

> but Haskell syntax contains a new keyword (`otherwise`)

As far as I know `otherwise` in haskell is just a convention and binds to a normal symbol, you can use the same convention in F# `match`/`function`.

@vasily-kirichenko I didn't know about that syntax extension in haskell, yes it looks better.

I'm overall finding the idea good, there is `match` and `function`, extending the principle to `if` would make sense if it follows the same rules wrt `|` and `->`, I would prefer not to allow the `then` and maybe we should actually call that `case` instead of `if`; It becomes a synctatical sugar similar to `function` and avoids repeating `_ when`.

That being said, even with `_ when` or `if` `elif` chains, I'm still finding the syntax better than in C# or VB.NET as of now, so I don't consider this feature to be critical.

**Comment by rmunn** [comment]
I find the similarity to `match` expressions to be a great feature of this proposal. Don Syme is quite right to worry about the extra learning cost, but I think that the proposed `|` and `->` syntax will actually *reduce* the learning cost for F# newbies, if they read a tutorial that introduces things in the right order. First they could be taught that `if ... then ... else` is an expression, not a statement. Then they could be shown an `if ... elif ... elif ... else` chain, which will feel familiar. Then they can be shown the `|` and `->` syntax for that same `elif` chain, and see that 1) it's syntactic sugar for `if ... elif`, and 2) testing proceeds from top to bottom. Then once they learn the syntax for the `match` expression, its syntax will look very familiar and they'll have (I believe) an easier time grokking it: they'll already be familiar with the `|` and `->` syntax, and the only new concept for them in `match` expressions will then be pattern-matching.

So because I think that this will actually *decrease* the learning cost for F# newbies (and I like the syntax), I've voted :+1: on this proposal.

**Comment by financial-engineer** [comment]
@dsyme 
I  agree completely with rmunn's comment and think that the suggested syntax will _decrease_ the learning cost for both F# newbies and seasoned developers. 
It's not something radically new; the suggested syntax is based on existing language resources: it extends the area of usage for the | and -> symbols that exist in F# right from the beginning. The syntax is suggested for situations when the existing syntax for the if expressions looks a bit verbose and heavyweight, namely for tackling the problems that can be solved in two or five lines of code. The goal of the suggested syntax is to make code more clear and elegant _in these situations_, rather than replace the existing if or match syntax. I think it can be a useful addition to the language. Please give it a chance

**Comment by cartermp** [comment]
This idea has grown on me.  I think it helps clarify that `if..then..else` is an expression rather than a statement, especially given the use if `|` and `->` in pattern matching, which is used everywhere.  I could easily see this being an outright replacement for `if..then..else` in terms of usage.  To that end, I think this is very similar in spirit to expression-bodied members in C# 6, which were a bit strange initially, but were quickly embraced by people as a default way of handling simple methods which just return something.

**Comment by TIHan** [comment]
Adding something like this to F# means that there are multiple ways to do the same thing.

**Comment by rmunn** [comment]
There are *already* multiple ways to do the same thing:

```fsharp
if x < 5 then "Small"
elif x < 10 then "Big"
elif x < 15 then "Huge"
else "Titanic"

// Or...

match x with
| n when n < 5 -> "Small"
| n when n < 10 -> "Medium"
| n when n < 15 -> "Huge"
| _ -> "Titanic"
```

I don't think that adding syntax sugar for the `if...elif...elif...else` chain will add significantly to anyone's cognitive load, and it's *certainly* nicer than that ugly `match` statement.

Actually, F# is *full* of multiple ways to do the same thing. For example, here are two different ways to filter a list of tuples:

```fsharp
let data = [ "a",1 ; "b",2 ; "c",3 ; "d",4 ; "e",5 ]

let pred (str,num) = num > 2
data |> List.filter pred

// Or...

let flip f a b = f b a
data |> List.filter (snd >> flip (>) 2)
```

Which one of those is easier to read? Well, that all depends on whether you understand why the `flip` in the second example was necessary. If you've already grokked that concept, then I prefer the second example's point-free style -- but if you're working with a team of people new to F#, then the first is better. And so on, and so forth.

Multiple ways to do the same thing is not a bad thing, because it lets you write your code in whatever way makes the most sense for your particular project and team.

**Comment by dsyme** [comment]
I've added the following two disadvantages to the description test:

> - there are even more ways of doing the same thing
> - no widely used language supports this version of conditional syntax

**Comment by dsyme** [comment]
Please see  [these notes](https://github.com/fsharp/fslang-suggestions#notes-on-the-design-process) where "does this give multiple ways to achieve the same thing" is listed as one of the ways of assessing suggestions.

> When chaining if...then...else expressions together, a language user can use the | symbol instead of the else if, elif keywords; they are equivalent.

I'm disinclined to give yet more ways to do the same thing just to save a couple of characters. There is also the potential for negatives w.r.t. error recovery in the parser (e.g. error recovery on `|` becomes harder if it can be used in more ways), and on suggesting completions.

**Comment by piaste** [comment]
Suggesting another option:

I come from a VB.NET background, and in that language the case labels don't need to be constant expressions like in C#. As a result, long chains of if-elseifs can _also_ be expressed as follows:

```
select case true
     case foo = String.Empty : return 1
     case bar.IsEmpty : return 2
     case SomePredicateFunction(foo) : return 3
     case someBooleanExpression, someEquivalentBooleanExpression : return 4
     case else : return -1
end select
```     

In other words, the value `true` is matched against various possible candidates, and the first matching case is executed (there is no `break` required in VB.NET).

This syntax is not idiomatic, but it's entirely legal and sometimes allows for more legible code compared to a chain of ifs.

So when I first learnt F#, at first I _expected_ (this is important) that the same trick could work in F#:

```
match true with
| (foo = String.Empty) -> 1
| bar.IsEmpty() -> 2
| SomePredicateFunction foo -> 3
| someBooleanExpression | someEquivalentBooleanExpression -> 4
| _ -> -1
```

Turns out that's not the case - while `true` is a valid candidate for pattern matching, the language doesn't allow any random expression to be a pattern.

But it _shouldn't_ be very messy to allow that syntax. Consider what is already possible:

```
let r = System.Random()

// this compiles
let x = if r.Next() = 1 then true else false

match true with
| x -> printfn "ok"

// this does NOT compile
let f () = if r.Next() = 1 then true else false

match true with
| (f()) -> printfn "ok"

// but this, again, compiles
let f' = f()

match true with
| f' -> printfn "ok"
```

So, just assign the expression to a variable and you're golden. _That_ can, in my opinion, be sugared without adding syntactic baggage: **if a pattern is wrapped in parentheses, it should be evaluated as a single expression and the candidate matched against it**.

If anything, I'd say it would follow user expectations: in pretty much every other part of the language, you can use an expression between parentheses in the same way as a pre-defined variable.

Also, on second thought, it's not *just* sugaring, since pre-assigning the variable forces the evaluation of every pattern. With expression patterns, you could have lazy evaluation. Consider this possibility (which also shows that it wouldn't be limited to boolean candidates):

```
match HttpResult.OK with
| (CheckMainServer req) -> "The resource exists on the main server"
| (CheckAlternateServer req) -> "The resource exists on the alternate server"
| (CheckBackupServer req) -> "The resource exists on the backup server"
| _ -> "The resource is not available"
```

**Comment by theprash** [comment]
@piaste, As you've implied, there has to be a separation between where value expressions and pattern expressions, and I don't think parentheses are enough syntax to switch a pattern to a value. They are used only for grouping everywhere else and this would be an exception. Patterns in existing code may already be wrapped in unnecessary parens so that would be a breaking change. And some patterns need to be wrapped in parens: `let f (Some x) = x`

I was going to say that parameterised active patterns can help here but I found they don't quite behave how I expected!

Take this active pattern:

```fsharp
let (|Eq|_|) x y = if x = y then Some() else None
```

These two match expressions both work as expected:

```fsharp
match a with
| Eq 2 -> "a is 2"
| Eq 3 -> "a is 3"

let two = 2
match a with
| Eq two -> "a is 2"
| Eq 3 -> "a is 3"
```

But this fails to compile with `FS0010: Unexpected infix operator in pattern. Expected ')' or other token.`

```fsharp
match a with
| Eq (1 + 1) -> "a is 2"
| Eq 3 -> "a is 3"
```

And this fails to compile with `FS0073: internal error: impossible (Failure)`

```fsharp
match true with
| Eq (a = 2) -> "a is 2"
| Eq (a = 3) -> "a is 3"
```

I assumed that active pattern parameters were arbitrary expressions (and only evaluated after the previous match case failed), but apparently not. I don't know if there is an important reason for this, or if it's something that could be implemented. It would make this `Eq` active pattern much more useful!

**Comment by TIHan** [comment]
@rmunn F# does have a lot of ways to accomplish the same goal. That is all the more reason we need to be conservative on what gets added or changed.

Less characters doesn't always mean it's more readable, especially if the meaning of certain characters and/or keywords change depending on how they are used.

**Comment by yawaramin** [comment]
Re: https://github.com/fsharp/fslang-suggestions/issues/519#issuecomment-261827016

I've (with help from Tomas Petricek, see http://stackoverflow.com/a/40786982/20371) implemented the List-style `cond` function. It looks like this:

```fsharp
let x = 11
    let actual =
      Cond.cond (None : int option)
        <@@ [ x < 5, Some -1
              x < 10, Some 0
              x < 15, Some 1 ] @@>
```

Obviously, there's some 'fixed cost' to using it, but the more conditions you have, I think the more it pays for itself in brevity.

Repo at https://github.com/yawaramin/fsharp-cond

**Comment by cloudRoutine** [comment]
@yawaramin  does it really need to be that complex?

```fsharp
let multIf (conds:(bool*'b) list) (lastResort:'b)=    
    let rec loop (eval,result) ls = 
        if eval = true then result else
        match ls with 
        | hd::tl -> loop hd tl 
        | [] -> lastResort
    if conds = [] then lastResort else 
    loop (List.head conds) (List.tail conds) 
```
```fsharp
let check_num x = 
    multIf [
        x < 5 , -1
        x < 10,  0
        x < 15,  1
    ]   100 

>check_num 4;;
val it : int = -1
>check_num 6;;
val it : int = 0
>check_num 14;;
val it : int = 1
>check_num 20;;
val it : int = 100
```

**Comment by radekm** [comment]
@cloudRoutine This won't work with side effects (side effects from all branches will be evaluated before `multIf` is evaluated).

**Comment by chojrak11** [comment]
@financial-engineer @dsyme 
Would that be the solution to make the pattern and `when` keyword optional? Can the parser distinguish between a pattern and a condition?

```fsharp
// Existing syntax
match t with
| _ when  0 <= t && t <= 19 -> ...
| _ when 20 <= t && t <= 39 -> ...
| _ when 40 <= t && t <= 59 -> ...
| _ when 60 <= t && t <= 79 -> ...
| _ ->
```

I mean this example:
```fsharp
// New syntax
match t with
|  0 <= t && t <= 19 -> ...
| 20 <= t && t <= 39 -> ...
| 40 <= t && t <= 59 -> ...
| 60 <= t && t <= 79 -> ...
| _ ->
```
and this spec:
```fsharp
// Match expression.
match test-expression with
| pattern1 [ when condition1 ] -> result-expression1
| condition2 -> result-expression2    // new syntax
| ...
```

**Comment by dsyme** [comment]
@chojrak11 That syntax would, I think, be too ambiguous

**Comment by dsyme** [comment]
I'm not inclined towards any of the syntax additions suggested so far.  I could vaguely imagine some variation on the suggestion of @chojrak11 where there are simply no inputs to the match, e.g. 

```
// Existing syntax
match with
| 0 <= t && t <= 19 -> ...
| 20 <= t && t <= 39 -> ...
| 40 <= t && t <= 59 -> ...
| 60 <= t && t <= 79 -> ...
| _ ->
```

The reason is that this more obviously a degenerate version of the existing ``match`` which lets you elide the ``_ when``

But my instinct is still against this.  Comments?

**Comment by smoothdeveloper** [comment]
Unless the suggestions gets lots more voters, I'm still fine with cascade of if/elif/else or match/with/when.

If we'd decide to support this, as @vasily-kirichenko shown, we should replicate haskell syntax.

**Comment by kspeakman** [comment]
I have found myself a few times really wishing for terser `if` syntax for one-liners, but rarely find myself using `elif ... then` syntax. Maybe it's just the nature of the apps I work on.

Empirically, the proposed syntax saves about 3 keystrokes / 5 characters per `elif` line.
```fsharp
elif ... then ...
// overhead = 8 keystrokes, 8 characters
| ... -> ...
// overhead = 5 keystrokes with shift, 3 characters
```

For one-liners it is more economical to use standard syntax.
```fsharp
if ... then ... else ...
// overhead = 10 keystrokes, 10 chars
if ... -> ... | _ -> ...
// overhead = 14 keystrokes, 10 chars, includes inner spaces on _ match
```

I too think that casual readers of F# code would have a harder time understanding the symbols `|` and `->` over the words `if`/`elif` and `then`. Extending the match syntax to support this does seem like the most appropriate way forward, since the cognitive burden of learning these symbols is intrinsic to learning the match statement.

But the keystroke overhead of typing `match with` at the top means you need several cases to break even versus just using `if`/`elif`. So the specific benefit would be to devs who are otherwise writing 4 or more `elif` branches.

**Comment by ReedCopsey** [comment]
@dsyme Any reason you need the `with` in there?  I really like:

```fsharp
match 
| 0 <= t && t <= 19 -> ...
| 20 <= t && t <= 39 -> ...```
```

Just from a "reading the code in my head" standpoint, I typically read it as "match _someExpression with_ ..." and, in this case, saying "match when t < 20" reads pretty cleanly to me, as the "with" seems more tied to the expression than the patterns.  This makes it seem more in line with the syntax of a pattern matching function.

The main advantage I see to this is it is a lot easier to follow the logic when you have many cases.  The alignment of the test cases "just works", so you end up with something more understandable than if/elif/else.  I don't think I'd ever use it for a one liner, but with many patterns, I think this would be really nice.

**Comment by dsyme** [comment]
@ReedCopsey That's feasible.

**Comment by dsyme** [comment]
Closing this as its use cases are too rare to justify having an additional construct in the language for all F# programmers to learn and all tooling to support.
