### ISSUE TITLE
Partial application should have "closure" for mutable parameter

### ISSUE THREAD

**Issue by LincolnYang1** [fsharp/fslang-suggestions#565]
Partial application can't work with mutable parameter

it seems partial application doesn't have "closure", if I use mutable variable as parameter to build partial application, it seems it will make a copy of this parameter and as "immutable".  this is very misleading sometime, especial if not use partial application, just add full parameter, in case below case 1 and case 2 only have 1 parameter difference, it will have a big different behavior

let add a b = a + b
let mutable mutVal1 = 1

// case 1. partial application
let addMutVal1_partial = add mutVal1

printf "mutVal1 = 1, mutVal1+100=%d" (addMutVal1_partial 100)
mutVal1 <- 1000

printf "it should equals to 1001, but partial application doesn't use 'closure' to capture in runtime \r\n" 
printf "mutVal1 = 1000, mutVal1+100=%d" (addMutVal1_partial 100)

// case 2. no partial application, correct behavior
printf "\r\n  no partial application, correct behavior\r\n"
mutVal1 <- 1
let addMutVal1_no_partial b = add mutVal1 b

printf "mutVal1 = 1, mutVal1+100=%d" (addMutVal1_no_partial 100)
mutVal1 <- 1000
printf "mutVal1 = 1000, mutVal1+100=%d" (addMutVal1_no_partial 100)

Suggestion, 
when build partial application with mutable variables, it should use "closure" to capture the variables in run time.

## Pros  
when most of the people read code below, they might not realize the case A and case B have very big difference, only because of "mutableVariable" is mutable. 
let's see this issue in other way, if for every partial application, developer need to check if there is mutable variable in, there are lots of extra work and burden.

let add a b = a+b
//case A
let addM = add mutableVariable
//case B
let addM b = add mutableVariable b

Please add "closure" feature to partial application if there is mutable parameter

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: (put links to reated suggestions here)

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
@LincolnYang1 This is by design.  If you want to pass a mutable thing around as a first class value, use a ref cell?

**Comment by matthid** [comment]
I assume it is in the philosophy of the language to not support that for several reasons:
 - Mutable values are explicitely marked throughout the language
 - Assignments and changes have special syntax

Your suggestion breaks this for two reasons:

```
mutVal1 <- 1000

printf "it should equals to 1001, but partial application doesn't use 'closure' to capture in runtime \r\n"
printf "mutVal1 = 1000, mutVal1+100=%d" (addMutVal1_partial 100)
```

 - You didn't mentioned `mutVal1` anywhere in the line so why should `addMutVal1_partial` now be something different than before? In a langauge where everything is immutable by default until written otherwise this doesn't make any sense.
 - Consider the `let addMutVal1_partial = add mutVal1`  (1) you did not mention anywhere that you want to keep it mutable. When writing `add mutVal1 b` you invoke a function and your arguments are bound to it and they stop beeing mutable within the function. When writing (1) you are applying the parameter early so the same happens as when you are calling the function, just earlier (a copy is made). And now consider your last code "`let addMutVal1_no_partial b = add mutVal1 b`" basically the same happens as written above, just at another time and within another function.

The workaround by using `ref` cells makes sense to me.

What I don't like about this is that 

`let addMutVal1_partial = add mutVal1` and `let addMutVal1_partial = fun p -> add mutVal1 p` are not the same, even when partial application is often explained like this ...

Hope that makes sense and I hope it's the correct reasoning for this. But at one point I agree. It's really a tough call to make ...

**Comment by dsyme** [comment]
> ... are not the same, even when partial application is often explained like this ...

Wekk, these are definitely different:

    add x
    fun p -> add x y

and the difference should at some point be explained.  For two reasons 
1. the arguments are evaluated (including reading mutable values, reading properties, reading fields, reading array entries etc.) 
2. in the first case the function is applied to the first argument, in the second the application is delayed until ``p`` is received

**Comment by LincolnYang1** [comment]
since the mutable parameters in partial application is early bind, once bind after mutable value changed, partial application still point to its old value. it is definitely a error-prone.
my suggestion is, for "mutable variable" used in partial application, please give a compilation warning to point the potential risk.
