### ISSUE TITLE
Allow backslash '\' as an operator

### ISSUE THREAD

**Issue by Richiban** [fsharp/fslang-suggestions#574]
# Allow backslash '\\' as an operator

**I propose we** allow the backslash character as an operator

As far as I can tell the backslash character does nothing in F# source code (unless it's used inside a string in which case it becomes the escape character). Why not allow it as an operator?

It would be very useful as, say, an integer division operator for floats:

```fsharp
let one : int = 2.0 \ 1.0
```

or as an even better pipe operator! (I think this looks great:)

```fsharp
let f() = "Hello world" \ reverse \ toUpper

let g() = 
    "http://example.com"
    \ Uri
    \ HttpClient.Send
```

The backslash character is sitting there doing nothing! Let's use it.

Estimated cost: XS

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by theprash** [comment]
I just want to comment that if `\` is currently reserved then we should be be completely sure we don't want to use it for some new syntax to serve one of the other language suggestions, before allowing it to be a user-defined operator. For example, there is some mention of its use in #506, although the idea was abandoned.

**Comment by rmunn** [comment]
I'm not totally against this idea, but I'm hesitant about it for the same reasons as @theprash. Also, I want to comment that I *would* be against using `\` as a substitute for λ, the way Haskell does. I've never liked that syntax, and find it confusing and unintuitive. It would, of course, appeal to Haskell users learning F#, but I think it would turn off C# people, and they are the ones we most need to reach (IMHO).

Also, a question for @Richiban. You didn't check the "This is not a breaking change" box: is that because you think it *is* a breaking change? Or is that because you skipped that part of the issue template? I notice, for example, that you also didn't check any of the first three boxes, so in theory you're saying that this is something that has obviously "already been decided" in previous versions of F#. I'm pretty sure that that's not what you meant, so I assume you just skipped checking the required boxes. I'd appreciate it if you would edit your issue and fix that, so that I can tell (among other things) whether you think this is, or is not, a breaking change in the language design.

**Comment by kspeakman** [comment]
@rmunn Not sure how `\` lambda would turn off C# users more than `fun` already does. In C# there is no keyword required to start a lambda. From that perspective defining lambdas feels like 4 wasted characters (fun and a space) versus 1 for backslash. VB users are most likely to resonate with F# `fun` since their lambdas have to start with `Function` (or `Sub`). But I think it is unlikely that F# will choose to use backslash in this way.

**Comment by Richiban** [comment]
@rmunn You're right; I actually submitted an empty issue. It seems that the Affadavit has been added after the fact (or at the point I submitted my post). I'll fill in the information accordingly so that it follows the rules!

**Comment by Richiban** [comment]
By the way, I'm curious as to whether the backslash has any meaning at all in .NET or the CLR, never mind C#. As far as I'm aware the character does nothing outside of strings in C#, F# and VB. This makes me think that it actually is reserved for something, but I can't find it.

**Comment by 21c-HK** [comment]
> Also, I want to comment that I would be against using \ as a substitute for λ, the way Haskell does. I've never liked that syntax, and find it confusing and unintuitive.

I am for using `\` instead of `fun`. There is a difference between typing 1 character and be done with it and having to type 4 characters (`fun` + space). 

The problem of syntax is that nothing is really intuitive. Whether some syntax is intuitive or confusing is mostly a function of familiarity. I once thought separating parameters and arguments by space, which is common in ML-languages, ‘unintuitive’. I also find OCaml-style (`type ('a, 'b) t = ...`) for type parameters in F# unintuitive, because I still use the .NET-style (`type t<'a, 'b> = ...`) that I was already familiar with from C#, but I still find separating suffixed lower-case type parameters by space in Haskell (`data T a b = ...`) unintuitive, but that's just because I don't program in Haskell. Scala seems more ‘intuitive’ in that regard (`class T[A, B] ...`), but only because `[A, B]` looks similar to `<'a, 'b>`.

**Comment by dsyme** [comment]
I'm pretty much against the use of ``\`` in operators.  Every language I've seen using `\` gets harder to read.

I will close this as we decided not to do this in F# 1.x for readability concerns.
