### ISSUE TITLE
Allow use of a, T... as type variable names without '

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-suggestions#582]
In F# today type variable names must begin with a tick ``'``.

From time to time people have suggested that F# should allow type variables of name ``T``, ``a`` etc. without the preceding ``'`` character.

This would include "free floating" type variables that are implicitly generalized, for example:
```
    let map (f : T -> U) (xs: T list) = ...
```

This code is arguably considerably friendlier to programmers from other languages than code that uses ``'``.

The (considerable) downside is that a special rule of some kind is required to determine if a name is a type variable or the name of a type definition.  The risk is that mis-spelled type names will be considered type variables, leading to later strange errors.  

Example possible rules are
* Don't allow this
* Always consider ``id`` to be a type variable if there is no type definition of name ``id`` in scope.  Use ``'id`` as the way to disambiguate if really needed
* The previous rule, but with a warning heuristic like, e.g. emit a warning if a name is considered to be a type variable but is long than 3 characters and doesn't begin with ``T``.  The warning would say "please add a ``'`` clarify this is a type variable."

## Pros and Cons 

The advantages of making this adjustment to F# are code that has fewer "unusual" characters.

The disadvantages of making this adjustment to F# are 
* it may be less clear what is generic and what is not
* introducing a type with a name such as ``T`` could severely mess with code.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by Pauan** [comment]
Koka has an interesting solution to this, which is that single-character names (like `A`, `T`, `a`, `b`, etc.) are *always* type variables, and multi-character names (like `list`, `Option`, etc.) are *always* types.

If you want a multi-character type variable, you can always use the `'foo` syntax, just like right now.

It's very rare for people to name a type with a single character, and in my opinion it's a bad idea anyways. So this is a pretty good solution in practice.

**Comment by theprash** [comment]
I think having a syntactic difference for type variables is a good feature of F#. To me it is simpler and clearer and has virtually no cost except for a slight initial friction for those familiar with C#/Java.

I would take this even further and say that the lack of this distinction in other languages may be a point of confusion for someone learning the concept of generics. It took me a little while to get the hang of generics in C# as I was learning about statically typed programming and I suspect it was made worse because I couldn't always tell the difference between a concrete type and a type variable.

**Comment by theprash** [comment]
@Pauan It's a common and useful to have named type variables. For example, `List.fold` has a type variable `'State`

**Comment by Pauan** [comment]
@theprash I never said otherwise. I said you can use `'State` for type variables like that.

**Comment by theprash** [comment]
@Pauan Sorry, I misread your last paragraph :)

**Comment by dsyme** [comment]
> I think having a syntactic difference for type variables is a good feature of F#. To me it is simpler and clearer and has virtually no cost except for a slight initial friction for those familiar with C#/Java.

We should be aware that statistically existing F# users are going to be ok with a rigid syntactic difference.

But I'm pretty sure some of those put off F# have been put off because of this issue.  It's hard to get a measure on how many, of course.

> I would take this even further and say that the lack of this distinction in other languages may be a point of confusion for someone learning the concept of generics. 

This is definitely possible, a good observation

**Comment by theprash** [comment]
I have a bit more to say on this. I'm not a Haskell person but I find it has very readable type signatures because it consistently follows a few rules. One is that type parameters mirror function parameters in terms of application and grouping: the parameters come after the type they are applied to, they are space separated, and parens are used for grouping if necessary, e.g. `Map a (b, c)`. Another rule is that type names start upper case and type variable names start lower case.

F# already inherits generic type syntax from both C# and OCaml, so it already has some inconsistency here. And then there's the lower case type aliases for core types so you can write either `int List` or `int list`, and there's also `int array` vs `int []`. I think it would be a mistake to introduce another special rule to the type syntax as it would be yet another wrinkle that everyone needs to learn about in order to read types. A C# developer writing F# would still frequently encounter tick-prefixed type variables when looking at inferred types or other people's code so they would experience the inconsistency too.

**Comment by cartermp** [comment]
I think there is some danger in doing this with existing code, of which there is plenty of.  Having code like this:

```fsharp
let oldF (f: 'T -> 'U) x = f x

let newF (f: T -> U) x = f x
```

Could confuse people.

However, I do think that the cleaner type signatures is a good idea, especially since it's more consistent with other functional languages.  F# always felt odd to me in that I needed to do this little ticky thing ... and you betcha, I still forget to type it out on a near-daily basis.

Unfortunately, it's nearly impossible to get any kind of data suggesting that `'` has a good or bad effect on people.  So this is going to be more a feel/taste sort of thing.  I think I'm for the change.

**Comment by dsyme** [comment]
> Unfortunately, it's nearly impossible to get any kind of data suggesting that ' has a good or bad effect on people. So this is going to be more a feel/taste sort of thing. I think I'm for the change.

One indication is that whenever I am "sketching" code and APIs I leave out the ticks... That's an indication that something is slightly odd.

**Comment by rspeele** [comment]
I recently introduced some C# developers to F# and a couple of them were noticeably perplexed when I explained that generic type parameters have a leading tick mark. The syntax is certainly foreign to devs accustomed to `'` being a character or string delimiter.

However, I think the reaction would be _much worse_ if I said "sometimes you have to use this tick mark and other times you don't", or even "you'll see this in existing F# code but you don't have to use it in your own". I think most programmers value consistency and have more respect for a language that sticks to its story (and doesn't require them to make yet another bikeshedding style decision).

I would prefer that we leave this syntax alone.

**Comment by gerardtoconnor** [comment]
I think it works in other languages due to the there being less type inference but I think it makes much more sense to "flag" generic types to make it clear what the code is trying to do.

In C#, generics have to be specified in the type parameters of the type/method, such that it makes it clear for the programmer to check and see the generic types declared and being used but in your example, there is nothing declarative showing these types are generic other than them not existing in the current type namespace(s), the programmer might waste time looking for type declarations etc. 

Non-tick type parameters would be clear if we replicate type parameters eg:
```f#
 let map<T,U> (f : T -> U) (xs: T list) = ...
```
But this is a step backwards on the already working tick prefix system, which is more lightweight than the verbose process of full type parameters on functions like we do on methods (&classes).

I would imagine if this was put through it would initially create a lot of unforeseen bugs and eat away loads of time that could be better spent improving tooling etc.

+1 for keep as is, (or alternatively allow without tick if put in type parameter consistent with c#)

**Comment by dsyme** [comment]
> I recently introduced some C# developers to F# and a couple of them were noticeably perplexed ...
> However, I think the reaction would be much worse if ..

I get what you're saying.  

However, if some variant of the proposal had been implemented in, say, F# 1.0,. then I very much doubt the topic would have come up at all in your discussion with the C# developers.  You would have used ``T`` etc., and they would have seen that, no one would have said anything, and everyone would likely have been content.

**Comment by scrwtp** [comment]
I have never met anyone who'd be "perplexed" about ticks for longer than 30 seconds. Just tell them that "generic type parameter names start with a tick instead of capital T". 

Because that is what it boils down to. In C#, people would use names like `TState` for their generic type parameters. They're already putting in their "ticks" by convention. That's what they're encouraged to do by style guides.

F# is already ahead, why take a step back?

**Comment by Rickasaurus** [comment]
We have 8 developers at SBS who came from C# to F#, and none of them had an issue with this. I very much like being able to easily identify generics and wish we could bring the F# way to C#.

The indentation rules are by far the biggest barrier. Second biggest would be understanding when type inference will and won't work (and understanding the errors generated).

**Comment by pblasucci** [comment]
I've introduced F# in a few different "C# Shops" now, and my experience is consistent with @Rickasaurus telling. Being able to distinctly identify generics _is_ really nice. And it's always a _one-time, one-sentence explanation_ to C# or VB devs.

Now, explaining generics to devs who've never worked with them? That's a whole separate issue.

**Comment by dsyme** [comment]
Closing given the feedback from @Rickasaurus and @pblasucci
