### ISSUE TITLE
Generic modules

### ISSUE THREAD

**Issue by ijsgaus** [fsharp/fslang-suggestions#593]
# Generic modules

I propose we enable generic module declaration:
`module A<T> =`

## Pros and Cons 

In static classes this is enabled as/ static members. Partial specialized generalizing algorithm can make life little easier.  Slightly cross win HKT. 

Estimated cost (XS, S, M, L, XL, XXL):  M
Can be difficult in type resolution

Related suggestions: (put links to related suggestions here)

 [* ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
 [* ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
 [?] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
 [*] This is not a breaking change to the F# language design
 [* ] I would be willing to help implement and/or test this

**Comment by rmunn** [comment]
The angle brackets in your code were interpreted as HTML and stripped out. I suggest you use ``` markers around your code next time so that the angle brackets get preserved. The Preview tab of GitHub's issue editor should help you make sure your Markdown is going to be interpreted properly. (It'll also help you get the checkboxes looking right: you should use [X] to check a checkbox in GitHub's Markdown).

**Comment by kspeakman** [comment]
Could you provide an example where you would use them? It might be in the OP, but I can not see it due to the angle bracket issue. I suspect I would not use generic modules, but I would like to see a case for them. I mostly use generics during interop with existing .NET IO libraries. Generic functions are fine for that.

I guess part of the reason is because I tried to use them before and found that generics in F# were infectious -- they eventually required me to genericize calling code due to compiler complaints. F# does not allow you to leave a "hole" in generics in the same way that type inference will generalize arguments. So I do not think you would get any closer to HKTs with this feature. But maybe I am missing something?

**Comment by Rickasaurus** [comment]
I'm struggling to see a case where just vanilla .net generics will get us anything other than maybe some boilerplate reduction at the cost of confusing users because they'd write `List<int>.fold` instead of `List.fold<int>`.

**Comment by scrwtp** [comment]
I would like to see a change going the direction of making F# modules parametrisable in some form or fashion. But I feel ultimately you'll arrive at the same conclusion that resulted in this suggestion being closed: https://github.com/fsharp/fslang-suggestions/issues/351 (i.e. no HKT in .NET would be a blocker in making this feature work).

**Comment by jack-pappas** [comment]
See also:
```
Russo, Claudio, Matt Windsor, Don Syme, Rupert Horlick, and James Clarke. "Classes for the Masses." CoALP-Ty’16 (2016): 9.
```

https://ff32.host.cs.st-andrews.ac.uk/coalpty16/proceedings.pdf#page=15

**Comment by dsyme** [comment]
I agree with @scrwtp that we would not do this unless we went further and made modules paramaterizable as in #351
