### ISSUE TITLE
Allow generic type constraints for union and record

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#62]
**Submitted by Huw Simpson on 3/4/2016 12:00:00 AM**  
**2 votes on UserVoice prior to migration**  

I suggest that the ability to express the following type constraints be added:
when 'T : union
when 'T : record
This would enable apis which use quotations or reflection over the supplied record or union to be safer.
The constraint could be enforced at runtime if unions or records implemented some sort of marker interface, perhaps there is a better way.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12804867)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12804867-allow-generic-type-constraints-for-union-and-reco.md#comments)

**Comment by dsyme** [comment]
This was considered in F# 2.0 but we decided against it then, partly because the presence of signatures makes it more difficult to consider what does/doesn't pass the constraint, and partly because there is a limitless number of constaints that could be added.  Per policy closing so as not to revisit design decisions unless there's been a significant change in circumstances
