### ISSUE TITLE
Add the flip function, as in Haskell

### ISSUE THREAD

**Issue by Soldalma** [fsharp/fslang-suggestions#620]
# Title of Suggestion

I propose we add a flip function: let flip f x y = f y x

The function is very useful when one has a long pipeline generating a value and one wants to apply a function where the two last arguments are in the "wrong" order. Without flip one would have to either define a lambda or do a let binding. With flip one can just continue with the pipeline. 

The existing way of approaching this problem in F# is: the user can define it.

## Pros and Cons 

The advantages of making this adjustment to F# are that the function is very useful for pipelines. Instead of using let to define a variable one can just use flip. For example:

let x = 4; let y = 2; let z = 3

x * y
|> flip (/)  z

Instead of 

x * y
|> (fun t -> t / z)

or

let w = x + y
w / z

The disadvantages of making this adjustment to F# are none. 

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  XS

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by vasily-kirichenko** [comment]
Please, don't. Just don't.

**Comment by realvictorprm** [comment]
Any constructive Arguments?

Am 14.11.2017 18:58 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by Soldalma** [comment]
Not clear what is meant by "Arguments" with capital "A". Please clarify. 

flip would just be a function, would not need a constructor.

**Comment by realvictorprm** [comment]
@Soldalma Sorry result of my german keyboard settings.
I meant whether there are any constructive reasons to not do this.

**Comment by dsyme** [comment]
We decided not to add this in F# 1.x and 2.x because we came to the conclusion that this and other such functions decrease code readability.

I'll close this as this decision has been made and the funciton is so easy to define if you need it

**Comment by Soldalma** [comment]
Fair enough, but just for my (admittedly beginner's) education, how do
these functions reduce readability?

**Comment by cartermp** [comment]
Just my two cents: lacking this function does give library authors a bit of an incentive to structure their functions that they intend for public consumption in a consistent way.  Although we can't wave our hands in the air and declare success here, I do generally think it's worked out well.  My own experiences with Haskell and Clojure left me doing either:

* Seemingly lots of `flip` calls in Haskell, and I ended up not really knowing what was going on in the middle of a long point-free chain
* Mixing `->` and `->>` in Clojure, because both macros existed and public APIs would seemingly optimize for the use of one macro over the other at random

**Comment by Soldalma** [comment]
Thanks. That makes sense. Perhaps I am a bit biased because the code I
write is for my own consumption.

**Comment by realvictorprm** [comment]
Thanks!

Von: Vasily Kirichenko
Gesendet: Donnerstag, 16. November 2017 17:58
An: fsharp/fslang-suggestions
Cc: Victor Peter Rouven Müller; Comment
Betreff: Re: [fsharp/fslang-suggestions] Add the flip function, as in Haskell(#620)

how do these functions reduce readability?
Directly. To understand the code, you have to flip function arguments mentally, every time.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus
