### ISSUE TITLE
Allow pre Mac OS X line endings in spec

### ISSUE THREAD

**Issue by moonPtr** [fsharp/fslang-suggestions#665]
Currently only Unix (\n) and Windows(\r\n) are allowed, and using \r only breaks F# tooling
I propose to adjust the specification to allow old mac-style line endings for compatibility sakes

**Comment by jwosty** [comment]
Sounds simple enough (feature-wise and implementation-wise). I don't see why not.

**Comment by rmunn** [comment]
I'm generally opposed to this, because if both `\r` and `\r\n` are legal line breaks (as well as `\n`), it complicates the parser. `\r\n` is hard enough to deal with already; adding another character that is a *prefix* of `\r\n` just makes it worse. It's easy to make a simple mistake in parsing order that ends up treating an `\r\n` pair as two separate linebreaks. Granted, it's not *too* hard to avoid this mistake in a parser, but it's yet another complication. So it has a cost, and that cost has to be balanced against the benefits.

And what are the benefits? Code written on Macs that ran System 9 or earlier can be passed into the parser without first running it through an `\r` → `\n` conversion step. How often do you deal with older code written on a pre-OS X Mac, especially older **F#** code written on a pre-OS X Mac? Mac OS X 10.0 was released in 2001, while F# 1.0 was released in 2005. I doubt that there will be many F# source files with `\r` in them.

So this proposal carries a small but nonzero cost, and I believe it will have zero benefit in practice. It's a nice idea, and I like it in theory, but in practice I'm opposed.

**Comment by abelbraaksma** [comment]
There's a simple enough algorithm for dealing with all these line endings and it's used by all open standards at W3C, like xml, html, xslt, css etc etc. It makes sense to be liberal in what we accept.

The algorithm is simple, unambiguous, and I hope simple to implement for this parser. It can be found, among others, in the xml spec.

**Comment by dsyme** [comment]
> So this proposal carries a small but nonzero cost, and I believe it will have zero benefit in practice. It's a nice idea, and I like it in theory, but in practice I'm opposed.

There's a definite significant cost in this sort of thing for both the compiler and all IDE tools.

**Comment by abelbraaksma** [comment]
Perhaps we should leave this to external tools, there are excellent plugins available and it wouldn't be so hard to roll out your own if you need it for a specific task. Here's one that I use: https://marketplace.visualstudio.com/items?itemName=JakubBielawa.LineEndingsUnifier
