### ISSUE TITLE
Rename AbstractClassAttribute to AbstractAttribute and add StaticAttribute

### ISSUE THREAD

**Issue by moonPtr** [fsharp/fslang-suggestions#666]
I know that AbstractClass also forces the type to be of kind class (Abstract Struct is not possible), but considering tools will already give an error when using both attributes together, I still think it's a little redundant to have "Class" in the name.

Besides, it looks awkward when using alongside `[<Sealed>]`, which together are used to make static classes,
which is why I also suggest adding a `[<Static>]` attribute.

I am aware that modules compile into static classes, but modules can't have methods, so for completeness (and possibly weird .NET interop edge cases) I still think it should be there.

**Comment by ForNeVeR** [comment]
I don't think CLI has such a thing as a "static class". `static` is purely a C# convention for an `abstract sealed` class, and that's the C# compiler who disallows these classes to have instance methods (these methods have no point anyway because the class is `sealed`).

You could combine `[<AbstractClass>]` and `[<Sealed>]` in your F# code to produce something that C#-aware tools will consider as "static class", [see example on sharplab](https://sharplab.io/#v2:DYLgZgzgPg9gDgUwHYAIDKBPCAXBBbAWACgBtAHgEEAjHAJwEMBjbAYWHoggD4BdFctAnrAEAE17FsGRChYAKAJQoAvMRTqUOetgCWjFHnxUEtFAFlFKlIrUbDeY6YD6TgHQBJJFqSMEl5dYKQA=) (note how C# decompiler shows us a `static` class with an instance method and even a public constructor: a blasphemy indeed!)

**Comment by dsyme** [comment]
Closing this as what's there is sufficient
