### ISSUE TITLE
Allow overloads of custom keywords in computation expressions

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#69]
**Submitted by Pierre Irrmann on 3/7/2016 12:00:00 AM**  
**13 votes on UserVoice prior to migration**  

I've been using custom keywords in computation expressions to write DSLs, and I would have loved to be able to have several signatures for the same custom keyword, in order to make some arguments optional in the expression.

When you try do it today, there is an error message such as "The custom operation 'myOperation' refers to a method which is overloaded. The implementations of custom operations may not be overloaded"
I'm aware this is a not-so-used feature, but I'd like to know how hard you think it could be (I would event be willing to have a look at how to implement it).

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12839142)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12839142-allow-overloads-of-custom-keywords-in-computation.md#comments)

**Comment by dsyme** [comment]
We decided in F# 3.0 not to support overloading on these, for reasons of code clarity,.

While I can see the utility of this, per design policy we don't revisit design decisions that have already been made unless there's a significant change in circumstance or assumptions.

**Comment by dsyme** [comment]
Reopening - Based on discussions with Diego Esmerio on slack I'm ok with approving this in principle but with this comment:

> Next step is an RFC by you, with matching implementation PR :slightly_smiling_face: And then get community feedback.  Some people may be opposed to this - though I won't block it if the use cases in Saturn etc. are compelling and described properly.  
>
> The reason I'm asking for compelling examples and a proper RFC is that I want people to understand (and have a record) for why we're doing this, and for people like @cartermp to be able to use your examples to explain why this is valuable when it comes to communicating this, e.g. in a Visual Studio blog post.

**Comment by gerardtoconnor** [comment]
Just to add some input on this request, recently I had issues due to there being no overloading on customOperations in my [experimental Zebra library](https://medium.com/@gerardtoconnor/racing-the-zebra-benchmark-performance-architecture-for-f-web-server-58dd922f5cfe) and had to do a hack work around although overloads is what I really wanted, had to take a performance hit.

In my CE I was chaining operations together by a passed state that could be a limited number of things (in limited combinations), I know the obvious answer is DU but due to the performance focus I could not afford DU allocations on each chained operation, as well as the deconstruction/matching, I had to settle on the less optimal struct DU, embedded in my CE state, that still needed matching as well as bloated embedded allocation (more space, less alloc). It also ruined some of the inline optimisations I could have received if the operations were explicitly overload linked (& inlined) as complete execution branches would be optimised. 

I know this is an extreme performance case that reflects only perhaps 1% of usage but if these cases are in frameworks that become popular it is unfortunate we are wasting & bloating on this needless restriction. I have already started looking into compiler source for how overloading can be integrated, more MINFO needs to trickle down to CE resolver code to handle/match overload list but seems like not too bad of a job, I think it is well worth it given the perf benefits that can be achieved.

**Comment by UnoSD** [comment]
This is probably a naive question, but I've been using overloads for custom operations for a while ( see https://github.com/UnoSD/Pulumi.FSharp.Extensions/blob/master/Pulumi.FSharp.Azure/Legacy/Core.fs ) without adding the attribute, it just works. I'm wondering, what does this add? I am interested to know if I can leverage this change in some other way or if there is any issue with my current approach that I haven't spotted yet.

**Comment by abelbraaksma** [comment]
@UnoSD, here's the rfc at details the changes: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1056-allow-custom-operation-overloads.md

**Comment by UnoSD** [comment]
@abelbraaksma I already had a look at that, it does not seem to be any different from just overloading without the attribute.

**Comment by cartermp** [comment]
@UnoSD it all depends on how it's called. Consider [this example](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfA9gBwKYDsAEBlAnhAC7oC2AsAFBVH4bYCSmqArkQNICWmM2AvFWxDsibABV0ADyLZkYbKmABDAMboAFsmAx0AJxDFd3AOazURTskyDhogApKIEAO7JdvOQuVrN2vSGxDEzMLKyoaOnRGZjYAeXNLTAh+GwBvbAAZJQAjdFBAoiNMUzRQ60phbC4ebACmVg5uGBshADUlYE4YJSI3ZICACiDi7ABaAD5sbOQtAEpsJV1dJXxsAF9wylp6erYAIRZOP10B+YFqCuFSMlzdbCIAOgBNTjyYAYB9M+wW4XSs3LAfjYAByVnQv0q1V4fHEUhkYMwEMulTaHS6PT6wIA2ohEABddaQ4S/bEAHgAwixiMhSPE9D1EgMAEQkaTM2bjfG/a6kW73dScCAPCTSAaWKAAfkUqg0Wh0ujOxKE6Us2GcnCI6iqTWBopkMp88r0RJRqNJlOpvTpGGWZRZqEcLjcMA5XJ5NxNWqFDwcTlc7nFyClhrlxyVZsqquQ6s12uhwL9zvcXllvgVptRJLN5KpNJtDPtzOUgLd3LNvP53uFALyQagJby32V2Gjsa1mRyeWBuFpUUbQI2kezlVzVtp9LtTOZGq1HwAbujur1dBAyx6+V7BcL2p1l3169hyQ5lqQAIJLFZc7CLveY1cRrMq7Bq2fa3cYlfJWG3z9YoeVFQwDoDI3ANMCuxEAcRwKqcmzATImBKNcKSXGBbCtr8A7YMyILIegzK/GyRC/G+C5LveEAtgMuCFCYDwMBAIIsMAwCxLoADqgokLgjpqNg4yTJgyBELMNgAU+QEgdgZBKEcqFCOhMipFhXZAsyACipBycAhFmsROFPMgLB3LJRx6ZUZG/vuq7UbRRTGAxTEsWxnHcegvGygJQkiWJw5CAMYAsDgyQTIEDwUlYRByUkOEAAJxRy4ktlJBpOgGMI2EpmFmthzJJhlFnCI6/oujhACyVrYCoUUxckPTYMBjgyAAbNV6iLKoJCrlAshItgmAsJudxKDU4LYCwqC2iojgEaRcbkXeX52XRxQPFIQpEMkFIdboTkAKpTXoflPtgNGrY5G3ENtu1OQAIpwxiaidT6BcFgRjJMNZYMYHbjLCLUvWsQA==) that will work with the feature. Another is overloads of different arities. It doesn't appear that those are utilized in your project.

**Comment by UnoSD** [comment]
@cartermp thank you for the example, it makes sense now.

**Comment by Thorium** [comment]
As the builders are coming fashionable, we'd need more validation possibilities, and extending this would help.

Here is a code sample that is not working in F# 5.0:

```fsharp
type InitialState =
    { Name : string
      Username : string option
    }

type ValidState =
    { Name : string
      Username : string option
      MoreData : string option
    }

type MyBuilder() =
    member __.Yield _ =
        { Name = ""
          Username = None
        } : InitialState

    // This fails for custom operator overloading now:
    [<CustomOperation "name">]
    member __.Name(state:InitialState, name) = { state with Name = name }
    member this.Name(state:ValidState, name) = { state with Name = name }

    [<CustomOperation "username">]
    member __.Username(state:InitialState, username) = 
        { Name = state.Name
          Username = username
          MoreData = None
        } : ValidState 

let my = type MyBuilder()
let process (x:ValidState) = 
    //...
    ()

my { name "hello"; username "hello" } |> process // Valid
my { username "hello"; name "hello" } |> process // Valid
my { name "hello" } |> process // Invalid, compile time error
```

**Comment by dsyme** [comment]
This is completed in RFC FS-1056 https://github.com/fsharp/fslang-design/blob/main/preview/FS-1056-allow-custom-operation-overloads.md
