### ISSUE TITLE
Allow record inheritance / multiple "inheritance"

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#70]
**Submitted by Vasily Kirichenko on 3/10/2016 12:00:00 AM**  
**17 votes on UserVoice prior to migration**  

I propose to add multiple ***fields*** inheritance into records:
```fsharp
type Person =
{ First: string
  Last: string }

type Foo = { Bar: int }

type Student =
  inherit Person
  inherit Foo
  { GPA: float }

let student = { First = "a"; Last = "b"; Bar = 2; GPA = 1.0 }
```

Making the same thing with composition results with not such an elegance flat records.
This approach is used, for example, in Nitra AST DSL, see https://github.com/rsdn/Nitra-Mini-C/blob/master/Nitra-Mini-C/MiniC-ast.nitra#L94

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12879717)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12879717-allow-record-inheritance-multiple-inheritance.md#comments)

**Comment by dsyme** [comment]
Note this is multiple-inheritance is not implementable withing the constraints of the .NET type system (since records are ultimately classes).  And singe inheritance is a poor substitute which is better not added alone.

**Comment by dsyme** [comment]
Closing for the above reason

**Comment by izackhub** [comment]
Is there a possibility to instead opt for a more highlevel approach that is taken care of by the compiler instead? I have been testing out many programming languages, F# is by far my absolut favorite, but there are some features I have come across that would really be practical, especially with a strict type system like F#'s. 
1 such feature is 'Type inclusion' in it's current form in the Ballerina Lanaguage. 

type Person record {|
    string name;
    int age;
|};

type Student record {|
    int studentId;
    string code;
|};

// The `PartTimeStudent` record has all the fields of `Person` and `Student`.
type PartTimeStudent record {|
    *Person;
    *Student;
    // Overrides the `code` field in `Student`.
    string:Char code;
|};

here, the fields of the Person and Student are effectively spread into the PartTimeStudent record. Using a copy mechanism overcomes the inheritance problem and rather just trasnparently add the fields the same way it's currently done by duplicating the fields in the eyes of the compiler.

I have run into 2 situations where I ended up duplicating almost exact keys of a type, because 1 of the types had 1 extra field or the type 1 of the 1o fields in a record type differred for 1 2types. 1 being used to bind form data that had a checkbox, the other was only to make it a real boolean for the document database.
