### ISSUE TITLE
Allow sequential processing for a sequence of asyncs

### ISSUE THREAD

**Issue by isaacabraham** [fsharp/fslang-suggestions#706]
# Sequential processing for a sequence of asyncs

I propose we provide support for an equivalent of `Async.Parallel`, `Async.Sequential`, which enforces *sequential* processing of workflows. The signature would be the same as `Async.Parallel` i.e. `Seq<Async<'T>> -> Async<'T []>`.

Sequential processing is useful in many cases where you need to, for example, throttle a number of asynchronous computations to a certain size. For example, you have 100 messages but can only send one at a time. `Async.Parallel` cannot achieve this sort of behaviour as it would send all of them together. In addition, combined with `Seq.chunkBySize`, you can control throttling at a specific batch size using Parallel for inner batches and Sequential for the overall control flow.

The existing way of approaching this problem in F# is to manually implement a recursive function or otherwise. However, it's a general problem which I believe would be useful to have.

## Pros and Cons 
The advantages of making this adjustment to F# are that the utility of FSharp.Core increases.

The disadvantages of making this adjustment to F# are that there is another method on the Async type, and some users may not know the difference between `Async.Sequential` and `Async.Parallel`

## Extra information
Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

I have implemented a (crude) sample which illustrates how this may look [here](https://gist.github.com/isaacabraham/1255f5c663176dfae9495987c4d6e460) as a starting point. It would be useful to know what it is missing as a way of moving this forward.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by realvictorprm** [comment]
Sounds understandable to me 👍

**Comment by dsyme** [comment]
It's reasonable to add this.

**Comment by cartermp** [comment]
@isaacabraham We can use an RFC to discuss approaches to implementation.

**Comment by isaacabraham** [comment]
Should I go ahead and create a basic RFC or is that something the language design team do?

**Comment by cartermp** [comment]
@isaacabraham definitely feel free. We can discuss the general approach to implementation there.

**Comment by gusty** [comment]
Here's a possible implementation from F#+ https://github.com/fsprojects/FSharpPlus/blob/74990208661751e2cb341600ea3ba2e62906f5f0/src/FSharpPlus/Extensions.fs#L1021-L1028

**Comment by isaacabraham** [comment]
I'll be putting the RFC together next week.

**Comment by Frassle** [comment]
Could F# just copy TPL and add an optional parameter/method overload/new method that has a [max degree of parallelism parameter](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.paralleloptions.maxdegreeofparallelism?view=netframework-4.7.2#System_Threading_Tasks_ParallelOptions_MaxDegreeOfParallelism).

Sequential is then just a max degree of 1, but this also provides other rate limiting options like running 10 connections at once. It's not possible to perfectly implement that now because you have to statically decided batch sizes so if one batch finishes faster that thread won't steal work.

**Comment by Frassle** [comment]
First time trying to develop on F# but put together https://github.com/Microsoft/visualfsharp/pull/6357 as a proof of concept.

**Comment by isaacabraham** [comment]
@Frassle yeah, the RFC suggests that as a possibility.

**Comment by cartermp** [comment]
I like the proposed implementation, though from an API surface area perspective I think it's also valuable to have a `Sequential` member. It can just call Parallel `maxDegreesOfParallelism=1`.

**Comment by isaacabraham** [comment]
Can this issue be closed - hasn't it now been delivered in the latest FSharp.Core (notwithstanding the bug on the current implementation - which I think has now been fixed and released)?

**Comment by nightroman** [comment]
I think the current implementation has a pitfall and I was caught.

The name `Async.Sequential` suggests that expressions are invoked in sequence.
And the [F# RFC FS-1067] talks about some processing "queue", namely

> The key behavioral difference between this and the existing Async.Parallel is
that this would enforce processing of multiple workflows in a sequential
"queue", before returning all the aggregated results to the caller.

I do believe that the current implementation invokes expressions one at a time,
otherwise that would be a bug, right? But this is not the same as invoking one
after another in the provided order.

If the current behavior is by design, this is fine, it is effective. But it
would be nice to have it documented. Because workflows are still invokes in
parallel and it's not what the name suggests and one may expect.

BTW, I cannot find the official documentation of this released feature.

Here is the slightly modified example from RFC that shows some "random order"
of processing by `Async.Sequential`

```fsharp
// 1. example collection of workflows
let random = System.Random ()
let workflows = [|
    for x in 1 .. 10 do
        async {
            do! Async.Sleep (random.Next 500)
            printfn "Working on %d" x
        }
|]

// 3. using Async.Sequential
workflows |> Async.Sequential |> Async.RunSynchronously |> ignore

(*
Working on 3
Working on 2
Working on 7
Working on 1
Working on 4
Working on 10
Working on 5
Working on 6
Working on 9
Working on 8
*)
```

[F# RFC FS-1067]: https://github.com/fsharp/fslang-design/blob/master/FSharp.Core-4.7.0/FS-1067-Async-Sequential.md#detailed-design-asyncsequential

**Comment by cartermp** [comment]
@nightroman The issue you're observing is resolved.

**Comment by nightroman** [comment]
@cartermp It's good, thank you. Is it released, or when is it going to be released?

**Comment by cartermp** [comment]
It's in the latest VS 2019. Not sure about NuGet. See here: https://github.com/dotnet/fsharp/pull/7596#issuecomment-573408074

**Comment by nightroman** [comment]
We use the latest FSharp.Core (4.7) and the latest VS 2019. The issue is there, probably because of the old NuGet package. Looking forward to the new package! Thank you for the good news.

**Comment by Thorium** [comment]
Could we call this by a new `fun!` keyword:
```fsharp
async {
   let! res = xs |> Seq.map(fun! x -> fetchAsync x)
   return res
}
```
