### ISSUE TITLE
Allow variable patterns for tuples in Discriminated Union matching

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#743]
# Allow variable patterns in Discriminated Union matching

I propose we allow variable patterns in Discriminated Union matching

The existing way of approaching this problem in F# is explicitly matching all tuple elements.

```fs
type DU = DUCase of int * int * int
match du with
| DUCase tuple -> f tuple
```
vs
```fs
type DU = DUCase of int * int * int
match du with
| DUCase (a, b, c) -> f (a, b, c)
```

## Pros and Cons

The advantage of making this adjustment to F# is shorter and concise matching.

The disadvantage of making this adjustment to F# is implementation effort required.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS~S

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by gusty** [comment]
I don't know what's reason why this was not allowed from the beginning, I wonder whether this is a bug.
Maybe someone would argue that you need to be explicit about the tuple to allow to disambiguate between different tuples, but you can't have 2 cases of the same DU, so what's the point of forcing you to match each element?

**Comment by charlesroddie** [comment]
I agree this would be good to have. Some subtleties:

```fsharp
type DUTuple = DUTupleCase of (int * int)
function
| DUTupleCase data -> ...
```
Here `data` has type `int*int`. This works currently and achieves the objective of the example in the OP.

Now consider:

```fsharp
type DUB =
    | DUBCase1 of int * int
    | DUBCase2 of int * b:int
function
| DUBCase1 case1Data -> ...
| DUBCase2 case2Data -> ...
```
What types should `case2Data` have? We should forget DUBCase1 because it's bad practice to have multiple unnamed inputs. We should make a decision for DUBCase2 and extend it consistently to DUBCase1.

The natural type for case2Data is an anonymous record of type `{| Item1:int; b:int |}`. But this is inconsistent with existing syntax `match ... with | DUBCase1(a,b)` since `(a,b)` can't match an anonymous record.

So perhaps the only option is to strip the names and match as tuples? So `case2Data` would have type `int * int`.

**Comment by jwosty** [comment]
@charlesroddie this would be interesting if there were named tuples (i.e. C#'s named ValueTuples); then it would be a 1-to-1 mapping.

Pros: allows this match rule to work
Cons: we already have anonymous records -- what would be the difference?

Just a thought.

**Comment by cartermp** [comment]
The asymmetry between:

`match .. with | DUBCase1(a, b) -> ...// do stuff with 'a' and 'b'`

and:

`match .. with | DUBCase2 x -> ...// do stuff with 'x.Item' and 'x.b'`

Is confusing, since both are currently tuples. If `DUBCase2` were defined as an anonymous record type that would make sense. The most consistent form would be to bind both to a tuple type and force the programmer to pattern match if they need to access constituent parts.

**Comment by dsyme** [comment]
> I don't know what's reason why this was not allowed from the beginning, I wonder whether this is a bug. Maybe someone would argue that you need to be explicit about the tuple to allow to disambiguate between different tuples, but you can't have 2 cases of the same DU, so what's the point of forcing you to match each element?

As history, OCaml deliberately forced matching against constituent elements and F# followed this design. It's hard to explain exactly why this was preferred - other languages such as StandardML and Haskell allowed implicit tupling here.  But I personally _much_ preferred the accuracy forced by the OCaml decision.  (I haven't followed recent updates to OCaml and it may be they eventually removed the distinction)

One consideration was that the conversion from `Data (x,y)` to `(x,y)` may be an allocation (since tuples are allocated).  But I think the real reason is that allowing the implicit conversion makes programmers write code that is a bit too cute and relies too much on "fortuitous" ordering correspondence between the union case and the tuple.  It's just rare that the values are placed in the union case data constructor in exactly the right order, and once you get more than two items in the data constructor it pays (in terms of code comprehension, error messages etc) to be explicit.

**Comment by kspeakman** [comment]
As @charlesroddie noted:

```fsharp
type DU = Case1 of int * string
// is different from
type DU = Case1 of (int * string)
```

The second one can pattern match as a single variable (in addition to tuple) whereas the first cannot. However, in the 2nd case, the types cannot have names.

```fsharp
type DU = Case1 of sum:int * name:string
// versus
type DU = Case1 of (sum:int * name:string) // ❌ compile error
// FS0715: Anonymous type variables are not permitted in this declaration
```

Also note that these two definitions are different behind the scenes. For example, they are constructed differently with reflection.

```fsharp
type DU = Case1 of int * string
let makeDuWithReflection i s =
    let args = [| box i; box s |]
    FSharpValue.MakeUnion(... , args)

// versus
type DU = Case1 of (int * string)
let makeDuWithReflection i s =
    let args = [| box (i, s) |]
    FSharpValue.MakeUnion(... , args)
```

The differences from using parenthesis or not is surprisingly large.

**Comment by dsyme** [comment]
Closing for the reasons explained here https://github.com/fsharp/fslang-suggestions/issues/743#issuecomment-507298497

That is, the combination of "perceived extra accuracy" and "no implicit allocation"
