### ISSUE TITLE
Make dictionaries assignable to functions

### ISSUE THREAD

**Issue by Richiban** [fsharp/fslang-suggestions#748]
# Title of Suggestion

I propose we make dictionaries (such as those returned by the `dict` and `Map` functions) assignable to functions. After all, we all learn that, to functional programs, a function is just a mapping from an input to an output--so why can't we use a literal map as if it's a function?

The existing way of approaching this problem in F# is to write a lambda to index the map, like so:

```
let transform = Map.ofList [ true, "yes"
                             false, "no" ]
                
let english = [true; true; false] |> List.map (fun x -> transform.[x])
```

It's a minor difference, but having an `IDictionary<bool, string>` appear to implement `bool -> string` would lead to a nice sort of consistency and usability in the language.

## Pros and Cons 

The advantages of making this adjustment to F# are that programmers will better understand the roles of functions and maps and how they relate to each other.

The disadvantages of making this adjustment to F# are that I don't know how this would be implemented. Would the compiler simple emit a lamda?

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by davidglassborow** [comment]
If you need this, you can write a generic function yourself:

```fsharp
let toFunc (map:Map<'a,'b>) = 
    fun x -> map.[x]
```

Also in reality you would probably want to use `TryGetValue` or similar.  Given it's so easy to write if you need it, I suggest it shouldn't be part of core.

**Comment by theprash** [comment]
I can appreciate the point you make about functions and maps being connected, and I think the implicit conversion makes sense in a dynamically typed language like Clojure where this is actually possible, but not in F# where the general philosophy is to be explicit rather than implicit. For example, even the implicit conversion from `int` to `float` isn't supported in F#. Maps and functions are two different things and should have incompatible types. In many cases it could be confusing and hard to understand why they were treated as the same type.

Some difference between maps and functions:

- You can guarantee that getting a value from a map won't launch a missile. A function call could.
- You can list all of the keys and values in a map.
- A map as a function must always return an option to be safe of runtime exceptions (what if the map doesn't have the complete set of inputs for the type?). Functions can safely return the actual value because they can be written in a way that handles all possible inputs (e.g. a complete pattern match with no warnings).

**Comment by cartermp** [comment]
An additional important distinction is that functions compose and use currying, whereas these are not applicable concepts for maps/dictionaries. I can appreciate the surface-level similarity, but they are not isomorphic without changing maps or functions in some fundamental way.
