### ISSUE TITLE
Add constraints to match FSharpType.Is* predicates

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#77]
# Add constraints to match FSharpType.Is* predicates [12920034] #

**Submitted by Matthew Orlando on 3/13/2016 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

I have a type, ``CaseSet<'a>``, that is only meant to be used with descriminated unions. The only way I've found to enforce this is at runtime using ``FSharpType.IsUnion``. I considered using type providers, but those aren't supported in PCLs.

I propose adding the following constraints based on the corresponding FSharpType reflection functions.

```
function : IsFunction
tuple : IsTuple
union : IsUnion
record : IsRecord
module : IsModule
exception : IsExceptionRepresentation
```

(I'm not really sure about that last one... I included it for completeness but maybe just testing for some subclass is sufficient?)

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12920034)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12920034-add-constraints-to-match-fsharptype-is-predicate.md#comments)

**Comment by dsyme** [comment]
There are really an arbitrary number of constraints that can be added.  It seems the best solution would be to allow plug-in mechanisms (akin to type providers) to implement new constraints.

**Comment by dsyme** [comment]
I'm closing this since we won't add these constraints directly.  But they are good examples to motivate a more general mecahnism

**Comment by cloudRoutine** [comment]
@dsyme would it be worthwhile to have another label like `Requires Resubmission - Too Specific` or something along those lines?  I think I've seen you comment in a similar manner on suggestions in the past, but currently there's no easy way to keep track of them.  

It could also be beneficial to have a label for the suggestions you reject because a library implementation would be more appropriate than a language feature. F# devs often ask how they can get started doing F# OSS dev throughout the various online forums and channels, and if there were a label that grouped them it'd be simple to point them here. As it currently stands it seems like these suggestions get lost in the wash.
