### ISSUE TITLE
multiple and power of int and float has actual meaning

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#770]
int multiple float or float multiple int has actual meaning in real world. for example, there is 9 bottle of cola in a box, every a bottle has 2.5L cola, how many Liters  are the total cola  in a box?
```F#
let count = 9
let bottle = 2.5
let total = 9*2.5
let total = 2.5*9
```

another has actual meaning is pow, for example, several number of float number multiple:
```F#
let res:float= 2.5**3
```
actually is:
```F#
let res = 2.5*2.5*2.5
```
when float divide int has actually meaning, for example, Mother is sharing the cola (2.5L) among the children(2 p).
```F#
let average = 2.5 / 2
```

**Comment by Happypig375** [comment]
Might as well add `int + float`, `float32 - int16|, `byte + int64`, `int64 ** decimal` and so on.

**Comment by gusty** [comment]
This suggestion is related #737 see my comment which propose a solution for this by using generic numbers.

**Comment by abelbraaksma** [comment]
I don't understand this request. What does 'has actual meaning' mean? What is the proposal here? I don't see a concrete proposal in the original post. 

Meaning can currently be added by using measures, which is already supported. But not sure that's what's asked here.

**Comment by xp44mm** [comment]
@abelbraaksma 
some auto-covert's actions should make sense:
  - when `int` meet `float`,  `int` auto-convert `float`.
  - and so on.

**Comment by abelbraaksma** [comment]
Since this is a language suggestion, can you write your original request as such to explain what you want changed in the language to make that happen? How can this be done without breaking current code, and how can the compiler know unambiguously what target type is wanted? In your examples, both `double` and `int` seem reasonable.

Though I wouldn't be surprised if this hasn't been asked already and decided upon. 

I personally prefer the strictness, as it makes my code more readable, allows me to reason about it and make assumptions. Allowing implicit conversions, while convenient, can be a cause of hard to find bugs, which is precisely why people choose a strictly typed language (F#, Haskell) over a loosely typed language (C#, Php). 

That said, you can always make your own struct types with implicit conversions, in some cases this makes sense and I have used it as well a handful of times.

**Comment by gusty** [comment]
@abelbraaksma 
Actually, implicit conversion is not the only way to solve this.
If you look at the comment I linked, supporting generic number literals should be the way to go.
You mentioned Haskell, well Haskell has this feature.

**Comment by abelbraaksma** [comment]
@gusty, thanks, I found your comment now and I agree it makes more sense to use generic literals to solve the common issue discussed there. Perhaps the OP can read that thread as well and close this as duplicate.

**Comment by xp44mm** [comment]
@abelbraaksma 
yes, this suggest is duplicate with the issue you provided. hope realize that feature! thank you for your answer!

**Comment by cartermp** [comment]
I don't think we'll consider implicit conversions. #737 is far more likely to get traction.
