### ISSUE TITLE
Add a pipe bang (|>!) operator 

### ISSUE THREAD

**Issue by travis-leith** [fsharp/fslang-suggestions#791]
# Pipe bang

I propose we add a new operator (|>!) that allows us to unwrap a monadic value and pipe it at the same time.

The existing way of approaching this problem in F# is

```F#
compExpr{
    let! someValue = someFunction()
    let someOtherValue = someOtherFunction someValue
    //I no longer need to use someValue for anything
}
```

or alternatively

```F#
compExpr{
    let someOtherValue = someFunction() |> aSpecificMapFunction (someOtherFunction someValue)
}
```

With the pipe bang operator, it could be rewritten as

```F#
compExpr{
    let someOtherValue = someFunction() |>! someOtherFunction someValue
}
```
## Pros and Cons 

The advantages of making this adjustment to F# are it makes programming in a computation expression more similar to programming outside of a computation expression. It also enables a shorter syntax.

The disadvantages of making this adjustment to F# are ... I can't think of any.

## Extra information

Estimated cost : I can't see that this would be a particularly difficult feature to implement.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  

Please tick all that apply:
* [x] This is not a breaking change to the F# language design

**Comment by cartermp** [comment]
Barring some careful application of SRTP (perhaps constraint to require the `Bind` member?), there wouldn't be a way to do this in a general way without a fundamental adjustment to the F# type system.

**Comment by ChechyLevas** [comment]
Since it is already within a computation expression, there is already a constraint to require the `Bind` member. Can the same mechanism that is used for `let!`, not be used for `|>!`? If so, it would be a fairly small change to enable this syntactic sugar, no?

**Comment by ChechyLevas** [comment]
@cartermp  - forgot to include you in my response, so making up for it here.

**Comment by cartermp** [comment]
@ChechyLevas The same mechanism could not be used, since an operator is not the same as the `let!` keyword from the compiler's perspective.

Another alternative would be to define an operator here, but intercept it in the compiler and do something very different with it. So much like `nameof` and `raise` it wouldn't be a "real" operator, but a specialized component that looks like an operator, and instead of operating on a `'T`, it would operate on some `Foo<'T>` with a builder that defines the appropriate builder members. That would probably be a medium-cost feature.

**Comment by ChechyLevas** [comment]
Perhaps there is a downside to this proposal. We would need 1 operator `|>!` to behave like a generic map, and another operator, possibly `|>!!`, to behave like a generic bind. This could be argued to contribute to operator soup.

**Comment by abelbraaksma** [comment]
It is currently possible to define this for any specific computation expression. As @cartermp already mentions, with some SRTP magic it is perhaps possible to make this generic. 

Instead of making this particular change for only one operator, we should try to find a way to make it easier to write such operators that should work seamlessly inside CE's. But that immediately raises the questoin: CE's were invented to make functional programming look more imperative. Now we would be trying to get functional features back in? I'm not saying it is a bad idea, but we should think it through and I hope we can come up with something that tackles the generic case (i.e., make it easier to write `|>!`, `<|!`, `||>!`, `<<|!` and `<<!` etc) instead of adding more functions to the surface area.

**Comment by gusty** [comment]
I don't think this is possible to implement fully with SRTPs, because the class to constraint is the builder class which is technically unrelated to the types inside the computation.

In F#+ there is a map operator `|>>` but it requires a static member in the type class, not the builder class. The builder is a generic one for monadic types. So this is not the same thing.

**Comment by amieres** [comment]
Personally, whenever I create a monadic type, I also create a module with operators:

```
module Operators =
    let inline ( <*> ) f v   = apply f v
    let inline ( |>> ) v f   = map   f v
    let inline ( >>= ) v f   = bind  f v
    let inline ( >-> ) f g v = f v |>> g
    let inline ( >=> ) f g v = f v >>= g
```
 ... that then can be used inside or outside a Computation Expression.

Also, I use `|>!` and `>>!` as `tee` operators https://fsharpforfunandprofit.com/rop/ :

```
let [<Inline>] inline tee f v = f v ; v

/// tee: call a function but return the input value
/// for logging, debugging
/// use: (5 * 8) |!> printfn "value = %d" |> doSomethingElse
let [<Inline>] inline  (|>!) v f   = f v ; v
let [<Inline>] inline  (>>!) g f   = g >> fun v -> f v ; v

```

**Comment by Swoorup** [comment]
I prefer the bang to be ahead first. That is saying only pipe if the previous operation succeeds in a Result or Option context.

```fsharp
option {
    TryFindNeedle()
    !|> transformToHammer
    |> bleh
}
```

**Comment by ehouarn-perret** [comment]
@Swoorup I think that goes against the non-written convention which involves ending the operator with the bang character `!`:

- `let!`
- `do!`
- `return!`
- `match!`
- `|>>!`
- `>>=!`
- `<!>`
- ...
- `|>!`

**Comment by Swoorup** [comment]
I agree about let, match, do, return but infix operators are bit different though, isn't it. 
Adding to the right feels bit odd to. 

Left version:
`TryFindNeed() !|> transformToHammer`

Right version:
`TryFindNeed() |>! transformToHammer`
Not that the following is correct, but easy to confuse with deference
`TryFindNeed() |> !transformToHammer`

Just a food for thought

**Comment by abelbraaksma** [comment]
@Swoorup, the exclamation mark at the start of an operator makes them prefix operators (as opposed to infix). Changing this would probably be a backwards compatibility issue, and even if it's possible by special casing it, it would violate the _principle of least surprise_, in that users will expect such operators to be prefix, as they are used to that now.

Quote from docs:

> Operators that begin with !, except !=, and the operator ~, or repeated sequences of ~, are always prefix operators.

**Comment by jl0pd** [comment]
As developer I would expect to have symmetry in operators:
`|>` is *pass one argument to function on the right*
And CE-version of this operator
`|!>` would mean *bind and pass one argument to function on the right*. Usable for case when you have `Task<int>` and `int -> unit`

But F# have additional operators:
`||>` is *uncurry 2 arguments and pass them to function on the right*. `(int, int)` and `int -> int -> unit`
So there's should be 3 additional operators for CE
`|!|!>` is *bind 2 arguments and pass them to function on the right*. `(Task<int>, Task<int>)` and `int -> int -> unit`
`|!|>` is *bind first and pass 2 argument to function on the right*. `(Task<int>, int)` and `int -> int -> unit`.
`||!>` is *bind second and pass 2 argument to function on the right*. `(int, Task<int>)` and `int -> int -> unit`.

But F# have even more operators: `|||>` which will introduce **8** CE operators.
And don't forget about backward pipe operators: `<|` `<||` `<|||`, each should have same set of CE operators

The problem with this approach is that language gain a ton (24 actually) of new highly specialized cryptic operators.

I don't even take into account relational operators: `<` `>` `>?` `?>` `?>?`... Each one should have `!` at both sides.

**Comment by Happypig375** [comment]
Let's just have #1070 instead.

**Comment by dsyme** [comment]
Agreed we would do #1070 before this
