### ISSUE TITLE
Attributes for local `let`s

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#848]
# Attributes for local `let`s

I propose we allow attributes for local `let`s.

The existing way of approaching this problem in F# is to put the `let`s that need attributes at the top level, polluting Intellisense.

```fs
module M =
    let [<System.Diagnostics.DebuggerStepThrough>] private f _ = ()
    let [<Literal>] private Constant = 3
    let f x =
        // FS0842: This attribute is not valid for use on this language element
        let [<Literal>] Constant = 3
        // FS0842: This attribute is not valid for use on this language element
        let [<System.Diagnostics.DebuggerStepThrough>] f _ = ()
        ()
```
## Pros and Cons 

The advantages of making this adjustment to F# are
1. Independence between proper scoping and attribute utilization
2. Less Intellisense pollution
3. Conciseness by not needing to pass local values into local functions just because they need attributes

The disadvantages of making this adjustment to F# are none that I can think of.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: None

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by Happypig375** [comment]
C# already has this: https://github.com/dotnet/roslyn/issues/38801

**Comment by abelbraaksma** [comment]
I think this is great to have, especially for literals, but I doubt it's going to be easy. Some things come to mind:

* often, attributes are used with discovery of methods that need to get special treatment, but in F# there's no one to one relation between the name and the attribute. We'd need some way to get the original name as well.
* the location of the definition of the final let binding function is a class, not a method. That class has one or more `Invoke` methods. Would we append the attributes to these methods?
* currently, attributes are not maintained when a method uses curryable arguments. It's very common to curry in F#. Would we append the attributes to each intermediate function?
* local functions are often inlined, there's no way to maintain the attributes in such case. Should we raise an error, or fix that in some other way? 
* what happens with quotations? 

That's from the top of my head. There may be a lot of subtleties involved here. Alternatively, we could only allow a subset of attributes that are recognized by F# or by the CLR.

**Comment by abelbraaksma** [comment]
Can we combine this with #984? I think both have merit, but need some ironing out

**Comment by dsyme** [comment]
This doesn't seem right for F#.

The expression language has always been kept "simple" in the sense that it's largely just plain and simple functional programming with various additions to augment the power of FP.  There's never been any real intention that it should be possible to reflect over the internals of compiled expressions.  This also allows the compiler great leeway to perform optimziations.

This philosophy seems stable and reasonable, and it needs some really big and important reason to allow the .NET-style attributions and other such reflective things to intrude into the expression language.

Since I'm spring-cleaning I'll close this out for these reasons.

**Comment by Bananas-Are-Yellow** [comment]
Here is an example of why this is useful. I want to do the following so that the compiler will confirm that the inner function `loop` is indeed tail-recursive.
```
let factorial n =
    [<TailCall>]
    let rec loop n acc = 
        match n with
        | 0 | 1 -> acc
        | _ -> loop (n - 1) (n * acc)
    loop n 1
```
If I put `[<TailCall>]` on the outer function, only the body of the outer function is checked, not the code inside the inner function.

Yes, I could make `loop` a private function of the module, but since it is only ever intended to be used by `factorial` it is natural to make it a nested function. And if I have other `loop` functions at module scope, I'd have to give them all unique names.

**Comment by Bananas-Are-Yellow** [comment]
I suppose I could do this:
```
module Math =
    module private Factorial =
        [<TailCall>]
        let rec loop n acc = 
            match n with
            | 0 | 1 -> ACC
            | _ -> loop (n - 1) (n * ACC)

    let factorial n = Factorial.loop n 1
```

**Comment by Happypig375** [comment]
@dsyme Attributes are not only for reflecting at runtime but also for various compile-time items like `[<Constant>]`, `[<TailCall>]` and `[<Struct>]` (for active patterns). Would a whitelist be considered to only allow compile-time attributes?

**Comment by Thorium** [comment]
This works:
```fsharp
let myState = 5
let inline processFive ([<InlineIfLambda>] simpleOp) =
    simpleOp myState

let test =
    processFive (fun c -> c + 1) +
    processFive (fun c -> c - 1)
```

The same code inside a function doesn't work:
```fsharp
let myCodeContext() = 
    let myState = 5
    // error FS0824: Attributes are not permitted on 'let' bindings in expressions
    let inline processFive ([<InlineIfLambda>] simpleOp) =
        simpleOp myState

    let test =
        processFive (fun c -> c + 1) +
        processFive (fun c -> c - 1)
    test
```
...so I have to cut the processFive out of the myCodeContext to somewhere else. Which is a bit annoying as then it leaks the "internal" myState out of myContext.

**Comment by eacasanovaspedre** [comment]
I came here looking for a future solution to the problem of adding TailCallAttribute to a nested/local function. Most of my recursive functions are local, since most of the time I have to carry some kind of accumulator or state, and I don't like to expose that part to the user of the function. 
Is this ever going to be considered or are there any alternatives? Otherwise, I find almost no value in TailCallAttribute.

**Comment by T-Gro** [comment]
One thing the compiler does not know (right now) is the ability to allow F#-typechecking-only attributes - this could be the case with TailCall.
That would eliminate compiler changes in IL generation, since TailCall is not needed at runtime anyway.

**Comment by T-Gro** [comment]
I can only imagine this for a whitelist of supported `F#-compile-time` attributes.
For any other .NET attribute, this would just confuse people to think a certain .NET library/framework will process it by their expectations.

**Comment by IS4Code** [comment]
I would be fine with restricting it that way, since the "full" range of attributes would require a general mechanism in .NET to attach them to variables, to be complete.

Are there other attributes that might make sense for function parameters? Maybe `[<UnscopedRef>]` or something affecting nullness, but I am not sure how that is exposed in F# currently.  I was also thinking about `[<Out>]`, `[<In>]`, `[<Optional>]` and `[<DefaultParameterValue>]` which, while ignored by F# for functions, are in the area of CLI "pseudo custom attributes".

**Comment by T-Gro** [comment]
A reasonable start should contain just attributes for F#'s own typechecking, and not even care about IL generation.
i.e. any attribute important for the runtime or interop with other projects/compilers is likely not a good fit.

That way, the question of where to emit and how to handle optimizations can be fully removed, focusing just on the semantics within F#'s own compilation.

**Comment by Thorium** [comment]
Like attributes, I would also want the `#nowarn` pragma to work within local lets. This would allow me to have finer-grained control over what raises warnings and what does not.

**Comment by Martin521** [comment]
> Like attributes, I would also want the `#nowarn` pragma to work within local lets. This would allow me to have finer-grained control over what raises warnings and what does not.

We have  now [FS-1146](https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1146-scoped-nowarn.md) defined with even finer granularity.
