### ISSUE TITLE
Assign functions to getters and setters

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#851]
# Assign functions to getters and setters

I propose we allow assigning functions to getters and setters.

The existing way of approaching this problem in F# is duplicating the last parameter of the function.

Assuming https://github.com/fsharp/fslang-suggestions/issues/794 is implemented,
```fs
type C() =
    member _.ExistingSyntax with get() = 4 and set x = ()
    member _.NewSyntax1 with get = fun () -> 4
                             and set = fun x -> ()
    member _.NewSyntax2 with get() = 4 and set = ignore
    member _.NewSyntax3 with get = System.Console.ReadLine and set = System.Console.WriteLine
```

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Consistency with `let`-bound functions and members
2. Convenience - not having to remember this inconsistency

The disadvantages of making this adjustment to F# are none that I can think of.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: https://github.com/fsharp/fslang-suggestions/issues/794

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by abelbraaksma** [comment]
I'm not opposed to this per se, but I do feel a bit ambivalent. I'm afraid that this may introduce "more ways to do the same", and it can easily be confused with already existing syntax to assign a function to a property gettor. For instance:

```f#
type X() =
    member _.Prop1 = fun() -> 12      // gets easily confused
    member _.Prop2 with get() = 12
    member _.Prop3 with get x = 12 + x   // 'get' can already take any number of args
    member _.Prop4 with get() = fun x -> 12 + x   // or return a function
    member _.Prop5 = fun x -> 12 + x     // existing syntax to do the same
```

Basically, `get()` is currently _not special_, it works like any other left-hand function declaration. The `()` is there simply because that's what MSIL expects: it gets compiled to `get_PropX() = 42` (and a special declaration with `.property`, separate from this, for `PropX`, which calls into `get_PropX`). When you write `get()` you explicitly say: I want a gettor declaration with one argument that's `unit`. When you write `get x = 12 + x` you tell the compiler you don't want `unit`, but `int` as that first argument.

For consistency, if `get = fun() -> 12` is going to be equal to `get() = 12`, it should follow that `Prop = 12` and `Prop = fun() -> 12` are also equal. Or at least that is what people might expect. But these are currently distinct. We can leave them separate, but that may just confuse people more.

Likewise, when you write `let f() = 12` (a function that returns 12) it means something else than `let f = fun() -> 12` (assign a function that in turn returns 12). In most cases this difference is negligible, and often the the compiler will manage to eliminate the lambda. Once you add more parameters this difference becomes more apparent.

**Comment by Happypig375** [comment]
Function values are initialised once only at initialisation, just like in `let`s.

**Comment by Tarmil** [comment]
Whereas a function-valued property like this is created on every call:

```fsharp
member _.Prop = fun x -> x + 1
```

It's confusing enough already for beginners to have this distinction, I feel like adding a layer where a property defined `with get` would behave like a `let` would make it even worse.

**Comment by abelbraaksma** [comment]
> Function values are initialised once only at initialisation, just like in lets

Yes, if you move aside the closure initialization, but that's not my point.

**Comment by gusty** [comment]
I think thus suggestion is not just an alternative syntax.

The proposed syntax here will allow a side effect before the getter, to be executed only the first time the getter is accesed, please correct me if I'm wrong.

`... get = sideeffect (); fun () -> ...`

**Comment by abelbraaksma** [comment]
> to be executed only the first time the getter is accesed

@gusty, yes, it certainly seems that way. Though, that can be considered a benefit just as well, as a shortcut for `if isFirstTime then... `, though I'd argue that it'll only add to the confusion.

**Comment by dsyme** [comment]
While this makes sense technically, we decided not to go down this path in F# 1.0 and I don't particularly see reasons to revisit the decision.  There are advantages to making the parameters explicit, and it makes it clear that the properties are re-evaluated on each invocation.
