### ISSUE TITLE
new function `Map.mapKey` & `Map.mapEntry` & `Map.concat` & `Map.append`

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#873]
I propose we add new functions `Map.mapKey` and `Map.mapEntry` into Map module
```F#
let mp = Map.ofSeq [1,1]

let entries = mp |> Map.mapEntry (fun k v-> k*2,v*2)
let keys = mp |> Map.mapKey (fun k v-> k*2)
```

The existing way of approaching this problem in F# is 

```F#
let mp = Map.ofSeq [1,1]
let entries =
    mp
    |> Map.toSeq
    |> Seq.map(fun(k,v)-> k*2,v*2)
    |> Map.ofSeq

let keys =
    mp
    |> Map.toSeq
    |> Seq.map(fun(k,v)-> k*2,v)
    |> Map.ofSeq
```

**Comment by Swoorup** [comment]
`mapKey` could return duplicate keys, should that return `Map option` instead? 
similar issue with `mapEntry`. 

I don't find this particularly useful as the naming is confusing. I would rather just have
* `Map.keys: Map<'k,'v> -> Seq<'k>`, and
* `Map.values: Map<'k,'v> -> Seq<'v>`

and build my utility functions in my own library than on F# core.

**Comment by abelbraaksma** [comment]
> The existing way of approaching this problem in F# is

If I understand the proposal correctly, you want to map over keys and return a new map with only the keys altered, and you want to map over entries where the function creates a new entry for the map on each iteration?

Since a map is already a sequence, you can already do this. The most natural is for what you call `mapEntries`:

```f#
let map = Map.ofSeq [1,2]
let entries = map |> Seq.map (fun x -> x.Key + 1, x.Value + 1) |> Map.ofSeq
```

And to update the keys only, you can do something similar:

```f#
let map = Map.ofSeq [1,2]
let entries = map |> Seq.map (fun x -> x.Key + 1, x.Value) |> Map.ofSeq
```

Since maps are immutable, there's no way around recreating the map. Though I agree that it would be nice to be able to map over keys (in an undefined order). That this may lead to a duplicate-key exception is understandable, you get that now too if you call `Map.ofSeq`.

I also think that `Map` is generally lacking a lot of functionality to make it really useful. I mean, one of the most common operations on maps is to merge them, but there's no `Map.merge` and there's no trivial way to create it either (but not that hard).

A more adamant problem with maps is their performance. `ImmutableDictionary` in the `System.Collections.Immutable` namespace is 2x as fast for most operations, and sometimes much more. There's some debate currently in allowing a default dependency on the immutable assembly for implementation of immutable arrays. Perhaps once that's there we can also re-implement maps with `ImmutableDictionary`.

**Comment by xp44mm** [comment]
yes! thank you, map keys should resolve the conflicts:
```F#
let keys = 
    mp 
    |> Map.mapKey 
        (fun values -> List.head values)
        (fun k v-> k*2)

let keys = 
    mp 
    |> Map.mapKey 
        (List.exactlyOne)
        (fun k v-> k*2)
```

**Comment by xp44mm** [comment]
mapper can delay to another function, and the main content is collect value to a sequence of values. this is my implement code:
```F#
let fromDuplicateKeys (pairs:#seq<'k*'v>) =
    pairs
    |> Seq.groupBy fst
    |> Seq.map(fun(k,pairs)->
        let values =
            pairs |> Seq.map snd
        k,values
    )
    |> Map.ofSeq

let mapKey (getKey:'k->'v->'kk) (mp:Map<'k,'v>) =
    mp
    |> Map.toSeq
    |> Seq.map(fun(k,v)->
        let kk = getKey k v
        kk,v)
    |> fromDuplicateKeys

let mapEntry (getEntry:'k->'v->'kk*'vv) (mp:Map<'k,'v>) =
    mp
    |> Map.toSeq
    |> Seq.map(fun(k,v)-> getEntry k v)
    |> fromDuplicateKeys

let append (mp1:Map<'k,'v>) (mp2:Map<'k,'v>) =
    (Map.toSeq mp1, Map.toSeq mp2)
    ||> Seq.append
    |> fromDuplicateKeys

let concat (mps:#seq<Map<'k,'v>>) =
    mps
    |> Seq.map Map.toSeq
    |> Seq.concat
    |> fromDuplicateKeys
```

**Comment by dsyme** [comment]
These are not bad suggestions, but I don't find them compelling to add to FSharp.Core, partly because they don't particularly have a more efficient implementation when the internal data structure is available.  

This differs to say #768 

I will close this - mainly because of the lack of supporting voices - but please keep suggestions for FSharp.Core coming in.
