### ISSUE TITLE
Using QueryBuilder, show available commands

### ISSUE THREAD

**Issue by Thorium** [fsharp/fslang-suggestions#880]
It seems that `QueryBuilder`s using `CustomOperationAttribute`s are gaining some popularity, e.g. this is from Saturn:

```fsharp
let webApp =
    router {
        // ...
    }

let app =
    application {
        use_router webApp
        // ...
    }
```

...but as a user, how on earth I do know the available commands?
- The intellisense auto-complete is showing all the keywords in the universe, including `acos`, `asin`, ...
- The tooltips over the builder-type are not showing those either.

Currently I just open a new browser window, navigate to the GitHub-repository and read the source code. Is that the intended user experience?

**Comment by Thorium** [comment]
Btw, if I try to use `asin`, it throws an error:

> This control construct may only be used if the computation expression builder defines a 'Zero' method

...so the intellisense is not very intelligent here.

**Comment by ronaldschlenker** [comment]
That might be an issue of FSAC, because I can see that in VSCode and Rider, but not in Visual Studio (2017).

Also, the same behavior is for record field completion (using Rider / VSCode):

![image](https://user-images.githubusercontent.com/472222/84629100-12403700-aeea-11ea-98d8-3f6cb21b4619.png)

For both (record fields and builder custom operations), the fields or custom operations appear, but they don't appear on top. Instead it seems that the intellisense list is sorted alphabetically.

In Visual Studio, record field and builder methods appear on top of the list.

**Comment by ronaldschlenker** [comment]
I created an issue in FSAC, so propably close this one?

**Comment by Thorium** [comment]
I had the problem also in VS2019.

**Comment by auduchinok** [comment]
> That might be an issue of FSAC, because I can see that in VSCode and Rider, but not in Visual Studio (2017).

Rider doesn't use FSAC though. 🙂 It uses a modified FCS build and VS does a similar thing.
And all three tools integrate into providing items to these completion lists differently, so there are chances each tool will have to fix it separately even if FCS provide items sorted properly in the first place.

**Comment by baronfel** [comment]
Thanks for opening the FSAC issue, @ronaldschlenker. I'll close this then.

**Comment by Thorium** [comment]
@baronfel as far as I understand, I was not using FSAC. This is a language suggestion, I hope it will be added to Visual Studio.

**Comment by cartermp** [comment]
This is more of a tooling concern and not a language suggestion. I filed this to make it tracked: https://github.com/dotnet/fsharp/issues/9534
