### ISSUE TITLE
may i use known members when constructing a value?

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#899]
I propose we can use the defining data:
```f#
> (3,sprintf "%d" x.[0]) as x;;
it: (3,"3")

> [|8;y.[0]/2|] as y;;
it:[|8;4|]

> {|x=100;y=z.x|} as z;;
it:{|x=100;y=100|}

```

**Comment by abelbraaksma** [comment]
I don't understand what you're proposing here, what problem you're trying to solve, or what change to the syntax you're after, if any. And what's plug and play, and what's a `when` declaration? Could you use the issue template and fill in the questions?

(it looks as if you're suggesting to change how let bindings work, like an alternative `let... in` syntax, but there's just too little here to be be certain of anything)

**Comment by TheJayMann** [comment]
To me, it appears, what is being proposed, is to allow a tuple, array, and anonymous record to be bound to a name before the tuple, array, or anonymous record has been fully constructed, allowing later parts of the tuple, array, or anonymous record to be defined by earlier contents of the tuple, array, or anonymous record.

First example is a two element tuple, assigned to the name `x`, with the first element defined as 3, and the second element defined by passing the first element (probably should use `fst` function, as tuples do not support indexing) into the sprintf function, specifying a format of "%d".  The second example is creating a two element array, bound to the name `y`, specifying 8 as the first element, and taking half of the value of the first element as the second element.  The final example creates an anonymous record with the fields `x` and `y`, assigns to the name `z`, assigns the `x` field the value of 100, and assigns the `y` field the value of the `x` field.

**Comment by abelbraaksma** [comment]
So, from the examples you deduct a feature like delayed declarations? It's a lot of assumptions ;). 

Basically:

```f#
> (3,sprintf "%d" (fst x)) as x;;
```

Would then be a different way of writing

```f#
> let x = let x = 3 in x, sprintf "%d" x;;
```

Hmm, I wonder what user cases that solves, and how it's supposed to work together with existing inference rules and syntax.

Either way, @xp44mm, could you rewrite your proposal such that it explains what you actually want added and why? See other examples, and the template.

**Comment by xp44mm** [comment]
@TheJayMann you have getten my propose.  without this feature:

```F#
let x = 3
let y = sprintf "%d" (fst x)
sprintf "%A" (x,y)
```

this feature will be:

```F#
sprintf "%A"
<| (3,sprintf "%d" x.[0]) as x
```

some times you void break a long chain with this feature.

**Comment by xp44mm** [comment]
@abelbraaksma let binding return unit, is a statement. and x as y is a expression that it return y. can be used in another expression.

**Comment by xp44mm** [comment]
this feature hope to use path reference known part or membr. array include tuple reference by indexing. and record by name.

**Comment by realvictorprm** [comment]
@xp44mm I see you have difficulties expressing yourself in English. You could give DeepL a try to get better translations of what you mean in your native language in English 😅

https://www.deepl.com/translator

**Comment by yatli** [comment]
@xp44mm or tag me and send zh-CN, and we can better rephrase together. :)

**Comment by abelbraaksma** [comment]
> let binding return unit, is a statement.

Yes, but not `let... in`, which returns whatever is after `in`, and does mostly what you proposed.

I'm OK with the English, but at least make your examples work, because that's what should show your purpose. You consistently mix lists and tuples, which makes one wonder whether you want to treat tuples as lists (as @TheJayMann pointed out), or propose something else (I now know it's the latter).

Please update the original text (you can edit it), and maybe take @yatli up on his offer to help with translation, and have a look at earlier comments on making the code work. 

In the proposal as I understand it, F# is a language were type info flows top to bottom, so that incomplete types (like a module) can already partially pass while you're typing.

Here you propose the opposite, where the only way to find out where the magic variable points to is to look forward. And then that magic variable changes with each line of the record. This opens up very hard to answer questions, like this:

```f#
let f v = {|
    A = v
    B = x.A + v
    C = x.B + x.A
|} as x
```

What type should `x` be? What type should each field be? Maybe it's possible to answer those questions, and maybe it's possible to come up with a solution that allows for identifiers to change type from line to line, but that's a whole lot of complexity.

I'm not necessarily unsympathetic to the idea, but it touches on virtually every aspect of type inference, and changes many core ideas of the F# language that have been the way they are since the very beginning. 

Another thing to consider: it looks very much like `as self`, which already exists, except that here it's applied outside of its own context.

**Comment by xp44mm** [comment]
> What type should x be? What type should each field be? 

@abelbraaksma , x's scope just limit in the expression, the code can directly transpile to:
```F#
let f v = 
    (fun () ->
        let A = v
        let B = A + v
        let C = B + A
        {|
            A=A;B=B;C=C;
        |})()
```

> Another thing to consider: it looks very much like as self, which already exists

yes! have existed two feature that i known. they are:
```F#
type SomeClass() as self =
    ...

let rec somefun () =
    ...
```

**Comment by abelbraaksma** [comment]
Thanks, all that info helps, and please, update the main issue on top, so that people understand what you're after. Including the transpile part.

It doesn't, however, answer the question what the type of `x` is in `as x`. In `as self`, it's typed, and compiler only has rui create a hidden field that's an instance of the class. The same technique cannot be used here.

**Comment by xp44mm** [comment]
@abelbraaksma x and his path can be eliminated. so need not to compliant old version.

**Comment by dsyme** [comment]
I understand the suggestion, however this was effectively decided early in F# that we wouldn't allow this kind of binding for expressions.

Thank you for taking the time to make the suggestion.
