### ISSUE TITLE
LLVM backend for F#

### ISSUE THREAD

**Issue by Zuzuk-null** [fsharp/fslang-suggestions#900]
What do you think about compiling F# to LLVM IR? There are already compilers F# to javascript and even to quantum assembler. I suggest this because .NET doesn't support the functional style very well, so sometimes very strange things can be found in decompiled IL. F# would be able to become a little more independent and faster by being able to compile to native code with optimization.

P.S. Sorry for the quality of the text, I used a machine translator

**Comment by davidglassborow** [comment]
There was also some work on an Erlang backend for F

**Comment by charlesroddie** [comment]
The level to do this is .Net not F#.

You can already run F# code compiled using a LLVM toolchain using mono. https://github.com/dotnet/corert/issues/8230
You can do AOT compilation using CoreRT and .Net Native and there are plans for [LLVM in CoreRT](https://github.com/dotnet/corert/issues/7200).

What F# needs is AOT and linker friendliness so that these approaches work well. I am compiling a suggestion to this effect at the moment which will focus on string methods.

> There are already compilers F# to javascript

These were written at a time when WASM did not exist and there was no way to run .Net code in the browser. They got F# working in the browser, at the cost of .Net compatibility. I don't believe this approach would have been taken if the relevant libraries were started now, since .Net WASM support is close to ready (should have official Blazor with AOT WASM in .Net 6).

**Comment by davidglassborow** [comment]
Excellent point @charlesroddie, see also the helpful image in this Xamarian documentation about how LLVM is currently used when targeting iOS as an optional optimisation step - https://docs.microsoft.com/en-gb/xamarin/ios/internals/architecture#aot

**Comment by cartermp** [comment]
There's no desire for anyone on the team to rebase atop LLVM and rewrite all the F# semantics that currently rely on .NET as the runtime.

If this interests anyone, they're free to depend on the F# Compiler Service and write their own dialect of F# similar to how Fable does things.

**Comment by colltoaction** [comment]
FYI https://github.com/speakez-llc/fsharp-mlir-hello
