### ISSUE TITLE
Lambda delegates caching

### ISSUE THREAD

**Issue by Lanayx** [fsharp/fslang-suggestions#910]
# Title of Suggestion

I propose to add the caching for delegates similar to csharp
[Csharp sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5lqZwB0AMgJYB2AjvigMyYzoDC6A3ul+st5o1noAeLKgB86ALIAKAJQdefblADs6SgFMA7gG0Auh3Rx0AX2IBlDQBsNAYwAu0gB7oAvBKfEAKgHtz9gCcqAHM5WTo+E2QTIA)
[Fsharp sharplab](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfA9gBwKYDsAEBlAnhAC7oC2AsAFBH4bYDCAFAJTYC8V2X2pZARugBO2APoA6ALIt22Tt3kBtRNgCM2RAF11APjzoAjmNIBDVNkZgArjgBe2ALS6bYgCrJcRQQEtMAcxbMQA==)

The existing way of approaching this problem in F# is unknown to me (probably ignoring the problem).

## Pros and Cons 

The advantages of making this adjustment to F# is performance boost, since functions are the first-class citizens of the language and used everywhere, it will be most evident in operations over collections.

The disadvantages of making this adjustment to F# are some hidden issues that are not clear right now. Another disadvantage is that [C# issue is still open](https://github.com/dotnet/roslyn/issues/5835) and we don't know how it will be handled

## Extra information

Estimated cost (L): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
This is approved, we should have done this long ago

**Comment by En3Tho** [comment]
I have a related question. Is there a plan to optimize FSharpFuncs binding in case there are static only functions/methods being bound? Eg. something like (Guid.Parse >> toString >> Guid.Parse>> toString >> Guid.Parse) where toString is simple ToString() call actually creates lots of FSharpFuncs instead of only one, and all of those methods not capturing. Can't they be grouped into single func?
https://sharplab.io/#v2:DYLgZgzgNAJiDUAfA9gBwKYDsAEBlAnhAC7oC2AsAFCnIwCuw62AKusdgLxXY/aNHYiyXEQBOAS0wBzbAA9OcgHTNhYyVIAUASm69+2VAENREdAEkpmZKKbyNh7CGzEJ07AFoAfNgDkhrQoO8oje4pbW6ADccro8+iTE2pyxvDxGJubhNtgaAMLImBDIjIoASuiGMAAykujaARoA4nTiMIoACsam2J7eQiKuMr3Yza0dXejD/Wpuw6NtnRlaQA==

**Comment by En3Tho** [comment]
@dsyme Can you check my question please? If needed, I can create another suggestion/issue

**Comment by Daniel-Svensson** [comment]
Since lambads are compiled to classes it should be possible to make the class `beforefieldinit`  and add a a `static initonly` field with a cached instance (which is initialized in the static constructor). 
This pattern is recognized well by the JIT compiler and should result on good machine code

E.g something similar to the IL generated for the following C# code snipped
https://sharplab.io/#v2:EYLgdgpgLgZgHgGiiAlgGwD4AEBMBGAWACgsBmAAl3IGFyBvY8pyirAFnIFkAKASnsbMhzACIA6AJJgAzlACGYAMYRJYAG4B7ANYRubHLwDcgpgF8Txc0WLEylHORHEGRIXax4AbOQBOEOQAmGmBoAJ6O5FKyCsrkALzkkADujnzGriYs5GooPlAArnJo5ChgUJHq2rql5XL8cQB85HLkAFTkOOmmQA=

**Comment by kerams** [comment]
Would this be reasonably difficult for someone with no prior experience with FSC?
