### ISSUE TITLE
record member borrow 

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#942]
I propose we When a record type contains all fields for another record type, you can borrow the functionality of all the custom instance members of that record type.

```F#
type Point2d = 
    {
        x:float
        y:float
    }
    member this.length = (this.x*this.x+this.y*this.y)**0.5

type Point3d = {
    x:float
    y:float
    z:float
}

// usage:
let p3d = {x=3.0;y=4.0;z=0.0}
printf "%A" p3d.on<Point2d>.length
>> 5.0

// current:
printf "%A" {x=p3d.x;y=p3d.y}.length
>> 5.0
```

It can be used to replace traditional inheritance mechanisms and maybe it is more flexible than multiple inheritance.

**Comment by abelbraaksma** [comment]
> It can be used to replace traditional inheritance mechanisms and maybe it is more flexible than multiple inheritance.

I believe this is called "mixins" in Ruby. Though F# is functional and I'm not sure a feature that resembles multiple inheritance would really have a place in it. It's not even available in C#. 

But your proposal isn't really about inheritance at all, if I understand your example correctly. You merely want instance methods of type X, where X contains
a subset of Y, to be able to be used regardless whether the instance is X or Y.

This is currently possible with SRTP. There's some discussion on allowing automatic static restrictions on certain cases. If such a feature comes around, you could use an inlined method to get this behavior.

Another way is, of course, to use regular inheritance. At least that wouldn't violate the OO principle of sending messages to a given instance of a type, when calling its member. This fundamental principle would be broken if this 'mixin' style were allowed (which isn't necessarily bad, but such fundamental changes are usually very hard to retrofit in a language).

**Comment by abelbraaksma** [comment]
Btw, as a good example, often people have a property like `Value`, `Name`or `Size` on each record of a given type. It's currently trivial to create a single function that just requires that property to be present. It's a common F# programming paradigm.

In your case that would mean have a function that operates on any object having `X` and `Y` properties. It's not exactly the same. But by putting that function in a module with the same name you will get the same behavior, albeit in toulouse) typical functional point free style (as opposed to dotting into it). Maybe that helps in your scenario?

**Comment by xp44mm** [comment]
There is a need to strictly distinguish between different types because they come with their own custom functionalities, and if two immutable data does not have custom functionalities, there is no need to distinguish them from each other. A named type represents a scenario that collects several related functionalities, centered on an immutable data type.

**Comment by TheJayMann** [comment]
SRTP is statically resolved type parameters.  They are generic type parameters beginning with `^` instead of `'`.  They allow adding extra constraints that .NET generic constraints do not support, such as requiring a property be present.  You should be able to do something similar to the following example.
```fsharp
let inline length (point: ^p) =
    let x = (^p: (member x: float) p)
    let y = (^p: (member y: float) p)
    (x * x + y * y) ** 0.5
```
With the above defined `length` function, you can pass in any value so long as it has a property named `x` of type `float` and a property named `y` of type `float`.  And, since record fields are exposed in .NET as properties, record fields will work as well.

**Comment by abelbraaksma** [comment]
Yep, that's precisely what I meant. And if you want to limit it further, you can use a marker interface to restrict it to a more succinct set of types. However, this may quickly explode and you'll want to revisit your code and use composition paradigms instead of ducktyping (the style above with SRTP is often considered ducktyping, as with duck tape, you can combine otherwise unrelated types, just like you proposed).

 > A named type represents a scenario that collects several related functionalities, centered on an immutable data type.

I agree and that was indeed part of my point. Which is why supporting this out of the box is probably not a good idea, as that would violate that single responsibility principle: it would open the door for unrelated types to share the same functionalities merely by them having properties that are the same in name and type only.

**Comment by cartermp** [comment]
This is definitely an interesting idea that's highly related to record inheritance. I won't say "probably not" right now, since I did discuss with @dsyme what record inheritance of a sort could look like and it wasn't met with an immediate rejection. If this were to be considered, it would likely be tied with https://github.com/fsharp/fslang-suggestions/issues/898

But for now, yes, SRTP is a great alternative to share functionality between records. Here is another example of how you can do that:

```
module M =
    let inline private (|HasName|) x = (^a : (member Name: string) x)

    let inline printName (HasName name) = printfn $"{name}"

type Person1 = { Name: string; Age: int }
type Person2 = { Name: string; Age: int; IsFunny: bool }

type Name(name) =
    member _.Name = name

let p1 = { Name = "Phillip"; Age = 30 }
let p2 = { Name = "Phillip"; Age = 30; IsFunny = false }
let nm = Name "Phillip"

M.printName p1
M.printName p2
M.printName nm
```

**Comment by xp44mm** [comment]
If the type has members with the same name as `printName`, your method does not work. Also, when reading the code, the reader does not know where the method `printName` is defined.

```F#
type Point2d = 
    {
        x:float
        y:float
    }
    member p.sum= p.x+p.y

type Point3d = 
    {
      x:float
      y:float
      z:float
    }
    member p.sum= p.x+p.y+p.z

let p3d = {x=3.0;y=4.0;z=1.0}

p3d.sum //own method.
p3d.on<Point2d>.sum //The method is on the Point2d.
```

**Comment by vzarytovskii** [comment]
```fsharp
p3d.on<Point2d>.sum //The method is on the Point2d.```
This looks too obscure and implicit to me, what should be done here?
Implicit "inheritance"? Implicitly create Point2d from p3d? Something else?

**Comment by xp44mm** [comment]
Inheritance is not recommended because inheritance makes the two types tightly coupled. It is easiest to create a new instance implicitly. There are, of course, other ways to do this, such as compiling a type member into a normal function and passing in the associated dependent fields as named parameters.

```F#
module Point2dCustomMembers

let sum x y = x + y
```

in another position:
```F#
p2d.sum // => sum (p2d.x) (p2d.y)
p3d.sum // => sum (p3d.x) (p3d.y)
```

**Comment by abelbraaksma** [comment]
> If the type has members with the same name as printName, SRTP method does not work

Actually, it does work. Since the SRTP functions reside in a module, it gives no conflict, because you'll be calling the module, not the type, as is shown in @cartermp's example.

**Comment by dsyme** [comment]
It feels like the natural generalization of this would be some built-in fancy mechanism to get from one type to another through a set of structural rules, e.g. 

    someObject.as<SomeOtherType>

where we would have a big bucket of rules about how one type gets to look like another type without loss of information - most rules would be structural but `op_Implicit` and widenings could be included I guess

**Comment by dsyme** [comment]
This isn't going to happen in its suggested form (it is impractical to implement)

I'll close this since numerous other issues track subtyping requests for records
