### ISSUE TITLE
add isNotNull to FSharp.Core

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#99]
# add isNotNull to FSharp.Core [13419354]

**Submitted by Gauthier Segay on 4/13/2016 12:00:00 AM**  
**2 votes on UserVoice prior to migration**  

Using "not (isNull a)" in conditions forces usage of parens or pipe operator and is not optimal readability compared to "a |> isNotNull" or "isNotNull a"
let inline isNotNull a = not (isNull a)
in absence of this function, people often take the shortcut of "a <> null" which according to lint is not optimal.
## Response

*\* by fslang-admin on 6/13/2016 12:00:00 AM **

Declining per my comment below.
Don Syme
F# Language Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13419354)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13419354-add-isnotnull-to-fsharp-core.md#comments)

**Comment by abelbraaksma** [comment]
When this was converted, the comments _after_ the decline showed (by Daniel Robinson, 13 Sept 2016):

> Did I miss something? It looks like this was added to FSharp.Core -
https://github.com/Microsoft/visualfsharp/blob/36050db52bc4d4876b16b7f62b5e67cdee34f2aa/src/fsharp/FSharp.Core/prim-types.fsi#L2157-L2158

So: this was declined because F# should not include negations of operators or functions and not make exceptions, but I think it has made it into the Core after all.

**Comment by dsyme** [comment]
@abelbraaksma Well spotted :)

@forki Ideally this should be removed from FSharp.Core , see your commit here: https://github.com/Microsoft/visualfsharp/commit/374bbc85eb702f7c5a2b0ce996441a5311b656f6

**Comment by forki** [comment]
Will do. But keep in mind that FCS AFAIK already "released" this.

Am 08.12.2016 02:12 schrieb "Don Syme" <notifications@github.com>:

**Comment by dsyme** [comment]
> Will do. But keep in mind that FCS AFAIK already "released" this.

FCS doesn't ship a new FSharp.Core.  Mono is still shipping FSharp.Core 4.1.0.0 (though maybe it gets rebuilt with this in it)

**Comment by KevinRansom** [comment]
@dsyme why are we removing this API?  it's certainly not the only new public Api .core.dll.

And on an entirely different note ... why does FCS not ship an FSharp.Core.dll? that seems a bit weird to me

**Comment by dsyme** [comment]
> @dsyme why are we removing this API? it's certainly not the only new public Api .core.dll.

It was never approved during the design process (indeed was explicitly rejected, because we have a rule not to put "NotXYZ" predicates in the core library), it just crept in during some code cleanup.  

> And on an entirely different note ... why does FCS not ship an FSharp.Core.dll? that seems a bit weird to me

FCS is a DLL shipped as a nuget package with dependency on the FSharp.Core nuget package >= 4.4.0.0 (previously >= 4.3.1.0)

**Comment by dsyme** [comment]
Closing as declined - we added ``isNull`` but not the negative
